<div class="col-xs-12 col-md-6" id="game_<?php echo $wo['game']['id'];?>">
	<div class="wow_content wow_pop_gam_list">
		<a href="<?php echo $wo['game']['url'];?>" data-ajax="?link1=game&id=<?php echo $wo['game']['id'];?>">
			<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
				<img src="<?php echo $wo['game']['game_avatar'];?>" alt="<?php echo $wo['game']['game_name']; ?> Profile Picture" />
			</div>
			<div class="game-name"><?php echo $wo['game']['game_name']; ?></div>
			<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M9,2V7.5L12,10.5L15,7.5V2H9M2,9V15H7.5L10.5,12L7.5,9H2M16.5,9L13.5,12L16.5,15H22V9H16.5M12,13.5L9,16.5V22H15V16.5L12,13.5M11,18H13V20H11V18Z" /></svg> <?php echo $wo['game']['players']; ?> <?php echo $wo['lang']['users_playing']; ?></p>
		</a>
	</div>
</div>