<?php if(!empty($wo['story']['blog_id'])) { ?>
<div class="post-fetched-url wo_post_fetch_blog">
   <a href="<?php echo $wo['story']['blog']['url'];?>">
      <div class="fetched-url-text">
         <h4>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book">
               <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
               <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
            </svg>
            <?php echo $wo['story']['blog']['title'];?>
         </h4>
         <div class="description"><?php echo $wo['story']['blog']['description'];?></div>
      </div>
      <?php if (!empty($wo['story']['blog']['thumbnail'])) {?>
      <div class="post-fetched-url-con">
         <img src="<?php echo $wo['story']['blog']['thumbnail'];?>" class="<?php echo Wo_RightToLeft('pull-left');?>" alt="<?php echo $wo['story']['blog']['title'];?>"/>
      </div>
      <?php } ?>
      <div class="clear"></div>
   </a>
</div>
<?php } ?>