<?php if(!empty($wo['story']['forum_id']) && !empty($wo['story']['forum'])) { ?>
<div class="post-fetched-url wo_post_fetch_blog">
   <a href="<?php echo $wo['config']['site_url'].'/forums/'.$wo['story']['forum']['id'];?>">
      <div class="fetched-url-text">
         <h4>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book">
               <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
               <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
            </svg>
            <?php echo $wo['story']['forum']['name'];?>
         </h4>
         <div class="description"><?php echo $wo['story']['forum']['description'];?></div>
      </div>
      <div class="clear"></div>
   </a>
</div>
<?php } ?>