<?php   
if (!empty($wo['story']['parent_id'])) {
    $post_shared_from = $wo['post_shared_from'] = Wo_PostData($wo['story']['parent_id']); ?>
<div class="post-heading">
   <div class="<?php echo Wo_RightToLeft('pull-left');?> image">
      <a href="<?php echo $wo['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['publisher']['username']?>">
      <img src="<?php echo $wo['story']['publisher']['avatar']; ?>" id="updateImage-<?php echo $wo['story']['publisher']['user_id']?>" class="avatar" alt="<?php echo $wo['story']['publisher']['name']; ?> profile picture">
      </a>
   </div>
   <div class="<?php echo Wo_RightToLeft('pull-right');?>">
      <?php  if ($wo['story']['admin'] === true || $wo['story']['group_admin'] === true) { ?>
      <span class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down">
               <polyline points="6 9 12 15 18 9"></polyline>
            </svg>
         </a>
         <ul class="dropdown-menu post-privacy-menu post-options" role="menu">
            <?php if ($wo['loggedin'] == true && !empty($wo['story']['offer_id']) && (Wo_IsModerator() || Wo_IsAdmin() || $wo['story']['offer']['user_id'] == $wo['user']['id'])) { ?>
               <li>
                  <div class="pointer" onclick="Wo_OpenOfferEditBox(<?php echo $wo['story']['offer_id']; ?>);"><?php echo $wo['lang']['edit_offer'];?></div>
               </li>
            <?php } ?>
            <?php if ($wo['story']['admin'] === true && empty($wo['story']['product_id']) && empty($wo['story']['shared_from'])) { ?>
            <li>
               <div class="pointer" onclick="Wo_OpenPostEditBox(<?php echo $wo['story']['id']; ?>);"><?php echo $wo['lang']['edit_post'];?></div>
            </li>
            <?php } else if (!empty($wo['story']['product_id']) && empty($wo['story']['parent_id'])) { 
               if ($wo['story']['product']['status'] == 0) { ?>
            <li>
               <div class="pointer mark-as-sold-post" onclick="Wo_MarkAsSold(<?php echo $wo['story']['id']; ?>, <?php echo $wo['story']['product_id']; ?>);"><?php echo $wo['lang']['mark_as_sold']?></div>
            </li>
            <li>
               <a class="pointer" href="<?php echo Wo_SeoLink('index.php?link1=edit-product&id=' . $wo['story']['product_id']);?>"><?php echo $wo['lang']['edit_product']?></a>
            </li>
            <?php } } ?>
            <li>
               <div class="pointer" onclick="Wo_OpenPostDeleteBox(<?php echo $wo['story']['id']; ?>);"><?php echo $wo['lang']['delete_post'];?></div>
            </li>
            <li>
               <div class="pointer disable-comments" onclick="Wo_DisableComment(<?php echo $wo['story']['id']; ?>, <?php echo $wo['story']['comments_status']; ?>);"><?php echo ($wo['story']['comments_status'] == 1) ? $wo['lang']['disable_comments'] : $wo['lang']['enable_comments'];?></div>
            </li>
            <li>
               <hr>
            </li>
            <li>
               <a href="<?php echo $wo['story']['url'];?>" target="_blank"><?php echo $wo['lang']['open_post_in_new_tab'];?></a>
            </li>
            <li>
               <hr>
            </li>
            <?php if (empty($wo['story']['recipient']) && $wo['story']['admin'] === true) { ?>
            <?php if ($wo['story']['is_group_post'] == false) { ?>
            <li>
               <?php
                  $pin_post_id = $wo['story']['publisher']['id'];
                  $pin_post_text = 'profile';
                  if (!empty($wo['story']['page_id'])) {
                     $pin_post_id = $wo['story']['page_id'];
                     $pin_post_text = 'page';
                  } else if (!empty($wo['story']['group_id'])) {
                     $pin_post_id = $wo['story']['group_id'];
                     $pin_post_text = 'group';
                  }  else if (!empty($wo['story']['event_id'])) {
                     $pin_post_id = $wo['story']['event_id'];
                     $pin_post_text = 'event';
                  }
                  ?>
               <div class="pin-post pointer" onclick="Wo_PinPost(<?php echo $wo['story']['id']; ?>, <?php echo $pin_post_id;?>, '<?php echo $pin_post_text; ?>');">
                  <?php if($wo['story']['is_post_pinned'] === true) { ?>
                  <?php echo $wo['lang']['unpin_post'];?>
                  <?php } else { ?>
                  <?php echo $wo['lang']['pin_post'];?>
                  <?php } ?>
               </div>
            </li>
            <?php } } ?>
            <?php if (!empty($wo['story']['album_name']) && ($wo['story']['group_admin'] === false || $wo['story']['admin'] === true)) {?>
            <li>
               <a href="<?php echo Wo_SeoLink('index.php?link1=create-album&album=' . $wo['story']['id']);?>"><?php echo $wo['lang']['add_photos'];?></a>
            </li>
            <?php } ?>
            <?php $hr = 0; if ($wo['config']['pro'] == 1 && ($wo['story']['group_admin'] === false || $wo['story']['admin'] === true)) { ?>
            <li>
               <?php if ($wo['user']['is_pro'] == 0) {  ?>
               <a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" data-ajax="?link1=go-pro"><?php echo $wo['lang']['boost_post']; ?></a>
               <?php } else if ($wo['user']['is_pro'] == 1 && in_array($wo['user']['pro_type'], array_keys($wo['pro_packages'])) && $wo['pro_packages'][$wo['user']['pro_type']]['posts_promotion'] > 0) {?>
               <?php if ($wo['story']['is_post_boosted'] == 0) { ?>
               <div class="boost-post pointer" onclick="Wo_BoostPost(<?php echo $wo['story']['id']; ?>)"><?php echo $wo['lang']['boost_post']; ?></div>
               <?php } else { ?>
               <div class="boost-post pointer" onclick="Wo_BoostPost(<?php echo $wo['story']['id']; ?>)"><?php echo $wo['lang']['unboost_post']; ?></div>
               <?php } ?>
               <?php } else if ($wo['user']['is_pro'] == 1 && $wo['user']['pro_type'] == 1) { $hr = 1; ?>
               <?php } ?>
            </li>
            <?php if ($hr == 0) { ?>
            <?php } } ?>
         </ul>
      </span>
      <?php  } elseif ($wo['loggedin'] == true) { ?>
      <span class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="pointer">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down">
                  <polyline points="6 9 12 15 18 9"></polyline>
               </svg>
            </span>
         </a>
         <ul class="dropdown-menu post-privacy-menu post-options post-recipient" role="menu"  >
            <?php if (Wo_IsAdmin()): ?>
            <li>
               <div class="pointer" onclick="Wo_OpenPostDeleteBox(<?php echo $wo['story']['id']; ?>);"><?php echo $wo['lang']['delete_post'];?></div>
            </li>
            <?php endif; ?>
            <li>
               <div class="save-post pointer" class="save-post" onclick="Wo_SavePost(<?php echo $wo['story']['id']; ?>);">
                  <?php if($wo['story']['is_post_saved'] === true) { ?>
                  <?php echo $wo['lang']['unsave_post'];?>
                  <?php } else { ?>
                  <?php echo $wo['lang']['save_post'];?>
                  <?php } ?>
               </div>
            </li>
            <li>
               <div  class="report-post pointer" onclick="Wo_ReportPost(<?php echo $wo['story']['id']; ?>);">
                  <?php if($wo['story']['is_post_reported'] === true) { ?>
                  <?php echo $wo['lang']['unreport_post'];?>
                  <?php } else { ?>
                  <?php echo $wo['lang']['report_post'];?>
                  <?php } ?>
               </div>
            </li>
            <li>
               <a href="<?php echo $wo['story']['url'];?>" target="_blank"><?php echo $wo['lang']['open_post_in_new_tab'];?></a>
            </li>
            <li>
               <a class="pointer" onclick="Wo_HidePost(<?php echo $wo['story']['id'];?>);"><?php echo $wo['lang']['hide_post'];?></a>    
            </li>
         </ul>
      </span>
      <?php } ?>
   </div>
   <div class="meta">
      <div class="title h5">
         <span class="user-popover" data-type="<?php echo $wo['story']['publisher']['type']; ?>" data-id="<?php echo $wo['story']['publisher']['id']; ?>">
         <a href="<?php echo $wo['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['publisher']['username']; ?>"><b><?php echo $wo['story']['publisher']['name']; ?></b></a>
         </span>
         <?php if($wo['story']['publisher']['verified'] == 1) { ?>
         <span class="verified-color">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>">
               <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
            </svg>
         </span>
         <?php } ?>
		 
		 <?php if (!empty($wo['story']['publisher']['is_open_to_work']) && $wo['config']['website_mode'] == 'linkedin') { ?>
			<span class="wo_open_job_badge" title="<?php echo($wo['lang']['open_to_work']); ?>" data-toggle="tooltip"><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg></span>
		<?php } ?>
		 
         <?php if (isset($wo['story']['publisher']['is_pro'])) { 
            if(Wo_IsUserPro($wo['story']['publisher']['is_pro']) === true) { ?>
         <?php 
            $user_pro_type = Wo_GetUserProType($wo['story']['publisher']['pro_type']);
            ?>
         <span style="color:<?php echo $user_pro_type['color_name'];?>">
         <?php 
            if (!empty(in_array($wo['story']['publisher']['pro_type'], array_keys($wo['pro_packages'])) && !empty($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['image'])) && $_COOKIE['mode'] == 'day') { ?>
         <img src="<?php echo($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['image']) ?>" class="pro_packages_icon_inline">
         <?php }
         elseif (!empty(in_array($wo['story']['publisher']['pro_type'], array_keys($wo['pro_packages'])) && !empty($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['night_image'])) && $_COOKIE['mode'] == 'night') { ?>
            <img src="<?php echo($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['night_image']) ?>" class="pro_packages_icon_inline">
         <?php }
         else{ ?>
         <i class="fa fa-<?php echo $user_pro_type['icon'];?> fa-fw" title="<?php echo $user_pro_type['type_name'];?>" data-toggle="tooltip"></i>
         <?php } ?>
         </span>
         <?php } } ?>
         <span class="user-popover" data-type="<?php echo $wo['story']['shared_from']['type']; ?>" data-id="<?php echo $wo['story']['shared_from']['id']; ?>">         
         <span><?php echo $wo['lang']['shared_a_post']; ?></span> 
         </span>
         <a href="<?php echo $post_shared_from['url']; ?>" class="pointer"><span style="color: #666;"><?php echo strtolower($wo['lang']['post']); ?></span></a>
         </span>
         &nbsp;
         <?php if ($wo['story']['shared_from'] && is_array($wo['story']['shared_from'])): ?>
         <span class="user-popover" data-type="<?php echo $wo['story']['shared_from']['type']; ?>" data-id="<?php echo $wo['story']['shared_from']['id']; ?>">
            <span><?php echo $wo['lang']['shared']; ?></span> 
            <a href="<?php echo $wo['story']['shared_from']['url']; ?>" class="pointer no_decor" data-ajax="?link1=timeline&u=<?php echo $wo['story']['shared_from']['username']; ?>"><b><?php echo $wo['story']['shared_from']['name']; ?></b></a>
            <?php if($wo['story']['shared_from']['verified'] == 1) { ?>
            <span class="verified-color">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip">
                  <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
               </svg>
            </span>
            <?php } ?>
         </span>
         <?php endif; ?>
         <?php if ($wo['story']['shared_from'] && is_array($wo['story']['shared_from'])): ?>
         <span>  
         <a href="<?php echo $wo['story']['post_url']; ?>" class="pointer"><span style="color: #666;"><?php echo strtolower($wo['lang']['post']); ?></span></a>
         </span>
         <?php endif; ?>
         <?php if ($wo['story']['recipient_exists'] == true) {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <span class="user-popover" data-type="<?php echo $wo['story']['recipient']['type']; ?>" data-id='<?php echo $wo['story']['recipient']['id']; ?>'>
            <a href="<?php echo $wo['story']['recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['recipient']['username']; ?>">
            <b><?php echo $wo['story']['recipient']['name']; ?></b>
            </a>
            <?php if($wo['story']['recipient']['verified'] == 1) { ?>
            <span class="verified-color">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip">
                  <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
               </svg>
            </span>
            <?php } ?>
         </span>
         <?php } ?>
         <?php if (!empty($wo['story']['page_event_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['created_new_event'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['fund_id']) && empty($wo['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['created_donation_request'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['fund_raise_id']) && empty($wo['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['donated_to_request'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['offer_id']) && empty($wo['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['created_offer'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['event_id']) && $wo['page'] != 'events') {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <a href="<?php echo $wo['story']['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo $wo['story']['event']['id']; ?>"><b><?php echo $wo['story']['event']['name']; ?></b></a>
         <?php } ?>
         <?php if ($wo['story']['group_recipient_exists'] == true && $wo['page'] != 'group') {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <span class="user-popover" data-type="<?php echo $wo['story']['group_recipient']['type']; ?>" data-id='<?php echo $wo['story']['group_recipient']['id']; ?>'>
         <a href="<?php echo $wo['story']['group_recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['group_recipient']['username']; ?>">
         <b><?php echo $wo['story']['group_recipient']['name']; ?></b>
         </a>
         </span>
         <?php } ?>
         <?php if (!empty($wo['story']['album_name']) && empty($wo['story']['shared_from'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['added_new_photos_to'];?> <b><a href="<?php echo $wo['story']['url']; ?>" data-ajax="?link1=post&id=<?php echo $wo['story']['id'];?>"><?php echo $wo['story']['album_name']; ?></a></b></small>
         <?php } ?>
         <?php if (!empty($wo['story']['product_id']) && empty($wo['story']['shared_from'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['added_new_product_for_sell']; ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['forum_id'])  && empty($wo['story']['shared_from']) && !empty($wo['story']['forum'])) {  ?>
         <!-- <small class="small-text"><?php echo $wo['lang']['shared_forum'] ?></small> -->
         <?php } ?>
         <?php if (!empty($wo['story']['thread_id'])  && empty($wo['story']['shared_from']) && !empty($wo['story']['thread'])) {  ?>
         <!-- <small class="small-text"><?php echo $wo['lang']['shared_thread'] ?></small> -->
         <?php } ?>
         <?php if (empty($wo['story']['shared_from'])): ?>
         <small class="small-text">
         <?php 
            if($wo['story']['postType'] == 'profile_picture') { 
               $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_male'];
               if ($wo['story']['publisher']['gender'] == 'female') {
                  $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_female'];
               } else {
                  $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_male'];
               }
               echo $changed_profile_pic_lang;
            } 
            if($wo['story']['postType'] == 'profile_cover_picture') { 
               $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_male'];
               if ($wo['story']['publisher']['gender'] == 'female') {
                  $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_female'];
               } else {
                  $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_male'];
               }
               echo $changed_profile_cover_pic_lang;
            } 
            ?>
         </small>
         <?php endif; ?>
         <?php if($wo['story']['via_type'] == 'share') {  ?>
         <small style="color:#a33e40;"><?php echo $wo['story']['via']['name'];?> <?php echo $wo['lang']['shared_this_post'];?></small>
         <?php }  ?>
         <?php 
            $extra_exists = 0;
            if (!empty($wo['story']['postFeeling'])) {
               if (empty($changed_profile_pic_lang) 
                  && $wo['story']['via_type'] != 'share'
                  && $wo['story']['group_recipient_exists'] != true
                  && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"> <?php echo $wo['lang']['is_feeling'];?> <i class="twa-lg twa twa-<?php echo $wo['story']['postFeelingIcon'];?>"></i> <?php echo $wo['lang'][$wo['story']['postFeeling']];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postTraveling'])) {
               if (empty($changed_profile_pic_lang) 
                  && $wo['story']['via_type'] != 'share'
                  && $wo['story']['group_recipient_exists'] != true
                  && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-plane"></i> <?php echo $wo['lang']['is_traveling'];?> <?php echo $wo['story']['postTraveling'];?></span>
         <?php
            } else {
               $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postListening'])) {
               if (empty($changed_profile_pic_lang) 
                  && $wo['story']['via_type'] != 'share'
                  && $wo['story']['group_recipient_exists'] != true
                  && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-headphones"></i> <?php echo $wo['lang']['is_listening'];?> <?php echo $wo['story']['postListening'];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postPlaying'])) {
               if (empty($changed_profile_pic_lang) 
                  && $wo['story']['via_type'] != 'share'
                  && $wo['story']['group_recipient_exists'] != true
                  && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-gamepad"></i> <?php echo $wo['lang']['is_playing'];?> <?php echo $wo['story']['postPlaying'];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postWatching'])) {
               if (empty($changed_profile_pic_lang) 
                  && $wo['story']['via_type'] != 'share'
                  && $wo['story']['group_recipient_exists'] != true
                  && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-eye"></i> <?php echo $wo['lang']['is_watching'];?> <?php echo $wo['story']['postWatching'];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            ?>
      </div>
      <h6>
         <?php if (strlen($wo['story']['postText']) >= 2): ?>
         <span onclick="Wo_Translate($(this).attr('id'),$(this).attr('data-language'))" title="<?php echo $wo['lang']['translate'];?>" class="pointer time" id="<?php echo $wo['story']['id']; ?>" data-language="<?php echo DetermineUserLang(); ?>" data-trans-btn="<?php echo $wo['story']['id']; ?>"><?php echo $wo['lang']['translate'];?></span>
         <?php endif ?>
         <?php  if ($wo['story']['admin'] === true && $wo['story']['group_recipient_exists'] == false && empty($wo['story']['product_id'])) { ?>
         <?php  if (empty($wo['story']['page_id'])) { ?>
         <div class="dropdown wo_post_privacy_menu" style="color:#9197a3;display: inline-block;">
            <span class="dropdown-toggle pointer" data-toggle="dropdown" role="button" aria-expanded="false">
               <span class="pointer post-privacy" style="color:#9197a3">
                  <?php  if($wo['story']['postPrivacy'] == 0) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['everyone'];?>">
                     <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                  </svg>
                  <?php  } ?>
                  <?php  if($wo['story']['postPrivacy'] == 1) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo ($wo['config']['connectivitySystem'] == 1) ? $wo['lang']['my_friends'] : $wo['lang']['people_i_follow'];?>">
                     <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
                  </svg>
                  <?php  }  ?>
                  <?php  if($wo['story']['postPrivacy'] == 2) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo ($wo['config']['connectivitySystem'] == 1) ? $wo['lang']['my_friends'] : $wo['lang']['people_follow_me'];?>">
                     <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                  </svg>
                  <?php  }  ?>
                  <?php  if($wo['story']['postPrivacy'] == 3) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['only_me'];?>">
                     <path fill="currentColor" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"></path>
                  </svg>
                  <?php  }  ?>
               </span>
               <span class="caret" style="color:#9197a3"></span>
            </span>
            <ul class="dropdown-menu post-privacy-menu post-privacy-options" role="menu">
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,3,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"></path>
                     </svg>
                     <?php echo $wo['lang']['only_me'];?>
                  </div>
               </li>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,0,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                     </svg>
                     <?php echo $wo['lang']['everyone'];?>
                  </div>
               </li>
               <?php if ($wo['config']['connectivitySystem'] == 1) { ?>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,1,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
                     </svg>
                     <?php echo $wo['lang']['my_friends'];?>
                  </div>
               </li>
               <?php } else { ?>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,2,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                     </svg>
                     <?php echo $wo['lang']['people_i_follow'];?>
                  </div>
               </li>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,1,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
                     </svg>
                     <?php echo $wo['lang']['people_follow_me'];?>
                  </div>
               </li>
               <?php } ?>
            </ul>
         </div>
         <?php } else { ?>
         <div class="dropdown wo_post_privacy_menu" style="display: inline-block;">
            <span class="dropdown-toggle pointer" data-toggle="dropdown" role="button" aria-expanded="false">
               <span class="pointer post-privacy" style="color:#9197a3">
                  <?php  if($wo['story']['postPrivacy'] == 0) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['everyone'];?>">
                     <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                  </svg>
                  <?php  } ?>
                  <?php  if($wo['story']['postPrivacy'] == 2) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="Liked My Page">
                     <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                  </svg>
                  <?php  }  ?>
               </span>
               <span class="caret"></span>
            </span>
            <ul class="dropdown-menu post-privacy-menu post-privacy-options" role="menu">
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,0,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                     </svg>
                     <?php echo $wo['lang']['everyone'];?>
                  </div>
               </li>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,2,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                     </svg>
                     Liked My Page
                  </div>
               </li>
            </ul>
         </div>
         <?php } ?>
         <?php }  ?>
         <?php if(!empty($wo['story']['postMap'])) { ?>
         <?php if(!empty($wo['story']['postSoundCloud']) || !empty($wo['story']['postVine']) || !empty($wo['story']['postYoutube']) || !empty($wo['story']['postPlaytube']) || !empty($wo['story']['postVimeo']) || !empty($wo['story']['postText']) || !empty($wo['story']['postFile']) || !empty($wo['story']['postLink']) || !empty($wo['story']['postFacebook']) || !empty($wo['story']['postDailymotion']) || !empty($wo['story']['album_name']) || ($wo['config']['google_map'] == 0 && $wo['config']['yandex_map'] == 0)) { ?>
         <span style="color:#9197a3"> - <i class="fa fa-map-marker"></i> <?php echo $wo['story']['postMap'];?>.</span>
         <?php } ?>
         <?php } else { ?>
         <?php
            $small_icon = '';
            $icon_type = '';
            if(!empty($wo['story']['postVine'])) { 
               $small_icon = 'vine';
               $icon_type = 'Vine';
            } else if (!empty($wo['story']['postVimeo'])) {
               $small_icon = 'vimeo';
               $icon_type = 'Vimeo';
            } else if (!empty($wo['story']['postFacebook'])) {
               $small_icon = 'facebook-official';
               $icon_type = 'Facebook';
            } else if (!empty($wo['story']['postDailymotion'])) {
               $small_icon = 'film';
               $icon_type = 'Dailymotion';
            } else if (!empty($wo['story']['postYoutube'])) {
               $small_icon = 'youtube-square';
               $icon_type = 'Youtube';
            } else if (!empty($wo['story']['postPlaytube'])) {
               // $small_icon = 'play-circle';
               // $icon_type = 'PlayTube';
            } else if (!empty($wo['story']['postSoundCloud'])) {
               $small_icon = 'soundcloud';
               $icon_type = 'SoundCloud';
            }
            if (!empty($icon_type)) {
            ?>
         <span style="color:#9197a3; text-transform: capitalize;">- <i class="fa fa-<?php echo $small_icon; ?>"></i> <?php echo $icon_type; ?></span>
         <?php  } } ?>
         <span class="time">
         &nbsp;&nbsp;<a  style="color:#9197a3" class="ajax-time" href="<?php echo $wo['story']['url'];?>" title="<?php echo date('c',$wo['story']['time']); ?>" target="_blank"><?php echo Wo_Time_Elapsed_String($wo['story']['time']); ?></a>
         </span>
      </h6>
   </div>
</div>
<?php 
}elseif (empty($wo['story']['parent_id'])) { 
   if ($wo['config']['shout_box_system'] == 1 && $wo['story']['postPrivacy'] == 4) {
      $anonymous = true;
      $wo['story']['publisher']['username'] = 'anonymous';
      $wo['story']['publisher']['name'] = $wo['lang']['anonymous'];
      $wo['story']['publisher']['avatar'] = Wo_GetMedia('upload/photos/incognito.png');
      $wo['story']['publisher']['verified'] = 0;
      $wo['story']['publisher']['type'] = '';
	  $wo['story']['publisher']['url'] = 'javascript:void(0)';
   }
   ?>

<div class="post-heading">
   <div class="<?php echo Wo_RightToLeft('pull-left');?> image">
      <?php if (!isset($anonymous)) { ?>
      <a href="<?php echo $wo['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['publisher']['username']?>">
      <img src="<?php echo $wo['story']['publisher']['avatar']; ?>" id="updateImage-<?php echo $wo['story']['publisher']['user_id']?>" class="avatar" alt="<?php echo $wo['story']['publisher']['name']; ?> profile picture">
      </a>
   <?php }else{ ?>
      <img src="<?php echo $wo['story']['publisher']['avatar']; ?>" id="updateImage-<?php echo $wo['story']['publisher']['user_id']?>" class="avatar" alt="<?php echo $wo['story']['publisher']['name']; ?> profile picture">
   <?php } ?>
   </div>
   <div class="<?php echo Wo_RightToLeft('pull-right');?>">
      <?php  if ($wo['story']['admin'] === true || $wo['story']['group_admin'] === true) { ?>
      <span class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down">
               <polyline points="6 9 12 15 18 9"></polyline>
            </svg>
         </a>
         <ul class="dropdown-menu post-privacy-menu post-options" role="menu">
            <?php if (!empty($wo['story']['offer_id']) && (Wo_IsModerator() || Wo_IsAdmin() || $wo['story']['offer']['user_id'] == $wo['user']['id'])) { ?>
               <li>
                  <div class="pointer" onclick="Wo_OpenOfferEditBox(<?php echo $wo['story']['offer_id']; ?>);"><?php echo $wo['lang']['edit_offer'];?></div>
               </li>
            <?php } ?>
            <?php if ($wo['story']['admin'] === true && empty($wo['story']['product_id']) && empty($wo['story']['shared_from'])) { ?>
            <li>
               <div class="pointer" onclick="Wo_OpenPostEditBox(<?php echo $wo['story']['id']; ?>);"><?php echo $wo['lang']['edit_post'];?></div>
            </li>
            <?php } else if (!empty($wo['story']['product_id']) && empty($wo['story']['parent_id'])) { 
               if ($wo['story']['product']['status'] == 0) { ?>
            <li>
               <div class="pointer mark-as-sold-post" onclick="Wo_MarkAsSold(<?php echo $wo['story']['id']; ?>, <?php echo $wo['story']['product_id']; ?>);"><?php echo $wo['lang']['mark_as_sold']?></div>
            </li>
            <li>
               <a class="pointer" href="<?php echo Wo_SeoLink('index.php?link1=edit-product&id=' . $wo['story']['product_id']);?>"><?php echo $wo['lang']['edit_product']?></a>
            </li>
            <?php } } ?>
            <li>
               <div class="pointer" onclick="Wo_OpenPostDeleteBox(<?php echo $wo['story']['id']; ?>);"><?php echo $wo['lang']['delete_post'];?></div>
            </li>
            <li>
               <div class="pointer disable-comments" onclick="Wo_DisableComment(<?php echo $wo['story']['id']; ?>, <?php echo $wo['story']['comments_status']; ?>);"><?php echo ($wo['story']['comments_status'] == 1) ? $wo['lang']['disable_comments'] : $wo['lang']['enable_comments'];?></div>
            </li>
            <li>
               <hr>
            </li>
            <li>
               <a href="<?php echo $wo['story']['url'];?>" target="_blank"><?php echo $wo['lang']['open_post_in_new_tab'];?></a>
            </li>
            <li>
               <hr>
            </li>
            <?php if (empty($wo['story']['recipient']) && $wo['story']['admin'] === true) { ?>
            <?php if ($wo['story']['is_group_post'] == false) { ?>
            <li>
               <?php
                  $pin_post_id = $wo['story']['publisher']['id'];
                  $pin_post_text = 'profile';
                  if (!empty($wo['story']['page_id'])) {
                    $pin_post_id = $wo['story']['page_id'];
                    $pin_post_text = 'page';
                  } else if (!empty($wo['story']['group_id'])) {
                    $pin_post_id = $wo['story']['group_id'];
                    $pin_post_text = 'group';
                  }  else if (!empty($wo['story']['event_id'])) {
                    $pin_post_id = $wo['story']['event_id'];
                    $pin_post_text = 'event';
                  }
                  ?>
               <div class="pin-post pointer" onclick="Wo_PinPost(<?php echo $wo['story']['id']; ?>, <?php echo $pin_post_id;?>, '<?php echo $pin_post_text; ?>');">
                  <?php if($wo['story']['is_post_pinned'] === true) { ?>
                  <?php echo $wo['lang']['unpin_post'];?>
                  <?php } else { ?>
                  <?php echo $wo['lang']['pin_post'];?>
                  <?php } ?>
               </div>
            </li>
            <?php } } ?>
            <?php if (!empty($wo['story']['album_name']) && ($wo['story']['group_admin'] === false || $wo['story']['admin'] === true)) {?>
            <li>
               <a href="<?php echo Wo_SeoLink('index.php?link1=create-album&album=' . $wo['story']['id']);?>"><?php echo $wo['lang']['add_photos'];?></a>
            </li>
            <?php } ?>
            <?php $hr = 0; if ($wo['config']['pro'] == 1 && ($wo['story']['group_admin'] === false || $wo['story']['admin'] === true)) { ?>
            <li>
               <?php if ($wo['user']['is_pro'] == 0) {  ?>
               <a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>" data-ajax="?link1=go-pro"><?php echo $wo['lang']['boost_post']; ?></a>
               <?php } else if ($wo['user']['is_pro'] == 1 && in_array($wo['user']['pro_type'], array_keys($wo['pro_packages'])) && $wo['pro_packages'][$wo['user']['pro_type']]['posts_promotion'] > 0) {?>
               <?php if ($wo['story']['is_post_boosted'] == 0) { ?>
               <div class="boost-post pointer" onclick="Wo_BoostPost(<?php echo $wo['story']['id']; ?>)"><?php echo $wo['lang']['boost_post']; ?></div>
               <?php } else { ?>
               <div class="boost-post pointer" onclick="Wo_BoostPost(<?php echo $wo['story']['id']; ?>)"><?php echo $wo['lang']['unboost_post']; ?></div>
               <?php } ?>
               <?php } else if ($wo['user']['is_pro'] == 1 && $wo['user']['pro_type'] == 1) { $hr = 1; ?>
               <?php } ?>
            </li>
            <?php if ($hr == 0) { ?>
            <?php } } ?>
         </ul>
      </span>
      <?php  } elseif ($wo['loggedin'] == true) { ?>
      <span class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="pointer">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down">
                  <polyline points="6 9 12 15 18 9"></polyline>
               </svg>
            </span>
         </a>
         <ul class="dropdown-menu post-privacy-menu post-options post-recipient" role="menu"  >
            <?php if (Wo_IsAdmin()): ?>
            <li>
               <div class="pointer" onclick="Wo_OpenPostDeleteBox(<?php echo $wo['story']['id']; ?>);"><?php echo $wo['lang']['delete_post'];?></div>
            </li>
            <?php endif; ?>
            <li>
               <div class="save-post pointer" class="save-post" onclick="Wo_SavePost(<?php echo $wo['story']['id']; ?>);">
                  <?php if($wo['story']['is_post_saved'] === true) { ?>
                  <?php echo $wo['lang']['unsave_post'];?>
                  <?php } else { ?>
                  <?php echo $wo['lang']['save_post'];?>
                  <?php } ?>
               </div>
            </li>
            <li>
               <div  class="report-post pointer" onclick="Wo_ReportPost(<?php echo $wo['story']['id']; ?>);">
                  <?php if($wo['story']['is_post_reported'] === true) { ?>
                  <?php echo $wo['lang']['unreport_post'];?>
                  <?php } else { ?>
                  <?php echo $wo['lang']['report_post'];?>
                  <?php } ?>
               </div>
            </li>
            <li>
               <a href="<?php echo $wo['story']['url'];?>" target="_blank"><?php echo $wo['lang']['open_post_in_new_tab'];?></a>
            </li>
            <li>
               <a class="pointer" onclick="Wo_HidePost(<?php echo $wo['story']['id'];?>);"><?php echo $wo['lang']['hide_post'];?></a>    
            </li>
         </ul>
      </span>
      <?php } ?>
   </div>
   <div class="meta">
      <div class="title h5">
         <?php if (!isset($anonymous)) { ?>  
         <span class="user-popover" data-type="<?php echo $wo['story']['publisher']['type']; ?>" data-id="<?php echo $wo['story']['publisher']['id']; ?>">
         <a href="<?php echo $wo['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['publisher']['username']; ?>"><b><?php echo $wo['story']['publisher']['name']; ?></b></a>
         </span>
         <?php }else{ ?>
            <b><?php echo $wo['story']['publisher']['name']; ?></b>
         <?php } ?>
         <?php if($wo['story']['publisher']['verified'] == 1) { ?>
         <span class="verified-color">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>">
               <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
            </svg>
         </span>
         <?php } ?>
		 
		 <?php if (!empty($wo['story']['publisher']['is_open_to_work']) && $wo['config']['website_mode'] == 'linkedin') { ?>
			<span class="wo_open_job_badge" title="<?php echo($wo['lang']['open_to_work']); ?>" data-toggle="tooltip"><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg></span>
		<?php } ?>
		 
         <?php 
         if ($wo['config']['shout_box_system'] != 1 || $wo['story']['postPrivacy'] != 4) {
         if (isset($wo['story']['publisher']['is_pro'])) { 
            if(Wo_IsUserPro($wo['story']['publisher']['is_pro']) === true) { ?>
         <?php 
            $user_pro_type = Wo_GetUserProType($wo['story']['publisher']['pro_type']);
            ?>
         <span style="color:<?php echo $user_pro_type['color_name'];?>">
         <?php 
            if (!empty(in_array($wo['story']['publisher']['pro_type'], array_keys($wo['pro_packages'])) && !empty($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['image'])) && $_COOKIE['mode'] == 'day') { ?>
         <img src="<?php echo($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['image']) ?>" class="pro_packages_icon_inline">
         <?php }
         elseif (!empty(in_array($wo['story']['publisher']['pro_type'], array_keys($wo['pro_packages'])) && !empty($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['night_image'])) && $_COOKIE['mode'] == 'night') { ?>
            <img src="<?php echo($wo['pro_packages'][$wo['story']['publisher']['pro_type']]['night_image']) ?>" class="pro_packages_icon_inline">
         <?php }
         else{ ?>
         <i class="fa fa-<?php echo $user_pro_type['icon'];?> fa-fw" title="<?php echo $user_pro_type['type_name'];?>" data-toggle="tooltip"></i>
         <?php } ?>
         </span>
         <?php } } 
         }
         ?>
         <?php if ($wo['story']['shared_from'] && is_array($wo['story']['shared_from'])): ?>
         <span class="user-popover" data-type="<?php echo $wo['story']['shared_from']['type']; ?>" data-id="<?php echo $wo['story']['shared_from']['id']; ?>">
            <span><?php echo $wo['lang']['shared']; ?></span> 
            <a href="<?php echo $wo['story']['shared_from']['url']; ?>" class="pointer no_decor" data-ajax="?link1=timeline&u=<?php echo $wo['story']['shared_from']['username']; ?>"><b><?php echo $wo['story']['shared_from']['name']; ?></b></a>
            <?php if($wo['story']['shared_from']['verified'] == 1) { ?>
            <span class="verified-color">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip">
                  <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
               </svg>
            </span>
            <?php } ?>
         </span>
         <?php if ($wo['story']['shared_from'] && is_array($wo['story']['shared_from'])): ?>
         <span>  
         <a href="<?php echo $wo['story']['post_url']; ?>" class="pointer"><span style="color: #666;"><?php echo strtolower($wo['lang']['post']); ?></span></a>
         </span>
         <?php endif; ?>
         <?php endif; ?>
         <?php if ($wo['config']['live_video'] == 1 && !empty($wo['story']['stream_name'])) { ?>
         <span><span style="color: #666;" class="was_live_text_<?php echo($wo['story']['id']) ?>"><?php echo ($wo['story']['is_still_live'] ? $wo['lang']['is_live'] : $wo['lang']['was_live']); ?></span></span>
      <?php } ?>
         <?php if ($wo['story']['recipient_exists'] == true) {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <span class="user-popover" data-type="<?php echo $wo['story']['recipient']['type']; ?>" data-id='<?php echo $wo['story']['recipient']['id']; ?>'>
            <a href="<?php echo $wo['story']['recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['recipient']['username']; ?>">
            <b><?php echo $wo['story']['recipient']['name']; ?></b>
            </a>
            <?php if($wo['story']['recipient']['verified'] == 1) { ?>
            <span class="verified-color">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip">
                  <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" />
               </svg>
            </span>
            <?php } ?>
         </span>
         <?php } ?>
         <?php if (!empty($wo['story']['page_event_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['created_new_event'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['fund_id']) && empty($wo['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['created_donation_request'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['fund_raise_id']) && empty($wo['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['donated_to_request'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['offer_id']) && empty($wo['story']['parent_id'])) {?>
         <small class="small-text"> <?php echo $wo['lang']['created_offer'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['event_id']) && $wo['page'] != 'events') {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <a href="<?php echo $wo['story']['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo $wo['story']['event']['id']; ?>"><b><?php echo $wo['story']['event']['name']; ?></b></a>
         <?php } ?>
         <?php if ($wo['story']['group_recipient_exists'] == true && $wo['page'] != 'group') {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <span class="user-popover" data-type="<?php echo $wo['story']['group_recipient']['type']; ?>" data-id='<?php echo $wo['story']['group_recipient']['id']; ?>'>
         <a href="<?php echo $wo['story']['group_recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['group_recipient']['username']; ?>">
         <b><?php echo $wo['story']['group_recipient']['name']; ?></b>
         </a>
         </span>
         <?php } ?>

         <?php if (!empty($wo['story']['page_info']) && $wo['page'] != 'page') {  ?>
         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentColor" d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
         </svg>
         <span class="user-popover" data-type="<?php echo $wo['story']['page_info']['type']; ?>" data-id='<?php echo $wo['story']['page_info']['id']; ?>'>
         <a href="<?php echo $wo['story']['page_info']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['page_info']['username']; ?>">
         <b><?php echo $wo['story']['page_info']['name']; ?></b>
         </a>
         </span>
         <?php } ?>
         <?php if (!empty($wo['story']['album_name']) && empty($wo['story']['shared_from'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['added_new_photos_to'];?> <b><a href="<?php echo $wo['story']['url']; ?>" data-ajax="?link1=post&id=<?php echo $wo['story']['id'];?>"><?php echo $wo['story']['album_name']; ?></a></b></small>
         <?php } ?>
         <?php if (!empty($wo['story']['product_id']) && empty($wo['story']['shared_from'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['added_new_product_for_sell']; ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['blog_id'])  && empty($wo['story']['shared_from'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['created_new_blog'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['forum_id'])  && empty($wo['story']['shared_from']) && !empty($wo['story']['forum'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['shared_forum'] ?></small>
         <?php } ?>
         <?php if (!empty($wo['story']['thread_id'])  && empty($wo['story']['shared_from']) && !empty($wo['story']['thread'])) {  ?>
         <small class="small-text"><?php echo $wo['lang']['shared_thread'] ?></small>
         <?php } ?>
         <?php if (empty($wo['story']['shared_from'])): ?>
         <small class="small-text">
         <?php 
            if($wo['story']['postType'] == 'profile_picture') { 
              $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_male'];
              if ($wo['story']['publisher']['gender'] == 'female') {
                $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_female'];
              } else {
                $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_male'];
              }
              echo $changed_profile_pic_lang;
            } 
            if($wo['story']['postType'] == 'profile_cover_picture') { 
              $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_male'];
              if ($wo['story']['publisher']['gender'] == 'female') {
                $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_female'];
              } else {
                $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_male'];
              }
              echo $changed_profile_cover_pic_lang;
            } 
            ?>
         </small>
         <?php endif; ?>
         <?php if($wo['story']['via_type'] == 'share') {  ?>
         <small style="color:#a33e40;"><?php echo $wo['story']['via']['name'];?> <?php echo $wo['lang']['shared_this_post'];?></small>
         <?php }  ?>
         <?php 
            $extra_exists = 0;
            if (!empty($wo['story']['postFeeling'])) {
              if (empty($changed_profile_pic_lang) 
                && $wo['story']['via_type'] != 'share'
                && $wo['story']['group_recipient_exists'] != true
                && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"> <?php echo $wo['lang']['is_feeling'];?> <i class="twa-lg twa twa-<?php echo $wo['story']['postFeelingIcon'];?>"></i> <?php echo $wo['lang'][$wo['story']['postFeeling']];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postTraveling'])) {
              if (empty($changed_profile_pic_lang) 
                && $wo['story']['via_type'] != 'share'
                && $wo['story']['group_recipient_exists'] != true
                && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-plane"></i> <?php echo $wo['lang']['is_traveling'];?> <?php echo $wo['story']['postTraveling'];?></span>
         <?php
            } else {
              $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postListening'])) {
              if (empty($changed_profile_pic_lang) 
                && $wo['story']['via_type'] != 'share'
                && $wo['story']['group_recipient_exists'] != true
                && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-headphones"></i> <?php echo $wo['lang']['is_listening'];?> <?php echo $wo['story']['postListening'];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postPlaying'])) {
              if (empty($changed_profile_pic_lang) 
                && $wo['story']['via_type'] != 'share'
                && $wo['story']['group_recipient_exists'] != true
                && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-gamepad"></i> <?php echo $wo['lang']['is_playing'];?> <?php echo $wo['story']['postPlaying'];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            if (!empty($wo['story']['postWatching'])) {
              if (empty($changed_profile_pic_lang) 
                && $wo['story']['via_type'] != 'share'
                && $wo['story']['group_recipient_exists'] != true
                && empty($wo['story']['album_name'])) {
            ?>
         <span class="feeling-text"><i class="fa fa-eye"></i> <?php echo $wo['lang']['is_watching'];?> <?php echo $wo['story']['postWatching'];?></span>
         <?php
            } else {
            $extra_exists = 1;
            }
            }
            ?>
      </div>
      <h6>
         <?php if (strlen($wo['story']['postText']) >= 2): ?>
         <span onclick="Wo_Translate($(this).attr('id'),$(this).attr('data-language'))" title="<?php echo $wo['lang']['translate'];?>" class="pointer time" id="<?php echo $wo['story']['id']; ?>" data-language="<?php echo DetermineUserLang(); ?>" data-trans-btn="<?php echo $wo['story']['id']; ?>"><?php echo $wo['lang']['translate'];?></span>
         <?php endif ?>
         <?php  if ($wo['story']['admin'] === true && $wo['story']['group_recipient_exists'] == false && empty($wo['story']['product_id'])) { ?>
         <?php  if (empty($wo['story']['page_id'])) { ?>
         <div class="dropdown wo_post_privacy_menu" style="color:#9197a3;display: inline-block;">
            <span class="dropdown-toggle pointer" data-toggle="dropdown" role="button" aria-expanded="false">
               <span class="pointer post-privacy" style="color:#9197a3">
                  <?php  if($wo['story']['postPrivacy'] == 0) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['everyone'];?>">
                     <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                  </svg>
                  <?php  } ?>
                  <?php  if($wo['story']['postPrivacy'] == 1) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo ($wo['config']['connectivitySystem'] == 1) ? $wo['lang']['my_friends'] : $wo['lang']['people_i_follow'];?>">
                     <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
                  </svg>
                  <?php  }  ?>
                  <?php  if($wo['story']['postPrivacy'] == 2) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo ($wo['config']['connectivitySystem'] == 1) ? $wo['lang']['my_friends'] : $wo['lang']['people_follow_me'];?>">
                     <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                  </svg>
                  <?php  }  ?>
                  <?php  if($wo['story']['postPrivacy'] == 3) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['only_me'];?>">
                     <path fill="currentColor" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"></path>
                  </svg>
                  <?php  }  ?>
                  <?php  if($wo['story']['postPrivacy'] == 5 && $wo['config']['website_mode'] == 'linkedin') { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" title="<?php echo $wo['lang']['hiring'];?>" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
                  <?php  }  ?>
               </span>
               <span class="caret" style="color:#9197a3"></span>
            </span>
            <ul class="dropdown-menu post-privacy-menu post-privacy-options" role="menu">
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,3,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"></path>
                     </svg>
                     <?php echo $wo['lang']['only_me'];?>
                  </div>
               </li>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,0,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                     </svg>
                     <?php echo $wo['lang']['everyone'];?>
                  </div>
               </li>
               <?php if ($wo['config']['connectivitySystem'] == 1) { ?>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,1,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
                     </svg>
                     <?php echo $wo['lang']['my_friends'];?>
                  </div>
               </li>
               <?php } else { ?>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,2,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                     </svg>
                     <?php echo $wo['lang']['people_i_follow'];?>
                  </div>
               </li>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,1,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path>
                     </svg>
                     <?php echo $wo['lang']['people_follow_me'];?>
                  </div>
               </li>
               <?php } ?>
               <?php if($wo['config']['website_mode'] == 'linkedin') { ?>
                  <li>
                     <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,5,event);">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
                        <?php echo $wo['lang']['hiring'];?>
                     </div>
                  </li>
               <?php } ?>
            </ul>
         </div>
         <?php } else { ?>
         <div class="dropdown wo_post_privacy_menu" style="display: inline-block;">
            <span class="dropdown-toggle pointer" data-toggle="dropdown" role="button" aria-expanded="false">
               <span class="pointer post-privacy" style="color:#9197a3">
                  <?php  if($wo['story']['postPrivacy'] == 0) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['everyone'];?>">
                     <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                  </svg>
                  <?php  } ?>
                  <?php  if($wo['story']['postPrivacy'] == 2) { ?>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="Liked My Page">
                     <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                  </svg>
                  <?php  }  ?>
               </span>
               <span class="caret"></span>
            </span>
            <ul class="dropdown-menu post-privacy-menu post-privacy-options" role="menu">
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,0,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path>
                     </svg>
                     <?php echo $wo['lang']['everyone'];?>
                  </div>
               </li>
               <li>
                  <div class="pointer" onclick="Wo_UpdatePostPrivacy(<?php echo $wo['story']['id']; ?>,2,event);">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z"></path>
                     </svg>
                     Liked My Page
                  </div>
               </li>
            </ul>
         </div>
         <?php } ?>
         <?php }  ?>
         <?php if(!empty($wo['story']['postMap'])) { ?>
         <?php if(!empty($wo['story']['postSoundCloud']) || !empty($wo['story']['postVine']) || !empty($wo['story']['postYoutube']) || !empty($wo['story']['postPlaytube']) || !empty($wo['story']['postVimeo']) || !empty($wo['story']['postText']) || !empty($wo['story']['postFile']) || !empty($wo['story']['postLink']) || !empty($wo['story']['postFacebook']) || !empty($wo['story']['postDailymotion']) || !empty($wo['story']['album_name']) || ($wo['config']['google_map'] == 0 && $wo['config']['yandex_map'] == 0)) { ?>
         <span style="color:#9197a3"> - <i class="fa fa-map-marker"></i> <?php echo $wo['story']['postMap'];?>.</span>
         <?php } ?>
         <?php } else { ?>
         <?php
            $small_icon = '';
            $icon_type = '';
            if(!empty($wo['story']['postVine'])) { 
              $small_icon = 'vine';
              $icon_type = 'Vine';
            } else if (!empty($wo['story']['postVimeo'])) {
              $small_icon = 'vimeo';
              $icon_type = 'Vimeo';
            } else if (!empty($wo['story']['postFacebook'])) {
              $small_icon = 'facebook-official';
              $icon_type = 'Facebook';
            } else if (!empty($wo['story']['postDailymotion'])) {
              $small_icon = 'film';
              $icon_type = 'Dailymotion';
            } else if (!empty($wo['story']['postYoutube'])) {
              $small_icon = 'youtube-square';
              $icon_type = 'Youtube';
            } else if (!empty($wo['story']['postPlaytube'])) {
              // $small_icon = 'play-circle';
              // $icon_type = 'PlayTube';
            } else if (!empty($wo['story']['postSoundCloud'])) {
              $small_icon = 'soundcloud';
              $icon_type = 'SoundCloud';
            }
            if (!empty($icon_type)) {
            ?>
         <span style="color:#9197a3; text-transform: capitalize;">- <i class="fa fa-<?php echo $small_icon; ?>"></i> <?php echo $icon_type; ?></span>
         <?php  } } ?>
         <span class="time">
         &nbsp;&nbsp;<a  style="color:#9197a3" class="ajax-time" href="<?php echo $wo['story']['url'];?>" title="<?php echo date('c',$wo['story']['time']); ?>" target="_blank"><?php echo Wo_Time_Elapsed_String($wo['story']['time']); ?></a>
         </span>
      </h6>
   </div>
</div>
<?php } ?>