<div class="page_list flex_pages boosted_pages">
	<div class="info">
		<a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
			<div class="avatar">
				<img src="<?php echo $wo['page']['avatar'];?>" alt="<?php echo $wo['page']['page_name']; ?> Profile Picture" />
			</div>
		</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<div>
			<a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
				<span class="page_title"><?php echo $wo['page']['page_title']; ?></span>
			</a>
			<div class="page_info">
				<ul>
					<li>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg> <?php echo Wo_CountPageLikes($wo['page']['page_id']);?> <?php echo $wo['lang']['people_likes_this']; ?>
					</li>
					<li>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z" /></svg> <?php echo $wo['page']['category']?>
					</li>
					<?php if (!empty($wo['page']['page_sub_category'])) { ?>
					<li>
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z" /></svg> <?php echo $wo['page']['page_sub_category']; ?>
					</li>
					<?php } ?>
				</ul>
			</div>
		</div>
	</div>
	<div class="btns">
		<div class="text-right">
			<?php if( isset( $wo['page']['Wo_PageSug'] ) ){ ?>
				<?php echo Wo_GetLikeButton($wo['page']['page_id']);?>
			<?php }else{ ?>
		    	<a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' .  $wo['page']['page_name']); ?>" data-ajax="?link1=page-setting&page=<?php echo $wo['page']['page_name'];?>" class="btn btn-info btn-sm btn-mat btn-mat-raised" title="<?php echo $wo['lang']['edit']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8,12H16V14H8V12M10,20H6V4H13V9H18V12.1L20,10.1V8L14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H10V20M8,18H12.1L13,17.1V16H8V18M20.2,13C20.3,13 20.5,13.1 20.6,13.2L21.9,14.5C22.1,14.7 22.1,15.1 21.9,15.3L20.9,16.3L18.8,14.2L19.8,13.2C19.9,13.1 20,13 20.2,13M20.2,16.9L14.1,23H12V20.9L18.1,14.8L20.2,16.9Z" /></svg>
				</a>
			<?php } ?>
		</div>
	</div>
</div>