<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists singlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></path></svg></span> <?php echo $wo['lang']['pages']; ?>
					</div>
				</div>
			</div>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_menu">
						<ul class="list-unstyled">
							<?php if ($wo['config']['can_use_pages']) { ?>
							<li><a href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages"><?php echo $wo['lang']['my_pages'] ?></a></li>
							<?php } ?>
							<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=suggested-pages'); ?>" data-ajax="?link1=suggested-pages"><?php echo $wo['lang']['suggested_pages'] ?></a></li>
							<li><a href="<?php echo Wo_SeoLink('index.php?link1=liked-pages'); ?>" data-ajax="?link1=liked-pages"><?php echo $wo['lang']['liked_pages'] ?></a></li>
						</ul>
						<?php if ($wo['config']['can_use_pages']) { ?>
						<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-page');?>" data-ajax="?link1=create-page"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <?php echo $wo['lang']['create'] ?></a>
						<?php } ?>
					</div>
				</div>
			</div>
			<div class="wo_my_pages">
				<div>
					<?php
						$pages = Wo_PageSug(50);
						if (count($pages) > 0) {
							foreach ($pages as $wo['page']) {
								$wo['page']['Wo_PageSug'] = true;
								echo Wo_LoadPage('page/pages-list');
							}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"></path></svg>' . $wo['lang']['no_pages_found'] . '</div>';
						}
					?>
				<div class="clear"></div>
				</div>
			</div>
		</div>
		<?php // echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>