<div class="welcome-footer">
	<?php 
		$copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
		echo $copy = str_replace('{date}', date('Y'), $copy);
	?> &nbsp;•&nbsp;
	<a data-ajax="?link1=terms&type=terms" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>"><?php echo $wo['lang']['terms_of_use'];?></a> &nbsp;•&nbsp;
	<a data-ajax="?link1=terms&type=privacy-policy" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>"><?php echo $wo['lang']['privacy_policy'];?></a> &nbsp;•&nbsp;
	<a data-ajax="?link1=contact-us" href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>"><?php echo $wo['lang']['contact_us'];?></a> &nbsp;•&nbsp;
	<a data-ajax="?link1=terms&type=about-us" href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>"><?php echo $wo['lang']['about'];?></a> &nbsp;•&nbsp;
	<?php  if ($wo['config']['blogs'] == 1) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=blogs');?>"><?php echo $wo['lang']['blog'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php  if ($wo['config']['forum'] == 1 && $wo['config']['forum_visibility'] == 0) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=forum');?>" data-ajax="?link1=forum"><?php echo $wo['lang']['forum'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php  if ($wo['config']['events'] == 1 && $wo['config']['events_visibility'] == 0) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=events');?>" data-ajax="?link1=events"><?php echo $wo['lang']['events'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php  if ($wo['config']['classified'] == 1 && $wo['config']['product_visibility'] == 0) { ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=products');?>" data-ajax="?link1=products"><?php echo $wo['lang']['market'];?></a> &nbsp;•&nbsp;
	<?php } ?>
	<?php
		$pages = Wo_GetCustomPages();
		if (count($pages) > 0) {
		foreach ($pages as $key => $page) {
	?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a> &nbsp;•&nbsp;
	<?php } } ?>
	<span class="lang dropup">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><svg fill="currentColor" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg" class="feather feather-translate" style="margin-top: -3px;width: 15px;height: 15px;vertical-align: middle;"><path d="M12.87,15.07L10.33,12.56L10.36,12.53C12.1,10.59 13.34,8.36 14.07,6H17V4H10V2H8V4H1V6H12.17C11.5,7.92 10.44,9.75 9,11.35C8.07,10.32 7.3,9.19 6.69,8H4.69C5.42,9.63 6.42,11.17 7.67,12.56L2.58,17.58L4,19L9,14L12.11,17.11L12.87,15.07M18.5,10H16.5L12,22H14L15.12,19H19.87L21,22H23L18.5,10M15.88,17L17.5,12.67L19.12,17H15.88Z" /></svg>
		<?php echo $wo['lang']['language'];?></a>
		<ul class="dropdown-menu dropdown-menu-right wow_lang_select_menu">
			<?php
				$langs = Wo_LangsNamesFromDB();
				if (count($langs) > 0) {
					foreach ($langs as $key => $wo['langs']) {
						if ($wo['config'][$wo['langs']] == 1) {
						$language = $wo['langs'];
						$languages_name = ucfirst($wo['langs']);
						$link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
			?>
				<li class="language_select"><a href="<?php echo $link;?>" rel="nofollow" class="<?php echo $languages_name;?>"><?php echo $languages_name;?></a></li>
			<?php } } } ?>
		</ul>
	</span>
</div>