<tr class="setting-postlist" id="<?php echo $wo['langs_'];?>" data_selected="<?php echo $wo['langs_'];?>">
  <td><input type="checkbox" id="check-data-<?php echo $wo['langs_'];?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['langs_'];?>"></label></td>
   <td style="text-align: center;"><?php echo $wo['langs'];?></td>
   <td style="text-align: center;">
      <a class="btn bg-success admn_table_btn" href="<?php echo Wo_LoadAdminLinkSettings('edit-lang?id=' . $wo['langs_']);?>">Edit</a>
      <a href="javscript:void(0)" class="delete-field btn bg-danger admn_table_btn" onclick="Wo_DeleteLang('<?php echo $wo['langs_'];?>','hide');">Delete</a>
      <a href="javscript:void(0)" class="delete-field btn bg-info admn_table_btn" onclick="update_lang_status(this,'<?php echo $wo['langs_'];?>')" data-type="<?php echo ($wo['config'][$wo['langs_']] == 1) ? 'disable': 'enable';?>"><?php if($wo['config'][$wo['langs_']] == 1){ ?> <?php }else{ ?> <?php } ?> <?php echo ($wo['config'][$wo['langs_']] == 1) ? 'Disable': 'Enable';?></a>


        <!-- <input type="radio" name="<?php echo $wo['langs_'];?>" id="<?php echo $wo['langs_'];?>-enabled" value="1" <?php echo ($wo['config'][$wo['langs_']] == 1) ? 'checked': '';?> onclick="update_lang_status('enabled','<?php echo $wo['langs_'];?>')">
        <label for="<?php echo $wo['langs_'];?>-enabled">Enabled</label>
        <input type="radio" name="<?php echo $wo['langs_'];?>" id="<?php echo $wo['langs_'];?>-disabled" value="0" <?php echo ($wo['config'][$wo['langs_']] == 0) ? 'checked': '';?> onclick="update_lang_status('disabled','<?php echo $wo['langs_'];?>')">
        <label for="<?php echo $wo['langs_'];?>-disabled" class="m-l-20">Disabled</label> -->
   </td>
</tr>