<div class="blog-comment-item" data-blog-comment-reply="<?php echo $wo['comm-reply']['id']; ?>">
	<div class="col-md-1 col-sm-1 col-xs-1"></div>
	<div class="col-md-1 col-sm-1 col-xs-1 <?php echo Wo_RightToLeft('pull-left');?> blog-comment-item-img">
		<img src="<?php echo $wo['comm-reply']['user_data']['avatar']; ?>" alt="" class="responsive-img img-circle">
	</div>
	<div class="col-md-10 <?php echo Wo_RightToLeft('pull-right');?> col-sm-10 col-xs-9 blog-comment-item-body">
		<h5>
			<a class="pointer bold" data-ajax="?link1=timeline&u=<?php echo $wo['comm-reply']['user_data']['username']; ?>" href="<?php echo $wo['comm-reply']['user_data']['url']; ?>">
				<?php echo $wo['comm-reply']['user_data']['name']; ?>
			</a>
			<span class="time">
				<span class="ajax-time" title="<?php echo date('c',$wo['comm-reply']['posted']); ?>">
					<?php echo Wo_Time_Elapsed_String($wo['comm-reply']['posted']); ?>
				</span>
			</span>
			<?php if ($wo['comm-reply']['is_owner']): ?>
				<span class="pointer <?php echo Wo_RightToLeft('pull-right');?> del-blog-commreplies" id="<?php echo $wo['comm-reply']['id']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
				</span>
			<?php endif ?>
		</h5>
		<p><?php echo $wo['comm-reply']['text']; ?></p>
		<div>
			<span class="comment-icons">
				<span class="pointer reply-toblogcomm-reply"  data-blog-commId="<?php echo $wo['comm-reply']['comm_id']; ?>" id="<?php echo $wo['comm-reply']['id']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
				</span>
				&nbsp;

				<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
		            <!-- reaction -->
		            <div class="like-stat stat-item" id="comment_reacted">
		              <span class="like-emo replay-reactions-icons-<?php echo $wo['comm-reply']['id']; ?>">
		              <?php echo Wo_GetPostReactions($wo['comm-reply']['id'],"reply",'blog');?>
		              </span>
		            </div>
					<div class="wo-reaction wo-reaction-replay stat-item" data-id="<?php echo $wo['comm-reply']['id']; ?>" id="comment_reactions">
		                <span class="like-btn like-btn-replay" data-id="<?php echo $wo['comm-reply']['id']; ?>">
		                    <?php
		                    if (Wo_IsReacted($wo['comm-reply']['id'], $wo['comm-reply']['user_id'],"reply",'blog') === true) {    
		                    echo '<span class="replay-status-reaction-'.$wo['comm-reply']['id'].' active-like"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <span class="r_likes-'.$wo['comm-reply']['id'].'"></span></span>';   
		                    } else {   
		                    echo '<span class="replay-status-reaction-'.$wo['comm-reply']['id'].'"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <span class="r_likes-'.$wo['comm-reply']['id'].'"></span></span>';   
		                    }    
		                    ?>
		                </span>
		                <ul class="reactions-box reactions-box-comment-replay-container-<?php echo $wo['comm-reply']['id']; ?>" data-id="<?php echo $wo['comm-reply']['id']; ?>" style="<?php if ($wo['language_type'] == 'rtl') {?> left: auto; <?php }else{ ?> right: auto; <?php }?>">

		                	<?php if (!empty($wo['reactions_types'])) {
							    foreach ($wo['reactions_types'] as $key => $value) {
							    	if ($value['status'] == 1) {
							     ?>
							    <li class="reaction reaction-<?php echo $value['id'];?> animated_2" data-reaction="<?php echo $value['name'];?>" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,<?php echo $value['id'];?>);">
									<img class="" src="<?php echo $value['sunshine_icon'];?>" alt="<?php echo $value['name'];?>">
								</li>
							<?php } } } ?>

<!-- 
		                    <li class="reaction reaction-like animated_2" data-reaction="Like" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Like');">
							<img class="" src="<?php echo $wo['config']['theme_url'];?>/reaction/like.gif" alt="<?php echo $wo['lang']['like'];?>">
							</li>
							<li class="reaction reaction-love animated_4" data-reaction="Love" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Love');">
								<img class="" src="<?php echo $wo['config']['theme_url'];?>/reaction/love.gif" alt="<?php echo $wo['lang']['love'];?>">
							</li>
							<li class="reaction reaction-haha animated_6" data-reaction="HaHa" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'HaHa');">
								<img class="" src="<?php echo $wo['config']['theme_url'];?>/reaction/haha.gif" alt="<?php echo $wo['lang']['haha'];?>">
							</li>
							<li class="reaction reaction-wow animated_8" data-reaction="Wow" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Wow');">
								<img class="" src="<?php echo $wo['config']['theme_url'];?>/reaction/wow.gif" alt="<?php echo $wo['lang']['wow'];?>">
							</li>
							<li class="reaction reaction-sad animated_10" data-reaction="Sad" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Sad');">
								<img class="" src="<?php echo $wo['config']['theme_url'];?>/reaction/sad.gif" alt="<?php echo $wo['lang']['sad'];?>">
							</li>
							<li class="reaction reaction-angry animated_12" data-reaction="Angry" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Angry');">
								<img class="" src="<?php echo $wo['config']['theme_url'];?>/reaction/angry.gif" alt="<?php echo $wo['lang']['angry'];?>">
							</li> -->
		                </ul>
		            </div>
		            <?php }else{ ?>


				<span class="pointer add-blog-commreply-likes-<?php echo $wo['comm-reply']['id']; ?>" onclick="Wo_AddBlogCommReplyLike(<?php echo $wo['comm-reply']['id']; ?>)">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg>
				</span> 
				<span id="blog-comment-likes" data-blog-comrlikes="<?php echo $wo['comm-reply']['id']; ?>">
					<?php if ($wo['comm-reply']['likes'] > 0): ?>
						<?php echo $wo['comm-reply']['likes']; ?>
					<?php endif ?>
				</span> 
				&nbsp;
				<span class="pointer add-blog-commreply-dislikes-<?php echo $wo['comm-reply']['id']; ?>" onclick="Wo_AddBlogCommReplyDisLike(<?php echo $wo['comm-reply']['id']; ?>)">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-down"><path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17"></path></svg>
				</span> 
				<span id="blog-comment-likes" data-blog-comrdislikes="<?php echo $wo['comm-reply']['id']; ?>">
					<?php if ($wo['comm-reply']['dislikes'] > 0): ?>
						<?php echo $wo['comm-reply']['dislikes']; ?>
					<?php endif ?>
				</span> 
			<?php } ?>
			</span>
		</div>
	</div>
</div>