<?php echo Wo_LoadPage('events/includes/header'); ?>
	
	<?php if (count($wo['events']) > 0): ?>
		<div id="events-going">
			<?php foreach ($wo['events'] as $wo['event']): ?>
				<?php echo Wo_LoadPage('events/includes/events-list'); ?>
			<?php endforeach; ?>
			<div class="clear"></div>
		</div>
		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
			 	<div class="posts_load">
				    <?php if (count($wo['events']) > 9): ?>
					<div class="load-more">
	                    <button class="btn btn-default text-center pointer load-more-events" data-events-type="going">
	                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more'] ?></button>
	                </div>
	                <?php endif ?>
				</div>
			</div>
		</div>
	<?php else: ?>
		<?php echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" /></svg>'. $wo['lang']['no_events_found'] .' </div>';?>
	<?php endif; ?>
<?php echo Wo_LoadPage('events/includes/footer'); ?>