<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M17,3H7A2,2 0 0,0 5,5V21L12,18L19,21V5C19,3.89 18.1,3 17,3Z"></path></svg></span> <?php echo $wo['lang']['saved_posts']; ?>
					</div>
				</div>
			</div>
			
			<div class="saved-posts">
				<?php
					$stories = Wo_GetSavedPosts($wo['user']['user_id']);
					if (count($stories) <= 0) {
						echo Wo_LoadPage('saved-posts/no-posts');
					} else {
						foreach ($stories as $wo['story']) {
							echo Wo_LoadPage('story/content');
						}
					}
				?>
			</div>
		</div>
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>