<div class="post-container">
  <div class="post<?php echo (!empty($wo['story']['post_is_promoted'])) ? ' boosted': '';?>" id="post-<?php echo $wo['story']['id']; ?>" data-post-id="<?php echo $wo['story']['id'];?>" <?php if( isset( $wo['story']['LastTotal'] ) ) { echo 'data-post-total="'.$wo['story']['LastTotal'].'"'; }?> <?php if( isset( $wo['story']['ids'] ) ) { echo 'data-post-ids="'.$wo['story']['ids'].'"'; }?> <?php if( isset( $wo['story']['dt'] ) ) { echo 'data-post-dt="'.$wo['story']['dt'].'"'; }?>>
    <?php
      if (empty($wo['page'])) {
        $wo['page'] = 'home';
      }
     if ($wo['story']['is_post_pinned'] === true && ($wo['page'] == 'timeline' || $wo['page'] == 'events' || $wo['page'] == 'page' || $wo['page'] == 'group' )) {?>
    <div class="pin-icon" data-toggle="tooltip" title="<?php echo $wo['lang']['pinned_post'];?>">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bookmark"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg>
    </div>
    <?php } ?>
    <div class="panel panel-white panel-shadow">
      <div class="post-heading">
        <div class="<?php echo Wo_RightToLeft('pull-left');?> image">
            <a href="<?php echo $wo['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['publisher']['username']?>">
            <img src="<?php echo $wo['story']['publisher']['avatar']; ?>" id="updateImage-<?php echo $wo['story']['publisher']['user_id']?>" class="avatar" alt="<?php echo $wo['story']['publisher']['name']; ?> profile picture">
            </a>
        </div>
        <div class="meta">
          <div class="title h5">
            <span class="user-popover" data-type="<?php echo $wo['story']['publisher']['type']; ?>" data-id="<?php echo $wo['story']['publisher']['id']; ?>">

              <a href="<?php echo $wo['story']['publisher']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['publisher']['username']; ?>"><b><?php echo $wo['story']['publisher']['name']; ?></b></a>
              <?php if($wo['story']['publisher']['verified'] == 1) { ?>
                <span class="verified-color">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" /></svg>
                </span>
              <?php } ?>
              
            
            </span>
            <?php if (isset($wo['story']['publisher']['is_pro'])) { 
              if(Wo_IsUserPro($wo['story']['publisher']['is_pro']) === true) { ?>
            <?php 
            $user_pro_type = Wo_GetUserProType($wo['story']['publisher']['pro_type']);
            ?>
            <span style="color:<?php echo $user_pro_type['color_name'];?>"><i class="fa fa-<?php echo $user_pro_type['icon'];?> fa-fw" title="<?php echo $user_pro_type['type_name'];?>" data-toggle="tooltip"></i></span>
            <?php } } ?>

            <?php if ($wo['story']['shared_from'] && is_array($wo['story']['shared_from'])): ?>
              <span class="user-popover" data-type="<?php echo $wo['story']['shared_from']['type']; ?>" data-id="<?php echo $wo['story']['shared_from']['id']; ?>">         
                    <span><?php echo $wo['lang']['shared']; ?></span> 
                    <a href="<?php echo $wo['story']['shared_from']['url']; ?>" class="pointer no_decor" data-ajax="?link1=timeline&u=<?php echo $wo['story']['shared_from']['username']; ?>"><b><?php echo $wo['story']['shared_from']['name']; ?></b></a>
                    <?php if($wo['story']['shared_from']['verified'] == 1) { ?>
                    <span class="verified-color">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" /></svg>
                    </span>
              <?php } ?>
              </span>
            <?php endif; ?>
            <?php if ($wo['story']['shared_from'] && is_array($wo['story']['shared_from'])): ?>
            <span>  
              <a href="<?php echo $wo['story']['post_url']; ?>" class="pointer"><span style="color: #666;"><?php echo strtolower($wo['lang']['post']); ?></span></a>
            </span>
            <?php endif; ?>

          

            <?php if ($wo['story']['recipient_exists'] == true) {  ?>
            <i class="fa fa-arrow-right"></i>
            <span class="user-popover" data-type="<?php echo $wo['story']['recipient']['type']; ?>" data-id='<?php echo $wo['story']['recipient']['id']; ?>'>
            <a href="<?php echo $wo['story']['recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['recipient']['username']; ?>">
            <b>
            <?php echo $wo['story']['recipient']['name']; ?>
            </b>
            </a>
            <?php if($wo['story']['recipient']['verified'] == 1) { ?> <span class="verified-color"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" /></svg></span>
            <?php } ?>
            </span>
            <?php } ?>

            <?php if (!empty($wo['story']['page_event_id'])) {?>
            <small class="small-text"> <?php echo $wo['lang']['created_new_event'] ?></small>
            <?php } ?>
            <?php if (!empty($wo['story']['event_id']) && $wo['page'] != 'events') {  ?>
            <i class="fa fa-arrow-right"></i> <a href="<?php echo $wo['story']['event']['url']; ?>" data-ajax="?link1=show-event&eid=<?php echo $wo['story']['event']['id']; ?>"><b><?php echo $wo['story']['event']['name']; ?></b></a>
            <?php } ?>
            <?php if ($wo['story']['group_recipient_exists'] == true && $wo['page'] != 'group') {  ?>
            <i class="fa fa-arrow-right"></i>
            <span class="user-popover" data-type="<?php echo $wo['story']['group_recipient']['type']; ?>" data-id='<?php echo $wo['story']['group_recipient']['id']; ?>'>
            <a href="<?php echo $wo['story']['group_recipient']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['story']['group_recipient']['username']; ?>">
            <b><?php echo $wo['story']['group_recipient']['name']; ?></b>
            </a>
            </span>
            <?php } ?>
            <?php if (!empty($wo['story']['album_name']) && empty($wo['story']['shared_from'])) {  ?>
            <small class="small-text"><?php echo $wo['lang']['added_new_photos_to'];?> <b><a href="<?php echo $wo['story']['url']; ?>" data-ajax="?link1=post&id=<?php echo $wo['story']['id'];?>"><?php echo $wo['story']['album_name']; ?></a></b></small>
            <?php } ?>
            <?php if (!empty($wo['story']['product_id']) && empty($wo['story']['shared_from'])) {  ?>
            <small class="small-text"><?php echo $wo['lang']['added_new_product_for_sell']; ?></small>
            <?php } ?>
            <?php if (!empty($wo['story']['blog_id'])  && empty($wo['story']['shared_from'])) {  ?>
            <small class="small-text"><?php echo $wo['lang']['created_new_blog'] ?></small>
            <?php } ?>
            <?php if (empty($wo['story']['shared_from'])): ?>
              <small class="small-text">
                <?php 
                  if($wo['story']['postType'] == 'profile_picture') { 
                     $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_male'];
                     if ($wo['story']['publisher']['gender'] == 'female') {
                        $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_female'];
                     } else {
                        $changed_profile_pic_lang = $wo['lang']['changed_profile_picture_male'];
                     }
                     echo $changed_profile_pic_lang;
                  } 
                  if($wo['story']['postType'] == 'profile_cover_picture') { 
                     $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_male'];
                     if ($wo['story']['publisher']['gender'] == 'female') {
                        $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_female'];
                     } else {
                        $changed_profile_cover_pic_lang = $wo['lang']['changed_profile_cover_picture_male'];
                     }
                     echo $changed_profile_cover_pic_lang;
                  } 
                  ?>
              </small>
            <?php endif; ?>
            <?php if($wo['story']['via_type'] == 'share') {  ?>
            <small style="color:#a33e40;"><?php echo $wo['story']['via']['name'];?> <?php echo $wo['lang']['shared_this_post'];?></small>
            <?php }  ?>
            <?php 
          $extra_exists = 0;
          if (!empty($wo['story']['postFeeling'])) {
            if (empty($changed_profile_pic_lang) 
              && $wo['story']['via_type'] != 'share'
              && $wo['story']['group_recipient_exists'] != true
              && empty($wo['story']['album_name'])) {
          ?>
          <span class="feeling-text"> <?php echo $wo['lang']['is_feeling'];?> <i class="twa-lg twa twa-<?php echo $wo['story']['postFeelingIcon'];?>"></i> <?php echo $wo['lang'][$wo['story']['postFeeling']];?></span>
          <?php
          } else {
            $extra_exists = 1;
          }
          }
          if (!empty($wo['story']['postTraveling'])) {
            if (empty($changed_profile_pic_lang) 
              && $wo['story']['via_type'] != 'share'
              && $wo['story']['group_recipient_exists'] != true
              && empty($wo['story']['album_name'])) {
          ?>
          <span class="feeling-text"><i class="fa fa-plane"></i> <?php echo $wo['lang']['is_traveling'];?> <?php echo $wo['story']['postTraveling'];?></span>
          <?php
          } else {
            $extra_exists = 1;
          }
          }
          if (!empty($wo['story']['postListening'])) {
            if (empty($changed_profile_pic_lang) 
              && $wo['story']['via_type'] != 'share'
              && $wo['story']['group_recipient_exists'] != true
              && empty($wo['story']['album_name'])) {
          ?>
          <span class="feeling-text"><i class="fa fa-headphones"></i> <?php echo $wo['lang']['is_listening'];?> <?php echo $wo['story']['postListening'];?></span>
          <?php
          } else {
            $extra_exists = 1;
          }
          }
          if (!empty($wo['story']['postPlaying'])) {
            if (empty($changed_profile_pic_lang) 
              && $wo['story']['via_type'] != 'share'
              && $wo['story']['group_recipient_exists'] != true
              && empty($wo['story']['album_name'])) {
          ?>
          <span class="feeling-text"><i class="fa fa-gamepad"></i> <?php echo $wo['lang']['is_playing'];?> <?php echo $wo['story']['postPlaying'];?></span>
          <?php
          } else {
            $extra_exists = 1;
          }
          }
          if (!empty($wo['story']['postWatching'])) {
            if (empty($changed_profile_pic_lang) 
              && $wo['story']['via_type'] != 'share'
              && $wo['story']['group_recipient_exists'] != true
              && empty($wo['story']['album_name'])) {
          ?>
          <span class="feeling-text"><i class="fa fa-eye"></i> <?php echo $wo['lang']['is_watching'];?> <?php echo $wo['story']['postWatching'];?></span>
          <?php
          } else {
            $extra_exists = 1;
          }
          }
          ?>
          </div>
          <h6>
            <span class="time">
               <a  style="color:#9197a3" class="ajax-time" href="<?php echo $wo['story']['url'];?>" title="<?php echo date('c',$wo['story']['time']); ?>" target="_blank"><?php echo Wo_Time_Elapsed_String($wo['story']['time']); ?></a>
            </span>
            <?php if (strlen($wo['story']['postText']) >= 2): ?>
                <span onclick="Wo_Translate($(this).attr('id'),$(this).attr('data-language'))" title="<?php echo $wo['lang']['translate'];?>" class="pointer time" id="<?php echo $wo['story']['id']; ?>" data-language="<?php echo DetermineUserLang(); ?>" data-trans-btn="<?php echo $wo['story']['id']; ?>">
                  - <?php echo $wo['lang']['translate'];?>
                </span> 
            <?php endif ?>

            <?php if(!empty($wo['story']['postMap'])) { ?>
            <?php if(!empty($wo['story']['postSoundCloud']) || 
              !empty($wo['story']['postVine']) || 
              !empty($wo['story']['postYoutube']) || 
              !empty($wo['story']['postPlaytube']) || 
              !empty($wo['story']['postVimeo']) || 
              !empty($wo['story']['postText']) || 
              !empty($wo['story']['postFile']) || 
              !empty($wo['story']['postLink']) || 
              !empty($wo['story']['postFacebook']) || 
              !empty($wo['story']['postDailymotion']) ||
              !empty($wo['story']['album_name']) || ($wo['config']['google_map'] == 0 && $wo['config']['yandex_map'] == 0)) { ?>
            <span style="color:#9197a3"> - <i class="fa fa-map-marker"></i> <?php echo $wo['story']['postMap'];?>.</span>
            <?php } ?>
            <?php } else { ?>
            <?php
              $small_icon = '';
              $icon_type = '';
              if(!empty($wo['story']['postVine'])) { 
                 $small_icon = 'vine';
                 $icon_type = 'Vine';
              } else if (!empty($wo['story']['postVimeo'])) {
                 $small_icon = 'vimeo';
                 $icon_type = 'Vimeo';
              } else if (!empty($wo['story']['postFacebook'])) {
                 $small_icon = 'facebook-official';
                 $icon_type = 'Facebook';
              } else if (!empty($wo['story']['postDailymotion'])) {
                 $small_icon = 'film';
                 $icon_type = 'Dailymotion';
              } else if (!empty($wo['story']['postYoutube'])) {
                 $small_icon = 'youtube-square';
                 $icon_type = 'Youtube';
              } else if (!empty($wo['story']['postPlaytube'])) {
                // $small_icon = 'play-circle';
                // $icon_type = 'PlayTube';
              } else if (!empty($wo['story']['postSoundCloud'])) {
                 $small_icon = 'soundcloud';
                 $icon_type = 'SoundCloud';
              }
              if (!empty($icon_type)) {
              ?>
            <span style="color:#9197a3; text-transform: capitalize;">
             - <i class="fa fa-<?php echo $small_icon; ?>"></i> <?php echo $icon_type; ?>
            </span>
            <?php  } } ?>
          </h6>
        </div>
      </div>

      <div class="post-description" id="post-description-<?php echo $wo['story']['id']; ?>">
        <?php
        if (!empty($wo['story']['product_id'])) {
			$class = '';
            $small = '';
			$singleimg = '';
			if (count($wo['story']['product']['images']) == 1) {
                 $singleimg = 'wo_single_proimg';
            }
            if (count($wo['story']['product']['images']) == 2) {
                 $class = 'width-2';
            }
            if (count($wo['story']['product']['images']) > 1) {
                 $small = '_small';
            }
            if (count($wo['story']['product']['images']) > 2) {
                 $class = 'width-3';
            }
            if (count($wo['story']['product']['images']) > 3) {
             foreach (array_slice($wo['story']['product']['images'],0,3) as $key => $photo) {
              if ($key == 2) {
                  echo "<div onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");' class='album-collapse pointer'> 
                            <img src='".($photo['image_org'])."' class='image-file'>
                            <span>+".count(array_slice($wo['story']['product']['images'],2))."</span>
                        </div>
                        "; 
              }
              else{
                echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                       onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
              }
              
             }
             foreach (array_slice($wo['story']['product']['images'],3) as $photo) {
                echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer hidden' 
                      onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
             }
            }
            else{
              foreach ($wo['story']['product']['images'] as $photo) {
                echo  "<img src='" . ($photo['image_org']) ."' alt='image' class='" . $class . " " . $singleimg . " image-file pointer' 
                      onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"product\");'>";
              }
            }
			echo '<br><br>';
            $symbol =  (!empty($wo['currencies'][$wo['story']['product']['currency']]['symbol'])) ? $wo['currencies'][$wo['story']['product']['currency']]['symbol'] : $wo['config']['classified_currency_s'];
            $text =  (!empty($wo['currencies'][$wo['story']['product']['currency']]['text'])) ? $wo['currencies'][$wo['story']['product']['currency']]['text'] : $wo['config']['classified_currency'];

            $status = '<span class="product-description">' . $wo['lang']['currently_unavailable'] . '</span>';
            if ($wo['story']['product']['units'] > 0) {
              $status = ($wo['story']['product']['status'] == 0) ? '<span class="product-description">' . $wo['lang']['in_stock'] . '</span>' : '<span class="product-status-sold">' . $wo['lang']['sold'] . '</span><br><br>';
            }
            $type = ($wo['story']['product']['type'] == 0) ? '<span class="product-description">' . $wo['lang']['new'] . '</span>' : '<span class="product-description">' . $wo['lang']['used'] . '</span><br>';
            echo '<div class="product-name"><h4 class="product-description">' . $wo['story']['product']['name'] . '</h4></div>';
			if (!empty($wo['story']['product']['location'])) {
               echo '<div class="product-name"><span class="product_row_title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg></span> <span class="product-description"> ' . $wo['story']['product']['location'] . '</span></div><br>';
            }
            echo '<div class="product-name"><p class="product-description product-description-'.$wo['story']['product']['id'].'">' . $wo['story']['product']['description'] . '</p></div><br>';
            echo '<div class="wo_product_row"><div class="product-name"><span class="product_row_title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tag" color="#2196F3"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7" y2="7"></line></svg>' . $wo['lang']['type'] . '</span> ' . $type . '</div>';
			echo '<div class="product-name"><span class="product_row_title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-credit-card" color="#349238"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect><line x1="1" y1="10" x2="23" y2="10"></line></svg>' . $wo['lang']['price'] . '</span> <span class="product-description" style="max-height: none;">' . $symbol . $wo['story']['product']['price'] . ' (' . $text . ')</span></div>';
            echo '<div class="product-name"><span class="product_row_title"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-package" color="#9C27B0"><path d="M12.89 1.45l8 4A2 2 0 0 1 22 7.24v9.53a2 2 0 0 1-1.11 1.79l-8 4a2 2 0 0 1-1.79 0l-8-4a2 2 0 0 1-1.1-1.8V7.24a2 2 0 0 1 1.11-1.79l8-4a2 2 0 0 1 1.78 0z"></path><polyline points="2.32 6.16 12 11 21.68 6.16"></polyline><line x1="12" y1="22.76" x2="12" y2="11"></line><line x1="7" y1="3.5" x2="17" y2="8.5"></line></svg>' . $wo['lang']['status'] . '</span> ' . $status . '</div></div>';
            
          } 
        ?>
        <p dir="auto">
        <span data-translate-text="<?php echo $wo['story']['id']; ?>"> <?php echo $wo['story']['postText']; ?></span>
        <?php if (!empty($wo['story']['postFeeling']) && $extra_exists == 1) { ?>
        <span class="feeling-text"> — <i class="twa-lg twa twa-<?php echo $wo['story']['postFeelingIcon'];?>"></i> <?php echo $wo['lang']['feeling'];?> <?php echo $wo['lang'][$wo['story']['postFeeling']];?></span>
        <?php } ?>
        <?php if (!empty($wo['story']['postTraveling']) && $extra_exists == 1) { ?>
        <span class="feeling-text"> — <i class="fa fa-plane"></i> <?php echo $wo['lang']['traveling'];?><?php echo $wo['story']['postTraveling'];?></span>
        <?php } ?>
        <?php if (!empty($wo['story']['postWatching']) && $extra_exists == 1) { ?>
        <span class="feeling-text"> — <i class="fa fa-eye"></i> <?php echo $wo['lang']['watching'];?> <?php echo $wo['story']['postWatching'];?></span>
        <?php } ?>
        <?php if (!empty($wo['story']['postPlaying']) && $extra_exists == 1) { ?>
        <span class="feeling-text"> — <i class="fa fa-gamepad"></i> <?php echo $wo['lang']['playing'];?> <?php echo $wo['story']['postPlaying'];?></span>
        <?php } ?>
         <?php if (!empty($wo['story']['postListening']) && $extra_exists == 1) { ?>
        <span class="feeling-text"> — <i class="fa fa-headphones"></i> <?php echo $wo['lang']['listening'];?> <?php echo $wo['story']['postListening'];?></span>
        <?php } ?>
        </p>
        <?php if(!empty($wo['story']['postYoutube'])) {  ?>
        <div class="post-youtube wo_video_post">
          <iframe id="ytplayer" type="text/html" width="100%" height="340" src="https://www.youtube.com/embed/<?php echo $wo['story']['postYoutube']; ?>?autoplay=0"
            frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen/></iframe>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['postPlaytube'])) {  ?>
        <div class="post-youtube wo_video_post">
          <iframe id="ptplayer" type="text/html" width="100%" height="340" src="<?php echo $wo['config']['playtube_url']; ?>/embed/<?php echo $wo['story']['postPlaytube']; ?>?autoplay=0&fullscreen=1"
            frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen/></iframe>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['postVimeo'])) {  ?>
        <div class="post-youtube wo_video_post">
          <iframe src="https://player.vimeo.com/video/<?php echo $wo['story']['postVimeo'];?>?byline=0&portrait=0" width="100%" height="340" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['postFacebook'])) {  ?>
        <div class="post-youtube wo_video_post">
          <iframe src="https://www.facebook.com/plugins/video.php?href=https://www.facebook.com/<?php echo $wo['story']['postFacebook'];?>&show_text=0" width="100%" height="100%" frameborder="0" allowfullscreen></iframe>
          <div class="clear"></div>
        </div>

        <?php } ?>
        <?php if(!empty($wo['story']['postDailymotion'])) {  ?>
        <div class="post-youtube wo_video_post">
          <iframe frameborder="0" width="100%" height="340" src="https://www.dailymotion.com/embed/video/<?php echo $wo['story']['postDailymotion']?>" allowfullscreen></iframe>
        </div>

        
        <?php } ?>
        <?php if(!empty($wo['story']['postVine'])) {  ?>
        <iframe src="https://vine.co/v/<?php echo $wo['story']['postVine']; ?>/embed/simple" width="100%" height="400" frameborder="0"></iframe>
        <?php } ?>
        <?php if(!empty($wo['story']['postSoundCloud'])) { ?>
        <iframe width="100%" src="https://w.soundcloud.com/player/?url=https://api.soundcloud.com/tracks/<?php echo $wo['story']['postSoundCloud'];?>&auto_play=false"></iframe>
        <?php } ?>
        <?php if(!empty($wo['story']['postMap']) && empty($wo['story']['postVine']) && empty($wo['story']['postSoundCloud']) && empty($wo['story']['postVimeo']) && empty($wo['story']['postDailymotion']) && empty($wo['story']['postYoutube']) && empty($wo['story']['postPlaytube']) && empty($wo['story']['postFile']) && ($wo['config']['google_map'] == 1 || $wo['config']['yandex_map'] == 1)) { ?>
        <div class="post-map">
          <?php if ($wo['config']['yandex_map'] == 1) { ?>
            <div id="share_place_<?php echo($wo['story']['id']) ?>" <?php echo($wo['config']['yandex_map'] == 1 ? 'style="width: 100%; height: 300px; padding: 0; margin: 0;"' : '') ?>></div>
          <script type="text/javascript">
              <?php if (!empty($wo['story']['postMap'])) { ?>
                setTimeout(function () {
                  var myMap;
                  ymaps.geocode("<?php echo($wo['story']['postMap']); ?>").then(function (res) {
                      myMap = new ymaps.Map('share_place_<?php echo($wo['story']['id']) ?>', {
                          center: res.geoObjects.get(0).geometry.getCoordinates(),
                          zoom : 10
                      });
                      myMap.geoObjects.add(new ymaps.Placemark(res.geoObjects.get(0).geometry.getCoordinates(), {
                          balloonContent: ''
                      }));
                  });
                },1000);
              <?php } ?>
            </script>
          <?php } ?>
          <?php if ($wo['config']['google_map'] == 1) { ?>
          <img src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $wo['story']['postMap'];?>&zoom=13&size=600x250&maptype=roadmap&markers=color:red%7C<?php echo $wo['story']['postMap'];?>&key=<?php echo $wo['config']['google_map_api'];?>" width="100%">
          <?php } ?>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['postLink']) && empty($wo['story']['postVine']) && empty($wo['story']['postPlaytube']) && empty($wo['story']['postSoundCloud']) && empty($wo['story']['postYoutube']) && empty($wo['story']['postFile'])) { ?>
        <div class="post-fetched-url wo_post_fetch_link">
          <a href="<?php echo $wo['story']['postLink'];?>" target="_blank">
            <?php if (!empty($wo['story']['postLinkImage'])) {?>
            <div class="post-fetched-url-con">
              <img src="<?php echo $wo['story']['postLinkImage'];?>" class="<?php echo Wo_RightToLeft('pull-left');?>" alt="<?php echo $wo['story']['postLinkTitle'];?>"/>
			        <div class="url">
                <?php 
                  $parse = parse_url($wo['story']['postLink']);
                  echo $parse['host'];
                  ?>
              </div>
            </div>
            <?php } ?>
            <div class="fetched-url-text">
        			<h4><?php echo $wo['story']['postLinkTitle'];?></h4>
        			<div class="description"><?php echo $wo['story']['postLinkContent'];?></div>
            </div>
            <div class="clear"></div>
            </a>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['page_event_id'])) { ?>
        <div class="post-fetched-url wo_post_fetch_event">
          <a href="<?php echo $wo['story']['event']['url'];?>">
            <?php if (!empty($wo['story']['event']['cover'])) {?>
            <div class="post-fetched-url-con">
              <img src="<?php echo $wo['story']['event']['cover'];?>" class="<?php echo Wo_RightToLeft('pull-left');?>"/>
			  <div class="description">
				<p>
				<?php if (strlen($wo['story']['event']['description']) > 175):?>
					<?php echo mb_substr($wo['story']['event']['description'],0,175,"UTF-8") . "..."; ?>
				<?php else:?>
					<?php echo $wo['story']['event']['description']; ?>
				<?php endif;?>
				</p>
			  </div>
            </div>
            <?php } ?>
            <div class="fetched-url-text">
              <h4><?php echo $wo['story']['event']['name'];?></h4>
			  <div class="url">
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg> <?php echo $wo['story']['event']['start_date'];?> - <?php echo $wo['story']['event']['end_date'];?>
              </div>
            </div>
            <div class="clear"></div>
            </a>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['blog_id'])) { ?>
        <div class="post-fetched-url wo_post_fetch_blog">
          <a href="<?php echo $wo['story']['blog']['url'];?>">
			<div class="fetched-url-text">
			  <h4><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg> <?php echo $wo['story']['blog']['title'];?></h4>
              <div class="description"><?php echo $wo['story']['blog']['description'];?></div>
            </div>
            <?php if (!empty($wo['story']['blog']['thumbnail'])) {?>
            <div class="post-fetched-url-con">
              <img src="<?php echo $wo['story']['blog']['thumbnail'];?>" class="<?php echo Wo_RightToLeft('pull-left');?>" alt="<?php echo $wo['story']['blog']['title'];?>"/>
            </div>
            <?php } ?>
            <div class="clear"></div>
            </a>
        </div>
        <?php } ?>
        <?php if(!empty($wo['story']['postFile'])) { ?>

        <div class="post-file" id="fullsizeimg">
          <!-- <div style="width: 100%;height: 100%;position: absolute;background-color: rgba(0,0,0,0.3);filter: blur(5px);"></div> -->
            <?php
            $media = array(
                'type' => 'post',
                'storyId' => $wo['story']['id'],
                'filename' => $wo['story']['postFile'],
                'name' => $wo['story']['postFileName'],
                'postFileThumb' => $wo['story']['postFileThumb'],
            );
            echo Wo_DisplaySharedFile($media, '', $wo['story']['cache']);
            ?>
        </div>

        <?php } ?>
        <?php if (Wo_IsUrl($wo['story']['postSticker'])): ?>
          <div class="post-file wo_video_post">
            <?php if (strpos('.mp4', $wo['story']['postSticker'])) { ?>
            <video autoplay loop><source src="<?php echo $wo['story']['postSticker']; ?>" type="video/mp4"></video>
            <?php } else { ?>
            <img src="<?php echo $wo['story']['postSticker']; ?>" alt="GIF">
            <?php } ?>
          </div>
        <?php endif; ?>
        <?php if (Wo_IsUrl($wo['story']['postPhoto'])): ?>
          <div class="post-file" id="fullsizeimg">
            <img src="<?php echo $wo['story']['postPhoto']; ?>" alt="Picture">
          </div>
        <?php endif; ?>
        <?php if(!empty($wo['story']['postRecord'])) { ?>
        <div class="post-file">
            <?php  
              $media = array(
                'type' => 'post',
                'storyId' => $wo['story']['id'],
                'filename' => $wo['story']['postRecord'],
                'name' => ''
              );
              echo  Wo_DisplaySharedFile($media,'record');
            ?>
        </div>
        <?php } ?>
        <div id="fullsizeimg" style="position: relative;">
          <?php if (!empty($wo['story']['photo_album']) && $wo['story']['blur'] == 1) { ?>
            <div class="post-file show_album_<?php echo $wo['story']['id']; ?> blur_multi_images" id="fullsizeimg">
              <button class='btn btn-main image_blur_btn remover_blur_btn_<?php echo $wo['story']['id']; ?>' onclick='Wo_RemoveBlurAlbum(this,<?php echo $wo['story']['id']; ?>)'><?php echo $wo['lang']['view_image']; ?></button>
                  <img src="<?php echo(Wo_GetMedia($wo['story']['photo_album'][0]['image_org'])) ?>" alt='image' class='image-file pointer image_blur remover_blur_<?php echo $wo['story']['id']; ?>'>
                </div>
          <?php } ?>
        <?php if (!empty($wo['story']['photo_album'])) {
           $class = '';
           $small = '';
           if (count($wo['story']['photo_album']) == 2) {
                $class = 'width-2';
           }
           if (count($wo['story']['photo_album']) > 1) {
                $small = '_small';
           }
           if (count($wo['story']['photo_album']) > 2) {
                $class = 'width-3';
           }
           $delete  = '';
           $onhover = '';
			
			if (count($wo['story']['photo_album']) == 3) {
				echo "<div class='wo_adaptive_media'>";
             foreach ($wo['story']['photo_album'] as $photo) {
                if ($wo['story']['admin'] === true) {
                $delete = "<span onclick='Wo_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='Wo_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='Wo_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
			 
			 echo "</div>";
			}
			
			else if (count($wo['story']['photo_album']) == 4) {
				echo "<div class='wo_adaptive_media_4'>";
             foreach ($wo['story']['photo_album'] as $photo) {
                if ($wo['story']['admin'] === true) {
                $delete = "<span onclick='Wo_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='Wo_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='Wo_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
			 
			 echo "</div>";
			}
			
			else if (count($wo['story']['photo_album']) == 5) {
				echo "<div class='wo_adaptive_media_5'>";
             foreach ($wo['story']['photo_album'] as $photo) {
                if ($wo['story']['admin'] === true) {
                $delete = "<span onclick='Wo_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='Wo_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='Wo_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
			 
			 echo "</div>";
			}
			
			else if (count($wo['story']['photo_album']) > 3) {
             foreach (array_slice($wo['story']['photo_album'],0,3) as $key => $photo) {
              if ($key == 2) {
                  echo "<div onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");' class='album-collapse pull-left pointer'> 
                            <img src='".Wo_GetMedia($photo['image_org'])."' class='image-file'>
                            <span>+".count(array_slice($wo['story']['photo_album'],2))."</span>
                        </div>
                        "; 
              }
              else{
                if ($wo['story']['admin'] === true) {
                  $delete = "<span onclick='Wo_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='Wo_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='Wo_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file  pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
                }
             }
             foreach (array_slice($wo['story']['photo_album'],3) as $photo) {
                if ($wo['story']['admin'] === true) {
                $delete = "<span onclick='Wo_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='Wo_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='Wo_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                echo  "<div class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer hidden' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
          }
          else{
              foreach ($wo['story']['photo_album'] as $photo) {
                if ($wo['story']['admin'] === true) {
                  $delete = "<span onclick='Wo_RemoveAlbumImage(" . $photo['post_id'] . "," . $photo['id'] . ");' class='pointer'><i class='fa fa-remove'></i></span>";
                  $onhover = "onmouseover='Wo_ShowDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ")' onmouseleave='Wo_HideDeleteButton(" . $photo['post_id'] . "," . $photo['id'] . ");'";
                }
                echo  "<div style='text-align:center;width: 100%;' class='album-image " . $class . "' id='image-" . $photo['id'] . "' {$onhover}>{$delete}<img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
              }
          }
        } 
        ?>
        <?php if ($wo['story']['multi_image'] == 1) {
          if ($wo['story']['blur'] == 1) { ?>
            <div class="post-file show_album_<?php echo $wo['story']['id']; ?> blur_multi_images" id="fullsizeimg">
              <button class='btn btn-main image_blur_btn remover_blur_btn_<?php echo $wo['story']['id']; ?>' onclick='Wo_RemoveBlurAlbum(this,<?php echo $wo['story']['id']; ?>)'><?php echo $wo['lang']['view_image']; ?></button>
                  <img src="<?php echo(Wo_GetMedia($wo['story']['photo_multi'][0]['image_org'])) ?>" alt='image' class='image-file pointer image_blur remover_blur_<?php echo $wo['story']['id']; ?>'>
                </div>
          <?php }
           $class = '';
           $small = '';
           if (count($wo['story']['photo_multi']) == 2) {
                $class = 'width-2';
           }
           if (count($wo['story']['photo_multi']) > 1) {
                $small = '_small';
           }
           if (count($wo['story']['photo_multi']) > 2) {
                $class = 'width-3';
           }
			
			if (count($wo['story']['photo_multi']) == 3) {
				echo "<div class='wo_adaptive_media'>";
             foreach ($wo['story']['photo_multi'] as $photo) {
                echo  "<div class='album-image'><img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
			 echo "</div>";
			}
			
			else if (count($wo['story']['photo_multi']) == 4) {
				echo "<div class='wo_adaptive_media_4'>";
             foreach ($wo['story']['photo_multi'] as $photo) {
                echo  "<div class='album-image'><img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
			 echo "</div>";
			}
			
			else if (count($wo['story']['photo_multi']) == 5) {
				echo "<div class='wo_adaptive_media_5'>";
             foreach ($wo['story']['photo_multi'] as $photo) {
                echo  "<div class='album-image'><img src='" . Wo_GetMedia($photo['image_org']) . "' alt='image' class='image-file pointer' onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'></div>";
             }
			 echo "</div>";
			}
			
           else if (count($wo['story']['photo_multi']) > 3) {
             foreach (array_slice($wo['story']['photo_multi'],0,3) as $key => $photo) {
              if ($key == 2) {
                  echo "<div onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");' class='album-collapse pointer'> 
                            <img src='".Wo_GetMedia($photo['image_org'])."' class='image-file'>
                            <span>+".count(array_slice($wo['story']['photo_multi'],2))."</span>
                        </div>
                        "; 
              }
              else{
                echo  "<img src='" . Wo_GetMedia($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                       onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'>";
              }
              
             }
             foreach (array_slice($wo['story']['photo_multi'],3) as $photo) {
                echo  "<img src='" . Wo_GetMedia($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer hidden' 
                      onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'>";
             }
           }
		   else{
              foreach ($wo['story']['photo_multi'] as $photo) {
                echo  "<img src='" . Wo_GetMedia($photo['image_org']) ."' alt='image' class='" . $class . " image-file pointer' 
                      onclick='Wo_OpenAlbumLightBox(" . $photo['id'] . ", \"album\");'>";
              }
           }
        }
        ?>
        <div class="clear"></div>
        </div>
        <?php
        if ($wo['story']['poll_id'] == 1) {
           echo Wo_LoadPage('story/entries/options');
        }
        ?>
        <div class="clear"></div>

        <?php if ($wo['loggedin'] == true) { ?>
        <div class="stats post-actions <?php echo Wo_RightToLeft('pull-left');?>" id="<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>active_react<?php } ?>">
          
          <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
            <div class="like-stat stat-item post-like-status">
              <span class="like-emo post-reactions-icons-<?php echo $wo['story']['id']; ?>">
				<?php echo Wo_GetPostReactions($wo['story']['id']);?>
              </span>
            </div>
          <?php }else{ ?>

            <div class="btn btn-default stat-item post-like-status" title="<?php echo $wo['lang']['likes'];?>" onclick="Wo_OpenPostLikedUsers(<?php echo $wo['story']['id'] ?>);">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg>
              <span id="likes">
              <?php echo $wo['story']['post_likes'];?>
              </span>
            </div>
            <?php if ($wo['config']['second_post_button'] != 'disabled') { ?>
            <div class="btn btn-default stat-item post-wonders-status" title="<?php echo ($wo['config']['second_post_button'] == 'wonder') ? $wo['lang']['wonders']: $wo['lang']['dislikes'];?>" onclick="Wo_OpenPostWonderedUsers(<?php echo $wo['story']['id'] ?>);">
              <?php echo $wo['second_post_button_icon'];?>
              <span id="wonders">
              <?php echo $wo['story']['post_wonders'];?>
              </span>
            </div>
            <?php } ?>

          <?php } ?>

          <?php if (!empty($wo['story']['postFile']) && strpos($wo['story']['postFile'], '_video') !== false): ?>
            <div class="btn btn-default stat-item post-wonders-status" <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>style="line-height: 2;"<?php } ?>>
             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
              <span data-post-video-views="<?php echo $wo['story']['id']; ?>">
              <?php echo $wo['story']['videoViews'];?>
              </span>
            </div>
          <?php endif; ?>
        </div>
		    <?php if ($wo['story']['comments_status'] == 1) { ?> 
		    <div class="stats post-actions  <?php echo Wo_RightToLeft('pull-right');?>">
          <div class="btn btn-default stat-item" title="<?php echo $wo['lang']['comments'];?>" onclick="Wo_ShowComments(<?php echo $wo['story']['id'] ?>);">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg> 
            <span id="comments">
            <?php echo $wo['story']['post_comments'];?>
            </span>
          </div>
        </div>
      <?php } ?>
        
        <div class="clear"></div>
        <hr>
        <?php } ?>
        <div class="clear"></div>
      </div>
      
    </div>
  </div>
  <div class="clear"></div>
</div>

<script type="text/javascript">
$(function () {
  <?php if (!empty($wo['story']['product_id'])): ?>
  ReadMoreText("#post-<?php echo $wo['story']['id']; ?> .product-description-<?php echo $wo['story']['product_id']; ?>");
  <?php endif; ?>
  ReadMoreText("#post-<?php echo $wo['story']['id']; ?> .post-description p");
    $("#post-<?php echo $wo['story']['id']; ?> .textarea").triggeredAutocomplete({
       hidden: '#hidden_inputbox_comment',
       source: Wo_Ajax_Requests_File() + "?f=mention",
       trigger: "@" 
    });
    $('[data-toggle="tooltip"]').tooltip();
    $('.dropdown-menu.post-recipient, .dropdown-menu.post-options, .wo_emoji_post').click(function (e) {
      e.stopPropagation();
    });
});

jQuery(document).click(function(event){
    if (!(jQuery(event.target).closest(".remove_combo_on_click").length)) {
        jQuery('.remove_combo_on_click').removeClass('comment-toggle');
    }
});


</script>