<div class="blog-comment-item" data-blog-comment-reply="<?php echo $wo['comm-reply']['id']; ?>">
	<div class="col-md-1 col-sm-1 col-xs-1"></div>
	<div class="col-md-1 col-sm-1 col-xs-1 <?php echo Wo_RightToLeft('pull-left');?> blog-comment-item-img">
		<img src="<?php echo $wo['comm-reply']['user_data']['avatar']; ?>" alt="" class="responsive-img img-circle">
	</div>
	<div class="col-md-10 <?php echo Wo_RightToLeft('pull-right');?> col-sm-10 col-xs-9 blog-comment-item-body">
		<h5>
			<a class="pointer bold" data-ajax="?link1=timeline&u=<?php echo $wo['comm-reply']['user_data']['username']; ?>" href="<?php echo $wo['comm-reply']['user_data']['url']; ?>">
				<?php echo $wo['comm-reply']['user_data']['name']; ?>
			</a>
			<span class="time">
				<span class="ajax-time" title="<?php echo date('c',$wo['comm-reply']['posted']); ?>">
					<?php echo Wo_Time_Elapsed_String($wo['comm-reply']['posted']); ?>
				</span>
			</span>
			<?php if ($wo['comm-reply']['is_owner']): ?>
				<span class="pointer <?php echo Wo_RightToLeft('pull-right');?> del-blog-commreplies" id="<?php echo $wo['comm-reply']['id']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" /></svg>
				</span>
			<?php endif ?>
		</h5>
		<p><?php echo $wo['comm-reply']['text']; ?></p>
		<div>
			<span class="comment-icons">
				<span class="pointer reply-toblogcomm-reply"  data-blog-commId="<?php echo $wo['comm-reply']['comm_id']; ?>" id="<?php echo $wo['comm-reply']['id']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M10,9V5L3,12L10,19V14.9C15,14.9 18.5,16.5 21,20C20,15 17,10 10,9Z" /></svg>
				</span>
				&nbsp;

				<?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
		            <!-- reaction -->
		            <div class="like-stat stat-item" id="comment_reacted">
		              <span class="like-emo replay-reactions-icons-<?php echo $wo['comm-reply']['id']; ?>">
		              <?php echo Wo_GetPostReactions($wo['comm-reply']['id'],"reply",'blog');?>
		              </span>
		            </div>
					<div class="wo-reaction wo-reaction-replay stat-item" data-id="<?php echo $wo['comm-reply']['id']; ?>" id="comment_reactions">
		                <span class="like-btn like-btn-replay" data-id="<?php echo $wo['comm-reply']['id']; ?>">
		                    <?php
		                    if (Wo_IsReacted($wo['comm-reply']['id'], $wo['comm-reply']['user_id'],"reply",'blog') === true) {    
		                    echo '<span class="replay-status-reaction-'.$wo['comm-reply']['id'].' active-like"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg> <span class="r_likes-'.$wo['comm-reply']['id'].'"></span></span>';   
		                    } else {   
		                    echo '<span class="replay-status-reaction-'.$wo['comm-reply']['id'].'"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="feather" viewBox="0 0 24 24"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg> <span class="r_likes-'.$wo['comm-reply']['id'].'"></span></span>';   
		                    }    
		                    ?>
		                </span>
		                <ul class="reactions-box reactions-box-comment-replay-container-<?php echo $wo['comm-reply']['id']; ?>" data-id="<?php echo $wo['comm-reply']['id']; ?>" style="<?php if ($wo['language_type'] == 'rtl') {?> left: auto; <?php }else{ ?> right: auto; <?php }?>">

		                	<?php if (!empty($wo['reactions_types'])) {
		                      foreach ($wo['reactions_types'] as $key => $value) {
		                        if ($value['status'] == 1) {
		                          
		                       ?>
		                    <li class="reaction reaction-<?php echo $value['id'];?>" data-reaction="<?php echo $value['name'];?>" data-reaction-id="<?php echo $value['id'];?>" data-reaction-lang="<?php echo $value['name'];?>" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,<?php echo $value['id'];?>);">
		                      <?php if (preg_match("/<[^<]+>/",$value['wowonder_icon'],$m)) {
		                            echo($value['wowonder_icon']);
		                         }
		                         else{ ?>
		                          <img src="<?php echo($value['wowonder_icon']) ?>">
		                        <?php } ?>
		                    </li>
		                  <?php } } } ?>


		                    <!-- <li class="reaction reaction-like animated_2" data-reaction="Like" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Like');">
								<div class="emoji emoji--like">
									<div class="emoji__hand"><div class="emoji__thumb"></div></div>
								</div>
							</li>
		                    <li class="reaction reaction-love animated_4" data-reaction="Love" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Love');">
								<div class="emoji emoji--love">
									<div class="emoji__heart"></div>
								</div>
							</li>
		                    <li class="reaction reaction-haha animated_6" data-reaction="HaHa" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'HaHa');">
								<div class="emoji emoji--haha">
									<div class="emoji__face">
										<div class="emoji__eyes"></div>
										<div class="emoji__mouth">
											<div class="emoji__tongue"></div>
										</div>
									</div>
								</div>
							</li>
		                    <li class="reaction reaction-wow animated_8" data-reaction="Wow" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Wow');">
								<div class="emoji emoji--wow">
									<div class="emoji__face">
										<div class="emoji__eyebrows"></div>
										<div class="emoji__eyes"></div>
										<div class="emoji__mouth"></div>
									</div>
								</div>
							</li>
		                    <li class="reaction reaction-sad animated_10" data-reaction="Sad" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Sad');">
								<div class="emoji emoji--sad">
									<div class="emoji__face">
										<div class="emoji__eyebrows"></div>
										<div class="emoji__eyes"></div>
										<div class="emoji__mouth"></div>
									</div>
								</div>
							</li>
		                    <li class="reaction reaction-angry animated_12" data-reaction="Angry" onclick="Wo_RegisterBlogReplyReaction(<?php echo $wo['comm-reply']['user_id']; ?>,<?php echo $wo['comm-reply']['id']; ?>,'Angry');">
								<div class="emoji emoji--angry">
									<div class="emoji__face">
										<div class="emoji__eyebrows"></div>
										<div class="emoji__eyes"></div>
										<div class="emoji__mouth"></div>
									</div>
								</div>
							</li> -->
		                </ul>
		            </div>
		            <?php }else{ ?>


					<span class="pointer add-blog-commreply-likes-<?php echo $wo['comm-reply']['id']; ?>" onclick="Wo_AddBlogCommReplyLike(<?php echo $wo['comm-reply']['id']; ?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg>
					</span> 
					<span id="blog-comment-likes" data-blog-comrlikes="<?php echo $wo['comm-reply']['id']; ?>">
						<?php if ($wo['comm-reply']['likes'] > 0): ?>
							<?php echo $wo['comm-reply']['likes']; ?>
						<?php endif ?>
					</span> 
					&nbsp;
					<span class="pointer add-blog-commreply-dislikes-<?php echo $wo['comm-reply']['id']; ?>" onclick="Wo_AddBlogCommReplyDisLike(<?php echo $wo['comm-reply']['id']; ?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-down"><path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17"></path></svg>
					</span> 
					<span id="blog-comment-likes" data-blog-comrdislikes="<?php echo $wo['comm-reply']['id']; ?>">
						<?php if ($wo['comm-reply']['dislikes'] > 0): ?>
							<?php echo $wo['comm-reply']['dislikes']; ?>
						<?php endif ?>
					</span> 
				<?php } ?>
			</span>
		</div>
	</div>
</div>