<div class="blog-sidebar">
	<div class="wo_page_hdng">
		<div class="wo_page_hdng_innr">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M4 7V19H19V21H4C2 21 2 19 2 19V7H4M23 3V15C23 15 23 17 21 17H8C8 17 6 17 6 15V3H23M21 5H8V15H21V5M14 7H10V12H14V7M19 7H15V9H19V7M19 10H15V12H19V10Z"></path></svg></span> <?php echo $wo['lang']['read_more'];?>
		</div>
	</div>
	<div class="row">
	<?php 
		$blogs = Wo_GetBlogs(array('limit' => 3, 'order_by' => 'RAND', 'id' => $wo['article']['id']));
		foreach ($blogs as $key => $wo['blog-style']) {
			echo Wo_LoadPage('blog/blog-recom');
		}
	?>
	</div>
</div>