<div class="page-margin">
	<div class="wow_main_float_head contactus">
		<div class="container">
			<h1><?php echo $wo['lang']['refund']; ?></h1>
			<p class="text-center" style="margin: 15px 0 0;"><a class="btn btn-default btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=refund');?>" data-ajax="?link1=refund"><?php echo $wo['lang']['request_refund']; ?></a></p>
		</div>
	</div>
	
	<div class="wow_main_blogs_bg"></div>
	
	<div class="wow_content wo_terms_page">
		<div class="setting-well">
			<?php echo $wo['lang']['refund_terms_page'];?>
		</div>
	</div>
</div>

<script>
$('.wow_main_blogs_bg').css('height', ($('.wow_main_float_head').height()) + 'px');
</script>