<div class="container-fluid">
    <div>
        <h3>Mobile & Verify Applications</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">API Settings</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Mobile & Verify Applications</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
    	 <div class="col-md-12">
        	<div class="card">
                <div class="card-body">
                    <h6 class="card-title">Use The Applications</h6>
                    <div>If you use one of those products listed below, you need to verify them before you can use them.</div><br>
					<div class="row">
						<div class="col-md-3">
							<div class="admin-apps-card">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#03a9f4" d="M3,12V6.75L9,5.43V11.91L3,12M20,3V11.75L10,11.9V5.21L20,3M3,13L9,13.09V19.9L3,18.75V13M20,13.25V22L10,20.09V13.1L20,13.25Z" /></svg>
								<h3><a href="http://www.wowonder.com/windows_app.php">Native Windows Messenger</a></h3>
								<a href="http://www.wowonder.com/windows_app.php" class="btn btn-outline-primary">Get Here</a>
							</div>
						</div>
						<div class="col-md-3">
							<div class="admin-apps-card">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4caf50" d="M16.61 15.15C16.15 15.15 15.77 14.78 15.77 14.32S16.15 13.5 16.61 13.5H16.61C17.07 13.5 17.45 13.86 17.45 14.32C17.45 14.78 17.07 15.15 16.61 15.15M7.41 15.15C6.95 15.15 6.57 14.78 6.57 14.32C6.57 13.86 6.95 13.5 7.41 13.5H7.41C7.87 13.5 8.24 13.86 8.24 14.32C8.24 14.78 7.87 15.15 7.41 15.15M16.91 10.14L18.58 7.26C18.67 7.09 18.61 6.88 18.45 6.79C18.28 6.69 18.07 6.75 18 6.92L16.29 9.83C14.95 9.22 13.5 8.9 12 8.91C10.47 8.91 9 9.24 7.73 9.82L6.04 6.91C5.95 6.74 5.74 6.68 5.57 6.78C5.4 6.87 5.35 7.08 5.44 7.25L7.1 10.13C4.25 11.69 2.29 14.58 2 18H22C21.72 14.59 19.77 11.7 16.91 10.14H16.91Z" /></svg>
								<h3><a href="http://www.wowonder.com/windows_app.php?app=android">Native Android Messenger</a></h3>
								<a href="http://www.wowonder.com/windows_app.php?app=android" class="btn btn-outline-primary">Get Here</a>
							</div>
						</div>
						<div class="col-md-3">
							<div class="admin-apps-card">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#607d8b" d="M18.71,19.5C17.88,20.74 17,21.95 15.66,21.97C14.32,22 13.89,21.18 12.37,21.18C10.84,21.18 10.37,21.95 9.1,22C7.79,22.05 6.8,20.68 5.96,19.47C4.25,17 2.94,12.45 4.7,9.39C5.57,7.87 7.13,6.91 8.82,6.88C10.1,6.86 11.32,7.75 12.11,7.75C12.89,7.75 14.37,6.68 15.92,6.84C16.57,6.87 18.39,7.1 19.56,8.82C19.47,8.88 17.39,10.1 17.41,12.63C17.44,15.65 20.06,16.66 20.09,16.67C20.06,16.74 19.67,18.11 18.71,19.5M13,3.5C13.73,2.67 14.94,2.04 15.94,2C16.07,3.17 15.6,4.35 14.9,5.19C14.21,6.04 13.07,6.7 11.95,6.61C11.8,5.46 12.36,4.26 13,3.5Z" /></svg>
								<h3><a href="http://www.wowonder.com/windows_app.php?app=ios">Native iOS Messenger</a></h3>
								<a href="http://www.wowonder.com/windows_app.php?app=ios" class="btn btn-outline-primary">Get Here</a>
							</div>
						</div>
						<div class="col-md-3">
							<div class="admin-apps-card">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4caf50" d="M16.61 15.15C16.15 15.15 15.77 14.78 15.77 14.32S16.15 13.5 16.61 13.5H16.61C17.07 13.5 17.45 13.86 17.45 14.32C17.45 14.78 17.07 15.15 16.61 15.15M7.41 15.15C6.95 15.15 6.57 14.78 6.57 14.32C6.57 13.86 6.95 13.5 7.41 13.5H7.41C7.87 13.5 8.24 13.86 8.24 14.32C8.24 14.78 7.87 15.15 7.41 15.15M16.91 10.14L18.58 7.26C18.67 7.09 18.61 6.88 18.45 6.79C18.28 6.69 18.07 6.75 18 6.92L16.29 9.83C14.95 9.22 13.5 8.9 12 8.91C10.47 8.91 9 9.24 7.73 9.82L6.04 6.91C5.95 6.74 5.74 6.68 5.57 6.78C5.4 6.87 5.35 7.08 5.44 7.25L7.1 10.13C4.25 11.69 2.29 14.58 2 18H22C21.72 14.59 19.77 11.7 16.91 10.14H16.91Z" /></svg>
								<h3><a href="http://www.wowonder.com/windows_app.php?app=native_android">Native Android Timeline</a></h3>
								<a href="http://www.wowonder.com/windows_app.php?app=native_android" class="btn btn-outline-primary">Get Here</a>
							</div>
						</div>
					</div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Verify Android Messenger</h6>
                    <div class="android_purchase_code_alert"></div>
                    <form class="form_android_purchase_code" method="POST">
                    	<?php if ($wo['decode_android_v'] != $wo['decode_android_value']): ?>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Android Messenger Verification Code</label>
                                <input type="text" id="android_purchase_code" name="android_purchase_code" class="form-control">
                            </div>
                        </div>
                        <a href="https://api.envato.com/authorization?response_type=code&client_id=wowonder-verification-78ngohfi&redirect_uri=http://www.wowonder.com/purchase_android_app.php?checked=true" target="_blank">Get Verification Code</a><div class="clearfix"></div><br>
                        <button type="button" class="btn btn-primary m-t-15 waves-effect" onclick="Wo_Verify('android_purchase_code')">Verify</button>
                        <?php else: ?>
                        <div><i class="fa fa-check"></i> Application Verified</div>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Verify IOS Messenger</h6>
                    <div class="ios_purchase_code_alert"></div>
                    <form class="form_ios_purchase_code" method="POST">
                    	<?php if ($wo['decode_ios_v'] != $wo['decode_ios_value']): ?>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">IOS Messenger Verification Code</label>
                                <input type="text" id="ios_purchase_code" name="ios_purchase_code" class="form-control">
                            </div>
                        </div>
                        <a href="https://api.envato.com/authorization?response_type=code&client_id=wowonder-ios-u2dki0b1&redirect_uri=http://www.wowonder.com/purchase_ios_app.php?checked=true" target="_blank">Get Verification Code</a><div class="clearfix"></div><br>
                        <button type="button" class="btn btn-primary m-t-15 waves-effect" onclick="Wo_Verify('ios_purchase_code')">Verify</button>
                        <?php else: ?>
                        <div><i class="fa fa-check"></i> Application Verified</div>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Windows Desktop Messenger</h6>
                    <div class="windows_purchase_code_alert"></div>
                    <form class="form_windows_purchase_code" method="POST">
                    	<?php if ($wo['decode_windwos_v'] != $wo['decode_windwos_value']): ?>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Windows Desktop Verification Code</label>
                                <input type="text" id="windows_purchase_code" name="windows_purchase_code" class="form-control">
                            </div>
                        </div>
                        <a href="https://api.envato.com/authorization?response_type=code&client_id=wowonder-windows-rdp0492u&redirect_uri=http://www.wowonder.com/purchase_windows_app.php?checked=true" target="_blank">Get Verification Code</a><div class="clearfix"></div><br>
                        <button type="button" class="btn btn-primary m-t-15 waves-effect" onclick="Wo_Verify('windows_purchase_code')">Verify</button>
                        <?php else: ?>
                        <div><i class="fa fa-check"></i> Application Verified</div>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Android Timeline Application</h6>
                    <div class="android_native_purchase_code_alert"></div>
                    <form class="form_android_native_purchase_code" method="POST">
                    	<?php if ($wo['decode_android_n_v'] != $wo['decode_android_n_value']): ?>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Android Timeline Verification Code</label>
                                <input type="text" id="android_native_purchase_code" name="android_native_purchase_code" class="form-control">
                            </div>
                        </div>
                        <a href="https://api.envato.com/authorization?response_type=code&client_id=android-timeline-kssuxhdu&redirect_uri=http://www.wowonder.com/purchase_android_native_app.php?checked=true" target="_blank">Get Verification Code</a><div class="clearfix"></div><br>
                        <button type="button" class="btn btn-primary m-t-15 waves-effect" onclick="Wo_Verify('android_native_purchase_code')">Verify</button>
                        <?php else: ?>
                        <div><i class="fa fa-check"></i> Application Verified</div>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

function Wo_Verify(type) {
	var code = $('#' + type).val();
	if (!code) {
        $('.'+type+'_alert').html('<div class="alert alert-danger">Verification code is required</div>');
        setTimeout(function () {
            $('.'+type+'_alert').empty();
        }, 2000);
		return false;
	}
	var form = $('.form_' + type);
	form.find('button').text('Please wait..');
	data = {};
	data[type] = code;
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=verfiy_apps', data, function (data) {
        if (data.android_status == 200) {
           form.html('<div><i class="fa fa-check"></i> Application Verified</div>');
        } else if (data.android_status == 400) {
            $('.'+type+'_alert').html('<div class="alert alert-danger">'+data.android_text+'</div>');
            setTimeout(function () {
                $('.'+type+'_alert').empty();
            }, 2000);
        }

        if (data.ios_status == 200) {
           form.html('<div><i class="fa fa-check"></i> Application Verified</div>');
        } else if (data.ios_status == 400) {
            $('.'+type+'_alert').html('<div class="alert alert-danger">'+data.ios_text+'</div>');
            setTimeout(function () {
                $('.'+type+'_alert').empty();
            }, 2000);
        }

        if (data.windows_status == 200) {
           form.html('<div><i class="fa fa-check"></i> Application Verified</div>');
        } else if (data.windows_status == 400) {
            $('.'+type+'_alert').html('<div class="alert alert-danger">'+data.windows_text+'</div>');
            setTimeout(function () {
                $('.'+type+'_alert').empty();
            }, 2000);
        }

        if (data.android_native_status == 200) {
           form.html('<div><i class="fa fa-check"></i> Application Verified</div>');
        } else if (data.android_native_status == 400) {
            $('.'+type+'_alert').html('<div class="alert alert-danger">'+data.android_text+'</div>');
            setTimeout(function () {
                $('.'+type+'_alert').empty();
            }, 2000);
        }

    	form.find('button').text('Verify');
    });
}
</script>