<?php if ($wo['config']['credit_card'] == 'yes') { ?>
<script src="https://js.stripe.com/v3/"></script>
<?php } ?>
<?php if ($wo['config']['securionpay_payment'] == '1') { ?>
    <script src="https://securionpay.com/checkout.js"></script>
<?php } ?>
<?php $loadPage = Wo_LoadPage('thirdparty/paypal-demo'); echo (!empty($loadPage)) ? $loadPage : '';?>
<div class="row">
	<div class="col-md-12">
		<div class="list-group wo_ads_wallet page-margin">
			<?php if (isset($wo['replenishment_notif'])): ?>
				<div class="col-md-12" id="replenish-user-account-alert">
					<div class="alert alert-success">
						<i class="fa fa-check" aria-hidden="true"></i>
						<?php echo $wo['replenishment_notif'];?>
					</div>
				</div>
			<?php endif; ?>
			<div class="col-md-12">
				<div class="alert alert-danger hidden please-check"><?php echo $wo['lang']['please_check_details'];?></div>
			</div>
			<div class="col-md-12" id="replenish-user-account-alert-warning"></div>
			<div class="row ml0 mr0">
				<div class="col-sm-6 col-md-6 my_wallet text-center">
					<div class="form-group w100">
						<svg xmlns="http://www.w3.org/2000/svg" class="feather feather-wallet" width="24" height="24" viewBox="0 0 24 24" fill="#77442B"><path d="M21,18V19A2,2 0 0,1 19,21H5C3.89,21 3,20.1 3,19V5A2,2 0 0,1 5,3H19A2,2 0 0,1 21,5V6H12C10.89,6 10,6.9 10,8V16A2,2 0 0,0 12,18M12,16H22V8H12M16,13.5A1.5,1.5 0 0,1 14.5,12A1.5,1.5 0 0,1 16,10.5A1.5,1.5 0 0,1 17.5,12A1.5,1.5 0 0,1 16,13.5Z" /></svg>
						<div class="col-md-12">
							<label class="col-md-12 bold"><?php echo $wo['lang']['my_balance'];?></label>
							<h5>
								<span><?php echo Wo_GetCurrency($wo['config']['ads_currency']); ?></span>
								<b><?php echo sprintf('%.2f',$wo['user']['wallet']);?></b>
							</h5>
						</div>
					</div>
					<div class="w100">
						<label class="col-md-12"></label>
						<div class="col-md-12">
							<button data-toggle="modal" data-target="#send_money_modal" class="btn btn-default">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-gift"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg> <?php echo $wo['lang']['send_money'];?></button>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 text-center">
					<form class="form" id="replenish-user-account">
						<svg xmlns="http://www.w3.org/2000/svg" class="feather feather-wallet" width="24" height="24" viewBox="0 0 24 24"><path fill="#3f51b5" d="M5,6H23V18H5V6M14,9A3,3 0 0,1 17,12A3,3 0 0,1 14,15A3,3 0 0,1 11,12A3,3 0 0,1 14,9M9,8A2,2 0 0,1 7,10V14A2,2 0 0,1 9,16H19A2,2 0 0,1 21,14V10A2,2 0 0,1 19,8H9M1,10H3V20H19V22H1V10Z"/></svg>
						<div class="w100">
							<label class="col-md-12 bold"><?php echo $wo['lang']['replenish_my_balance'];?></label>
						</div>
						<div class="form-group w100 add-amount">
							<h5>
								<span><?php echo Wo_GetCurrency($wo['config']['ads_currency']); ?></span>
								<b><input type="number" placeholder="0.00" min="1.00"  name="amount" id="amount" /></b>
							</h5>
						</div>
						<div class="w100">
							<label class="col-md-12"></label>
							<div class="col-md-12">
								<div class="ball-pulse"><div></div><div></div><div></div></div>
								<button type="submit" class="btn btn-main">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg> <?php echo $wo['lang']['continue'];?>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>

			<?php
				$wo['trans'] = Wo_GetMytransactions();
			?>
			<div class="wallet_transactions">
				<h3>
					<?php echo $wo['lang']['transaction_log']; ?>
					<?php if ($wo['config']['affiliate_system'] == 1 || $wo['config']['point_allow_withdrawal'] == 1 || $wo['config']['funding_system'] == 1 || $wo['config']['store_system'] == 'on') { ?>
						<a href="<?php echo Wo_SeoLink('index.php?link1=setting&page=payments');?>" data-ajax="?link1=setting&page=payments" class="btn btn-sm btn-main"><?php echo($wo['lang']['withdrawal']) ?></a>
					<?php } ?>
				</h3>
				<div class="tabbable">
					<?php echo Wo_LoadPage('ads/includes/latest_activities');?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo Wo_LoadPage('ads/send_money'); ?>
<div id="pay-modal"></div>
<style type="text/css">
	input::-webkit-outer-spin-button,
	input::-webkit-inner-spin-button {
	    /* display: none; <- Crashes Chrome on hover */
	    -webkit-appearance: none;
	    margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
	}
</style>
<div class="modal fade sun_modal" id="paystack_wallet_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['paystack'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="paystack_wallet_form" action="#">
				<div class="modal-body twocheckout_modal">
					<div id="paystack_wallet_alert"></div>
					<div class="clear"></div>
					<div class="sun_input col-md-12">
						<input id="paystack_wallet_email" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['email']; ?>" value="<?php echo($wo['user']['email']) ?>">
						<label class="plr15" for="paystack_wallet_email"><?php echo $wo['lang']['email']; ?></label>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="button" class="btn btn-main" id="paystack_btn" onclick="InitializeWalletPaystack()"><?php echo $wo['lang']['pay']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal fade sun_modal" id="cashfree_wallet_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['cashfree'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="cashfree_form" action="#">
				<div class="modal-body twocheckout_modal">
					<div id="cashfree_wallet_alert"></div>
					<div class="clear"></div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="cashfree_name"><?php echo $wo['lang']['name']; ?></label>
						<input id="cashfree_name" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['name']; ?>" value="<?php echo($wo['user']['name']) ?>">

					</div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="cashfree_email"><?php echo $wo['lang']['email']; ?></label>
						<input id="cashfree_email" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['email']; ?>" value="<?php echo($wo['user']['email']) ?>">

					</div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="cashfree_phone"><?php echo $wo['lang']['phone_number']; ?></label>
						<input id="cashfree_phone" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['phone_number']; ?>" value="<?php echo($wo['user']['phone_number']) ?>">

					</div>
					<input type="hidden" name="cashfree_type" id="cashfree_type">
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="button" class="btn btn-main" id="cashfree_btn" onclick="SignatureWalletCashfree()"><?php echo $wo['lang']['pay']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>
<?php if ($wo['config']['razorpay_payment'] == 'yes' && !empty($wo['config']['razorpay_key_id']) && !empty($wo['config']['razorpay_key_secret'])) { ?>
<div class="modal fade sun_modal" id="razorpay_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['razorpay'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="razorpay_form" action="#">
				<div class="modal-body twocheckout_modal">
					<div id="razorpay_alert"></div>
					<div class="clear"></div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="razorpay_name"><?php echo $wo['lang']['name']; ?></label>
						<input id="razorpay_name" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['name']; ?>" value="<?php echo($wo['user']['name']) ?>">
					</div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="razorpay_email"><?php echo $wo['lang']['email']; ?></label>
						<input id="razorpay_email" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['email']; ?>" value="<?php echo($wo['user']['email']) ?>">
					</div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="razorpay_phone"><?php echo $wo['lang']['phone_number']; ?></label>
						<input id="razorpay_phone" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['phone_number']; ?>" value="<?php echo($wo['user']['phone_number']) ?>">
					</div>
					<input type="hidden" name="razorpay_type" id="razorpay_type">
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="button" class="btn btn-main" id="razorpay_btn" onclick="SignatureRazorpay()"><?php echo $wo['lang']['pay']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<?php } ?>
<?php if ($wo['config']['fluttewave_payment'] == 1) { ?>
<div class="modal fade sun_modal" id="fluttewave_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['fluttewave'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="fluttewave_form" action="#">
				<div class="modal-body twocheckout_modal">
					<div id="fluttewave_alert"></div>
					<div class="clear"></div>
					<div class="sun_input col-md-12">
						<label class="plr15" for="fluttewave_email"><?php echo $wo['lang']['email']; ?></label>
						<input id="fluttewave_email" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['email']; ?>" value="<?php echo($wo['user']['email']) ?>">
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="button" class="btn btn-main" id="fluttewave_btn" onclick="SignatureFluttewave()"><?php echo $wo['lang']['pay']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>
<?php } ?>
<?php if ($wo['config']['aamarpay_payment'] == 1) { ?>
<div class="modal fade sun_modal" id="aamarpay_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content add_money_modal add_address_modal">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['aamarpay'] ?></h4>
			</div>

            <div class="modal-body">
                <div id="aamarpay_alert" style="    color: red;"></div>
                <form id="aamarpay_form" method="post">
                    <div class="sun_input col-md-12">
						<label class="plr15" for="aamarpay_name"><?php echo $wo['lang']['name']; ?></label>
                        <input class="form-control input-md" type="text" placeholder="<?php echo $wo['lang']['name']; ?>"  value="<?php echo($wo['user']['name']) ?>" id="aamarpay_name">
                    </div>
                    <div class="sun_input col-md-12">
						<label class="plr15" for="aamarpay_email"><?php echo $wo['lang']['email']; ?></label>
                        <input class="form-control input-md" type="email" placeholder="<?php echo $wo['lang']['email']; ?>" value="<?php echo($wo['user']['email']) ?>" id="aamarpay_email">
                    </div>
                    <div class="sun_input col-md-12">
						<label class="plr15" for="aamarpay_number"><?php echo $wo['lang']['phone_number']; ?></label>
                        <input id="aamarpay_number" class="form-control input-md" type="text" placeholder="<?php echo $wo['lang']['phone_number']; ?>" value="<?php echo($wo['user']['phone_number']) ?>">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-main" onclick="AamarpayRequest()" id="aamarpay_button"><?php echo $wo['lang']['pay']; ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php } ?>
<script>
<?php if ($wo['config']['ngenius_payment'] == '1') { ?>
	function pay_using_ngenius() {
		amount = $("#amount").val();
		$.post(Wo_Ajax_Requests_File() + '?f=ngenius&s=pay',{amount:amount}, function (data) {
	        if (data.status == 200) {
	        	location.href = data.url;
	        }
	        else{
	        	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
				setTimeout(function () {
					$('.pay-go-pro-alert').html("");
				},3000);
	        }
	    }).fail(function(data) {
	    	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
			setTimeout(function () {
				$('.pay-go-pro-alert').html("");
			},3000);
		});
	}
<?php } ?>
<?php if ($wo['config']['aamarpay_payment'] == '1') { ?>
	function pay_using_aamarpay() {
		$('#pay-go-pro').modal('hide');
		$('#aamarpay_modal').modal({
             show: true
            });
	}
	function AamarpayRequest() {
		$('#aamarpay_button').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
		amount = $("#amount").val();
		$.post(Wo_Ajax_Requests_File() + '?f=aamarpay&s=pay',{amount:amount,name:$('#aamarpay_name').val(),email:$('#aamarpay_email').val(),phone:$('#aamarpay_number').val()}, function (data) {
			$('#aamarpay_button').removeAttr('disabled');
	        $('#aamarpay_button').text("<?php echo($wo['lang']['pay']) ?>");
	        if (data.status == 200) {
	        	location.href = data.url;
	        }
	    }).fail(function(data) {
		});

	}
<?php } ?>
<?php if ($wo['config']['fortumo_payment'] == '1') { ?>
	function pay_using_fortumo() {
		$.post(Wo_Ajax_Requests_File() + '?f=fortumo&s=pay', function (data) {
	        if (data.status == 200) {
	        	location.href = data.url;
	        }
	    }).fail(function(data) {
		});
	}
<?php } ?>
<?php if ($wo['config']['fluttewave_payment'] == 1) { ?>
	function open_fluttewave() {
		$('#pay-go-pro').modal('hide');
		$('#fluttewave_modal').modal({
	        show: true
	    });
	}
	function SignatureFluttewave() {
		$('#fluttewave_btn').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
		amount = $('#amount').val();
		email = $('#fluttewave_email').val();
	    $.post(Wo_Ajax_Requests_File() + '?f=fluttewave&s=pay', {amount:amount,email:email}, function(data) {
	    	$('#fluttewave_btn').html("<?php echo($wo['lang']['pay']) ?>");
		    $('#fluttewave_btn').removeAttr('disabled');
	        if (data.status == 200) {
	            window.location.href = data.url;
	        } else {
	         	$('#fluttewave_alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
				setTimeout(function () {
					$('#fluttewave_alert').html("");
				},3000);
	        }
	    });
	}
<?php } ?>
<?php if ($wo['config']['razorpay_payment'] == 'yes' && !empty($wo['config']['razorpay_key_id']) && !empty($wo['config']['razorpay_key_secret'])) { ?>
function pay_using_razorpay(type) {
	$("#razorpay_alert").html('');
	$('#razorpay_type').val(type)
	$('#pay-go-pro').modal('hide');
	$('#razorpay_modal').modal({
        show: true
    });
}

function SignatureRazorpay() {
	$('#razorpay_btn').html("<?php echo($wo['lang']['please_wait']) ?>");
	$('#razorpay_btn').attr('disabled','true');
    var merchant_order_id = "<?php echo(round(111111,9999999)) ?>";
    var card_holder_name_id = $('#razorpay_name').val();
    var type = $('#razorpay_type').val();
    var email = $('#razorpay_email').val();
    var phone = $('#razorpay_phone').val();
    //var currency_code_id = "<?php echo($wo['config']['currency']) ?>";
    var currency_code_id = "INR";

    if (!email || !phone || !card_holder_name_id) {
    	$('#razorpay_alert').html("<div class='alert alert-danger'><?php echo($wo['lang']['please_check_details']) ?></div>");
		setTimeout(function () {
			$('#razorpay_alert').html("");
		},3000);
		$('#razorpay_btn').html("<?php echo($wo['lang']['pay']) ?>");
		$('#razorpay_btn').removeAttr('disabled');
		return false;
    }


    var merchant_total = Number($('#amount').val()) * 100;

    var razorpay_options = {
        key: "<?php echo $wo['config']['razorpay_key_id']; ?>",
        amount: merchant_total,
        name: "<?php echo $wo['config']['siteName']; ?>",
        description: "Top up wallet",
        image: '<?php echo $wo['config']['theme_url'];?>/img/logo.<?php echo $wo['config']['logo_extension'];?>',
        netbanking: true,
        currency: currency_code_id,
        prefill: {
            name: card_holder_name_id,
            email: email,
            contact: phone
        },
        notes: {
            soolegal_order_id: merchant_order_id,
        },
        handler: function (transaction) {
            jQuery.ajax({
                url:Wo_Ajax_Requests_File() + '?f=razorpay&s=wallet',
                type: 'post',
                data: {payment_id: transaction.razorpay_payment_id, order_id: merchant_order_id, card_holder_name_id: card_holder_name_id,  merchant_amount: merchant_total, currency: currency_code_id, type: 'wallet'},
                dataType: 'json',
                success: function (data) {
                	if (data.status == 200) {
                		window.location = data.url;
                	}
                	else{
                		if (data.url != '') {
                			window.location = data.url;
                		}
                		else{
                			$('#razorpay_alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
							setTimeout(function () {
								$('#razorpay_alert').html("");
							},3000);
							$('#razorpay_btn').html("<?php echo($wo['lang']['pay']) ?>");
							$('#razorpay_btn').removeAttr('disabled');

                		}
                	}
                }
            });
        },
        "modal": {
            "ondismiss": function () {
                // code here
            }
        }
    };
    // obj
    var objrzpv1 = new Razorpay(razorpay_options);
    objrzpv1.open();
    e.preventDefault();
}
<?php } ?>
<?php if ($wo['config']['paysera_payment'] == 'yes' && !empty($wo['config']['paysera_project_id']) && !empty($wo['config']['paysera_sign_password'])) { ?>
	function pay_using_paysera(type) {
		$('.btn-paysera').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
		amount = $('#amount').val();
	    $.post(Wo_Ajax_Requests_File() + '?f=paysera&s=get_url', {type:'wallet',amount:amount}, function(data) {
	        if (data.status == 200) {
	            window.location.href = data.url;
	        } else {
	         	$('.btn-paysera').attr('disabled', false).html("Paysera App not set yet.");
	        }
	    });
	}
<?php } ?>

	function pay_using_cashfree(type) {
		$("#cashfree_wallet_alert").html('');
		$('#pay-go-pro').modal('hide');
		$('#cashfree_wallet_modal').modal({
	        show: true
	    });
	}
	function SignatureWalletCashfree() {
		$('#cashfree_btn').html("<?php echo($wo['lang']['please_wait']) ?>");
		$('#cashfree_btn').attr('disabled','true');
		type = $('#cashfree_type').val();
		email = $('#cashfree_email').val();
		name = $('#cashfree_name').val();
		phone = $('#cashfree_phone').val();
		amount = $('#amount').val();
		$.post(Wo_Ajax_Requests_File() + '?f=cashfree&s=initialize', {type:'wallet',email:email,name:name,phone:phone,amount:amount}, function(data) {
			if (data.status == 200) {
				$('body').append(data.html);
				document.getElementById("redirectForm").submit();
			} else {
				$('#cashfree_wallet_alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
				setTimeout(function () {
					$('#cashfree_wallet_alert').html("");
				},3000);
			}
			$('#cashfree_btn').html("<?php echo($wo['lang']['pay']) ?>");
			$('#cashfree_btn').removeAttr('disabled');
		});
	}

	function pay_using_paystack(type) {
		$("#paystack_wallet_alert").html('');
		$('#pay-go-pro').modal('hide');
		$('#paystack_wallet_modal').modal({
	        show: true
	    });
	}

	function InitializeWalletPaystack() {
		$('#paystack_btn').html("<?php echo($wo['lang']['please_wait']) ?>");
	    $('#paystack_btn').attr('disabled','true');
		email = $('#paystack_wallet_email').val();
		amount = $('#amount').val();
		$.post(Wo_Ajax_Requests_File() + '?f=paystack&s=initialize', {type:'wallet',email:email,amount:amount}, function(data) {
			if (data.status == 200) {
				window.location.href = data.url;
			} else {
				$('#paystack_wallet_alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
				setTimeout(function () {
					$('#paystack_wallet_alert').html("");
				},3000);
			}
			$('#paystack_btn').html("<?php echo($wo['lang']['pay']) ?>");
		    $('#paystack_btn').removeAttr('disabled');
		});
	}



	function Wo_GetPayPalLink(type) {
		$('.btn-paypal').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
		$.get(Wo_Ajax_Requests_File() + '?f=wallet&s=replenish-user-account', {amount:$('#amount').val(), desc: '<?php echo $wo['lang']['replenish_my_balance'];?>'}, function(data) {
			if (data.status == 200) {
				window.location.href = data.url;
			} else {
				$('.btn-paypal').attr('disabled', false).html("PayPal App not set yet.");
			}
		});
	}
	function Wo_CheckOutCard(type, description, amount, payment_type) {
		description = "Wallet replenishment";
		amount = $('#amount').val() * 100;

		if (payment_type == 'bitcoin') {
			$('.btn-bitcoin').attr('disabled', true).text("<?php echo $wo["lang"]["please_wait"]?>");
			$('#pay-go-pro').modal({
				show: false
			});
		} else if (payment_type == 'credit_card') {
			$('.btn-cart').attr('disabled', true);
		} else if (payment_type == 'alipay') {
			$('.btn-alipay').attr('disabled', true);
		}
		var img = 'star';
		if (type == 1) {
			img = 'star';
		} else if (type == 2) {
			img = 'hot';
		} else if (type == 3) {
			img = 'ultima';
		} else if (type == 4) {
			img = 'vip';
		}
		if (payment_type != 'bank_payment' && payment_type != 'checkout' && payment_type != 'bitcoin') {
			var stripe = Stripe('<?php echo $wo['config']['stripe_id'];?>');
			$.post(Wo_Ajax_Requests_File() + '?f=stripe&s=session', {amount: $('#amount').val(),type:'wallet',payment_type:payment_type}, function(data, textStatus, xhr) {
				if (data.status == 200) {
					return stripe.redirectToCheckout({ sessionId: data.sessionId });
				}
				else{
			    	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
					setTimeout(function () {
						$('.pay-go-pro-alert').html("");
					},3000);
			    }
			    if (payment_type == 'credit_card') {
			    	$('.btn-cart').removeAttr('disabled');
			    }
			    if (payment_type == 'alipay') {
				    $('.btn-alipay').removeAttr('disabled');
				}
			});
		}
		if (payment_type == 'bitcoin') {
			if( $('#amount').val() <= 0 ){
				$('#pay-go-pro').modal('hide');
				alert('You must enter value greater than ZERO');
				return false;
			}else{
				$.get(Wo_Ajax_Requests_File() + '?f=pay_with_bitcoin&s=pay&amount=' + $('#amount').val(), function (data) {
					if (data.status == 200) {
						$(data.html).appendTo('body').submit();
					}
					else{
			        	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.message+"</div>");
						setTimeout(function () {
							$('.pay-go-pro-alert').html("");
						},3000);
			        }
				});
			}

		} else if (payment_type == 'bank_payment') {
	    	$('#configreset').click();
	    	$(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $wo['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $wo['lang']['or']; ?></span><p><?php echo $wo['lang']['browse_to_upload']; ?></p></div></div> </div>');
			$("#blog-alert").html('');
	    	$('#bank_transfer_des').val('Add to balance');
	    	$('#bank_transfer_price').val($('#amount').val());
	    	$('#pay-go-pro').modal('hide');
	    	$('#bank_transfer_modal').modal({
	             show: true
	            });


		} else if (payment_type == 'checkout') {
			$("#2checkout_alert_wallet").html('');
			$('#pay-go-pro').modal('hide');
	    	$('#2checkout_wallet_modal').modal({
	            show: true
	        });
		}
		$(window).on('popstate', function() {
		handler.close();
		});
	}

	jQuery(document).ready(function($) {

		$("#replenish-user-account").submit(function(e) {
			e.preventDefault();
			var string = $('#amount').val();
			if (string.indexOf(',') > -1 || string < 0 || string == 0) {

				$('.please-check').removeClass("hidden");
				return false;
			}
			$('.please-check').addClass("hidden");
			var type = 1;
			$.get(Wo_Ajax_Requests_File() + '?f=get_payment_method&type=' + type, function (data) {
				if (data.status == 200) {
					$('#pay-modal').html(data.html);
					$('#pay-go-pro').modal({
						show: true
					});
				}
			});
		});

		$('#bank_transfer_form_wallet').ajaxForm({
		  url: Wo_Ajax_Requests_File() + '?f=bank_transfer_wallet',
		  beforeSend: function() {
	    $('#bank_transfer_form_wallet').find('.ball-pulse').fadeIn(100);
	  },
	  success: function(data) {
	    if (data['status'] == 200) {
	    	$("#blog-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	    	setTimeout(function () {
	    		window.location = "<?php echo $wo['config']['site_url'];?>";
	    		$(".prv-img").html('<div class="thumbnail-rendderer"><div><h4 class="bold"><?php echo $wo['lang']['drop_img_here']; ?></h4><div class="error-text-renderer"></div><div><span><?php echo $wo['lang']['or']; ?></span><p><?php echo $wo['lang']['browse_to_upload']; ?></p></div></div> </div>');
	    		$("#blog-alert").html('');
	    		$('#configreset').click();

	    	},3000)
	    } else if (data['message']) {
	      $("#blog-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	    }
	    $('#bank_transfer_form_wallet').find('.ball-pulse').fadeOut(100);
		}});



	});

	// $(document).on('click', '#select-img', function(event) {
	// 	$("#thumbnail").click()
	// });
	// $(document).on('change', '#thumbnail', function(event) {
	// 	$(".prv-img").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
	// });
$(document).on('change', '#upload', function(event) {
	let imgPath = $(this)[0].files[0].name;
    if (typeof(FileReader) != "undefined") {
        let reader = new FileReader();
        reader.onload = function(e) {
			$('#receipt_img_preview').attr('src', e.target.result);
        }
        reader.readAsDataURL(this.files[0]);
    }
	$('#bank_transfer_modal').addClass('up_rec_img_ready');
});



// Called when token created successfully.
var successCallback = function(data) {
    var myForm = document.getElementById('2checkout_form_wallet');
    $.post(Wo_Ajax_Requests_File() + '?f=2checkout_wallet', {card_number: $("#card_number").val(),card_cvc: $("#card_cvc").val(),card_month: $("#card_month").val(),card_year: $("#card_year").val(),card_name: $("#card_name").val(),card_address: $("#card_address").val(),card_city: $("#card_city").val(),card_state: $("#card_state").val(),card_zip: $("#card_zip").val(),card_country: $("#card_country").val(),card_email: $("#card_email").val(),card_phone: $("#card_phone").val(),amount: $('#amount').val(),token: data.response.token.token}, function(data, textStatus, xhr) {
    	$('#2checkout_btn_wallet').html("<?php echo($wo['lang']['pay']) ?>");
    	$('#2checkout_btn_wallet').attr('disabled');
    	$('#2checkout_btn_wallet').removeAttr('disabled');
    	$('#2checkout_form_wallet').find('.ball-pulse').fadeOut(100);
    	if (data.status == 200) {
      	 	window.location.href = data.location;
      	} else {
      	 	$('#2checkout_alert_wallet').html("<div class='alert alert-danger'>"+data.error+"</div>");
			setTimeout(function () {
				$('#2checkout_alert_wallet').html("");
			},3000);
      	}
    	/*optional stuff to do after success */
    });
};

// Called when token creation fails.
var errorCallback = function(data) {
	$('#2checkout_btn_wallet').html("<?php echo($wo['lang']['pay']) ?>");
	$('#2checkout_btn_wallet').removeAttr('disabled');
	$('#2checkout_form_wallet').find('.ball-pulse').fadeOut(100);
    if (data.errorCode === 200) {
        tokenRequest();
    } else {
    	$('#2checkout_alert_wallet').html("<div class='alert alert-danger'>"+data.errorMsg+"</div>");
		setTimeout(function () {
			$('#2checkout_alert_wallet').html("");
		},3000);
    }
};

var tokenRequest = function() {
	$('#card_number').val($('#_number_').val());
	$('#2checkout_btn_wallet').html("<?php echo($wo['lang']['please_wait']) ?>");
	$('#2checkout_btn_wallet').attr('disabled','true');
	if ($("#card_number").val() != '' && $("#card_cvc").val() != '' && $("#card_month").val() != '' && $("#card_year").val() != '' && $("#card_name").val() != '' && $("#card_address").val() != '' && $("#card_city").val() != '' && $("#card_state").val() != '' && $("#card_zip").val() != '' && $("#card_country").val() != 0 && $("#card_email").val() != '' && $("#card_phone").val() != '') {
		$('#2checkout_form_wallet').find('.ball-pulse').fadeIn(100);
		// Setup token request arguments
	    var args = {
	        sellerId: "<?php echo($wo['config']['checkout_seller_id']) ?>",
	        publishableKey: "<?php echo($wo['config']['checkout_publishable_key']) ?>",
	        ccNo: $("#card_number").val(),
	        cvv: $("#card_cvc").val(),
	        expMonth: $("#card_month").val(),
	        expYear: $("#card_year").val()
	    };

	    // Make the token request
	    TCO.requestToken(successCallback, errorCallback, args);
	}
	else{
		$('#2checkout_btn_wallet').html("<?php echo($wo['lang']['pay']) ?>");
		$('#2checkout_btn_wallet').removeAttr('disabled');
		$('#2checkout_alert_wallet').html("<div class='alert alert-danger'><?php echo($wo['lang']['please_check_details']) ?></div>");
		setTimeout(function () {
			$('#2checkout_alert_wallet').html("");
		},3000);

	}


};

<?php if ($wo['config']['checkout_payment'] == 'yes') { ?>
$(function() {
    // Pull in the public encryption key for our environment
    TCO.loadPubKey("<?php echo($wo['config']['checkout_mode']) ?>");
});
<?php } ?>
<?php if ($wo['config']['coinbase_payment'] == '1' && !empty($wo['config']['coinbase_key'])) { ?>
function pay_using_coinbase() {
    amount = $('#amount').val();
    $.get(Wo_Ajax_Requests_File() + '?f=coinbase&s=create',{amount:amount}, function (data) {
	    if (data.status == 200) {
	    	$('#pay-go-pro').modal('hide');
	        window.location.href = data.url;
	    }
	    else{
	    	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.error+"</div>");
			setTimeout(function () {
				$('.pay-go-pro-alert').html("");
			},3000);
	    }
    });
}
<?php } ?>
<?php if ($wo['config']['yoomoney_payment'] == '1' && !empty($wo['config']['yoomoney_wallet_id']) && !empty($wo['config']['yoomoney_notifications_secret'])) { ?>
function pay_using_yoomoney() {
    amount = $('#amount').val();
    $.get(Wo_Ajax_Requests_File() + '?f=yoomoney&s=create',{amount:amount}, function (data) {
	    if (data.status == 200) {
	    	$('#pay-go-pro').modal('hide');
	    	$('body').append(data.html);
			document.getElementById("yoomoney_form").submit();
			$("#yoomoney_form").remove();
	    }
	    else{
	    	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.error+"</div>");
			setTimeout(function () {
				$('.pay-go-pro-alert').html("");
			},3000);
	    }
    });
}
<?php } ?>
<?php if ($wo['config']['iyzipay_payment'] == '1' && !empty($wo['config']['iyzipay_key']) && !empty($wo['config']['iyzipay_secret_key'])) { ?>
function pay_using_iyzipay() {
    amount = $('#amount').val();
    $.get(Wo_Ajax_Requests_File() + '?f=iyzipay&s=create',{amount:amount}, function (data) {
	    if (data.status == 200) {
	    	$('#pay-go-pro').modal('hide');
	    	$('#iyzipay_content').html('');
			$('#iyzipay_content').html(data.html);
	    }
	    else{
	    	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.error+"</div>");
			setTimeout(function () {
				$('.pay-go-pro-alert').html("");
			},3000);
	    }
    });
}
<?php } ?>
<?php if ($wo['config']['securionpay_payment'] == '1' && !empty($wo['config']['securionpay_public_key']) && !empty($wo['config']['securionpay_secret_key'])) { ?>
$(function () {
    SecurionpayCheckout.key = '<?php echo($wo['config']['securionpay_public_key']); ?>';
    SecurionpayCheckout.success = function (result) {
        $.post(Wo_Ajax_Requests_File() + '?f=securionpay&s=handle', result, function(data, textStatus, xhr) {
            if (data.status == 200) {
                window.location.href = data.url;
            }
        }).fail(function(data) {
                  M.toast({html: data.responseJSON.message});
        });
    };
    SecurionpayCheckout.error = function (errorMessage) {
              M.toast({html: errorMessage});
    };
});
function securionpay_pay(){
	amount = $('#amount').val();
	$.post(Wo_Ajax_Requests_File() + '?f=securionpay&s=create',{amount:amount}, function (data) {
	    if (data.status == 200) {
	    	$('#pay-go-pro').modal('hide');
	    	SecurionpayCheckout.open({
	            checkoutRequest: data.token,
	            name: 'Top Up Wallet',
	            description: 'Top Up Wallet'
            });
	    }
	    else{
	    	$('.pay-go-pro-alert').html("<div class='alert alert-danger'>"+data.error+"</div>");
			setTimeout(function () {
				$('.pay-go-pro-alert').html("");
			},3000);
	    }
    });
}
<?php } ?>
<?php if ($wo['config']['authorize_payment'] == '1' && !empty($wo['config']['authorize_login_id']) && !empty($wo['config']['authorize_transaction_key'])) { ?>
	function open_authorize() {
		$('#pay-go-pro').modal('hide');
		$('#authorize_modal').modal({
	     	show: true
	    });
	}
	function AuthorizeRequest(self) {
	  $('#authorize_btn').html("<?php echo($wo['lang']['please_wait']) ?>");
	  $('#authorize_btn').attr('disabled','true');
	  amount = $('#amount').val();
	  authorize_number = $('#authorize_number').val();
	  authorize_month = $('#authorize_month').val();
	  authorize_year = $('#authorize_year').val();
	  authorize_cvc = $('#authorize_cvc').val();
	  $.post(Wo_Ajax_Requests_File() + '?f=authorize&s=pay', {card_number:authorize_number,card_month:authorize_month,card_year:authorize_year,card_cvc:authorize_cvc,amount:amount}, function(data) {
	    if (data.status == 200) {
	      window.location.href = data.url;
	    } else {
	      $('#authorize_alert').html("<div class='alert alert-danger'>"+data.error+"</div>");
	      setTimeout(function () {
	        $('#authorize_alert').html("");
	      },3000);
	    }
	    $('#authorize_btn').html("<?php echo $wo['lang']['pay']; ?>");
	      $('#authorize_btn').removeAttr('disabled');
	  }).fail(function(data) {
	      $('#authorize_alert').html("<div class='alert alert-danger'>"+data.responseJSON.error+"</div>");
	    setTimeout(function () {
	      $('#authorize_alert').html("");
	    },3000);
	    $('#authorize_btn').html("<?php echo $wo['lang']['pay']; ?>");
	    $('#authorize_btn').removeAttr('disabled');
	  });
	}
<?php } ?>
</script>

<div id="iyzipay_content"></div>
<div class="modal fade" id="authorize_modal" role="dialog" data-keyboard="false" >
    <div class="modal-dialog mat_box">
        <div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['authorize'] ?></h4>
		    </div>
            <form class="form form-horizontal" method="post" id="authorize_form" action="#">
            	<div id="authorize_alert"></div>
                <div class="modal-body authorize_modal">
                	<div class="row two_check_card">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,8H4V6H20M20,18H4V12H20M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4Z" /></svg>
						<div class="sun_input col-lg-12">
							<input id="authorize_number" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['card_number']; ?>">
						</div>
						<div class="sun_input col-xs-4">
							<select id="authorize_month" name="card_month" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['month']; ?> (01)">
								<option value="01">01</option>
								<option value="02">02</option>
								<option value="03">03</option>
								<option value="04">04</option>
								<option value="05">05</option>
								<option value="06">06</option>
								<option value="07">07</option>
								<option value="08">08</option>
								<option value="09">09</option>
								<option value="10">10</option>
								<option value="11">11</option>
								<option value="12">12</option>
							</select>
							<!-- <input id="card_month" name="card_month" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['month']; ?> (01)"> -->
						</div>
						<div class="sun_input col-xs-4 no-padding-both">
							<select id="authorize_year" name="card_year" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['year']; ?> (2019)">
								<?php for ($i=date('Y'); $i <= date('Y')+15; $i++) {  ?>
									<option value="<?php echo($i) ?>"><?php echo($i) ?></option>
								<?php } ?>
							</select>
							<!-- <input id="card_year" name="card_year" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['year']; ?> (2019)"> -->
						</div>
						<div class="sun_input col-xs-4">
							<input id="authorize_cvc" name="card_cvc" type="text" class="form-control input-md" autocomplete="off" placeholder="CVC" maxlength="3" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
						</div>
					</div>
                </div>
                <div class="clear"></div>
                <div class="modal-footer">
                    <div class="ball-pulse"><div></div><div></div><div></div></div>
                    <button type="button" class="btn btn-primary btn-mat" id="authorize_btn" onclick="AuthorizeRequest($(this))"><?php echo $wo['lang']['pay']; ?></button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="payu_modal" role="dialog" data-keyboard="false" >
    <div class="modal-dialog mat_box">
        <div class="modal-content">
		    <div class="modal-header">
		    	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['payu'] ?></h4>
		    </div>
            <form class="form form-horizontal" method="post" id="payu_form" action="#">
            	<div id="payu_alert"></div>
                <div class="modal-body payu_modal">
                	<div class="row two_check_card">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,8H4V6H20M20,18H4V12H20M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4Z" /></svg>
						<div class="sun_input col-lg-12">
							<input id="payu_card_number" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['card_number']; ?>">
						</div>
						<div class="sun_input col-xs-4">
							<select id="payu_card_month" name="card_month" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['month']; ?> (01)">
								<option value="01">01</option>
								<option value="02">02</option>
								<option value="03">03</option>
								<option value="04">04</option>
								<option value="05">05</option>
								<option value="06">06</option>
								<option value="07">07</option>
								<option value="08">08</option>
								<option value="09">09</option>
								<option value="10">10</option>
								<option value="11">11</option>
								<option value="12">12</option>
							</select>
							<!-- <input id="card_month" name="card_month" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['month']; ?> (01)"> -->
						</div>
						<div class="sun_input col-xs-4 no-padding-both">
							<select id="payu_card_year" name="card_year" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['year']; ?> (2019)">
								<?php for ($i=date('Y'); $i <= date('Y')+15; $i++) {  ?>
									<option value="<?php echo($i) ?>"><?php echo($i) ?></option>
								<?php } ?>
							</select>
							<!-- <input id="card_year" name="card_year" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['year']; ?> (2019)"> -->
						</div>
						<div class="sun_input col-xs-4">
							<input id="payu_card_cvc" name="card_cvc" type="text" class="form-control input-md" autocomplete="off" placeholder="CVC" maxlength="3" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
						</div>
					</div>
                </div>
                <div class="clear"></div>
                <input id="payu_type" type="hidden">
                <div class="modal-footer">
                    <div class="ball-pulse"><div></div><div></div><div></div></div>
                    <button type="button" class="btn btn-primary btn-mat" id="payu_btn" onclick="pay_using_payu($(this))"><?php echo $wo['lang']['pay']; ?></button>
                </div>
            </form>
        </div>
    </div>
</div>





<div class="modal fade" id="2checkout_wallet_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['2checkout'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="2checkout_form_wallet" action="#">
				<div class="modal-body twocheckout_modal">
					<div id="2checkout_alert_wallet"></div>
					<div class="clear"></div>
					<div class="sun_input col-md-6">
						<input id="card_name" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['name']; ?>" value="<?php echo($wo['user']['name']) ?>">
						<label class="plr15" for="card_name"><?php echo $wo['lang']['name']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<input id="card_address" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['address']; ?>" value="<?php echo($wo['user']['address']) ?>">
						<label class="plr15" for="card_address"><?php echo $wo['lang']['address']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<input id="card_city" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['city']; ?>" value="<?php echo($wo['user']['city']) ?>">
						<label class="plr15" for="card_city"><?php echo $wo['lang']['city']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<input id="card_state" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['state']; ?>" value="<?php echo($wo['user']['state']) ?>">
						<label class="plr15" for="card_state"><?php echo $wo['lang']['state']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<input id="card_zip" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['zip']; ?>" value="<?php echo($wo['user']['zip']) ?>">
						<label class="plr15" for="card_zip"><?php echo $wo['lang']['zip']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<select id="card_country" name="card_country" class="form-control">
							<?php
								foreach ($wo['countries_name'] as $country_ids => $country) {
									$country_id = $wo['user']['country_id'];
									$selected_contry = ($country_ids == $country_id) ? ' selected' : '' ;
							?>
								<option value="<?php echo $country_ids;?>" <?php echo $selected_contry;?> ><?php echo $country;?></option>
							<?php } ?>
						</select>
						<label class="plr15" for="card_country"><?php echo $wo['lang']['country']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<input id="card_email" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['email']; ?>" value="<?php echo($wo['user']['email']) ?>">
						<label class="plr15" for="card_email"><?php echo $wo['lang']['email']; ?></label>
					</div>
					<div class="sun_input col-md-6">
						<input id="card_phone" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['phone_number']; ?>" value="<?php echo($wo['user']['phone_number']) ?>">
						<label class="plr15" for="card_phone"><?php echo $wo['lang']['phone_number']; ?></label>
					</div>
					<div class="clear"></div>
					<hr>
					<div class="row two_check_card">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,8H4V6H20M20,18H4V12H20M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4Z" /></svg>
						<div class="sun_input col-lg-12">
							<input id="_number_" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['card_number']; ?>">
							<input id="card_number" name="card_number" type="hidden" class="form-control input-md" autocomplete="off">
						</div>
						<div class="sun_input col-xs-4">
							<select id="card_month" name="card_month" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['month']; ?> (01)">
								<option value="01">01</option>
								<option value="02">02</option>
								<option value="03">03</option>
								<option value="04">04</option>
								<option value="05">05</option>
								<option value="06">06</option>
								<option value="07">07</option>
								<option value="08">08</option>
								<option value="09">09</option>
								<option value="10">10</option>
								<option value="11">11</option>
								<option value="12">12</option>
							</select>
							<!-- <input id="card_month" name="card_month" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['month']; ?> (01)"> -->
						</div>
						<div class="sun_input col-xs-4 no-padding-both">
							<select id="card_year" name="card_year" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['year']; ?> (2019)">
								<?php for ($i=date('Y'); $i <= date('Y')+15; $i++) {  ?>
									<option value="<?php echo($i) ?>"><?php echo($i) ?></option>
								<?php } ?>
							</select>
							<!-- <input id="card_year" name="card_year" type="text" class="form-control input-md" autocomplete="off" placeholder="<?php echo $wo['lang']['year']; ?> (2019)"> -->
						</div>
						<div class="sun_input col-xs-4">
							<input id="card_cvc" name="card_cvc" type="text" class="form-control input-md" autocomplete="off" placeholder="CVC" maxlength="3" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');">
						</div>
					</div>
					<div class="clear"></div>
					<input id="card_token" name="token" type="hidden" value="">
				</div>
				<div class="clear"></div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="button" class="btn btn-main" onclick="tokenRequest()" id="2checkout_btn_wallet"><?php echo $wo['lang']['pay']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>






<div class="modal fade" id="bank_transfer_modal" role="dialog" data-keyboard="false" style="overflow-y: auto;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><i class="fa fa-money"></i> <?php echo $wo['lang']['bank_transfer'] ?></h4>
			</div>
			<form class="form form-horizontal" method="post" id="bank_transfer_form_wallet" action="#">
			<div class="modal-body dt_bank_trans_modal">
				<div id="blog-alert"></div>
				<p><?php echo $wo['config']['bank_description'];?></p>
				<?php if (!empty($wo['config']['bank_transfer_note'])) { ?>
					<div class="dt_user_profile hide_alert_info_bank_trans">
							<span class="valign-wrapper">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M13,13H11V7H13M13,17H11V15H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"></path></svg> Note:
							</span>
							<ul class="dt_prof_vrfy">
								<li><?php echo $wo['config']['bank_transfer_note'];?></li>
							</ul>
						</div>
				<?php } ?>
				<p class="dt_bank_trans_upl_rec"><a href="javascript:void(0);" onclick="$('#bank_transfer_modal').addClass('up_rec_active'); return false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M13.5,16V19H10.5V16H8L12,12L16,16H13.5M13,9V3.5L18.5,9H13Z"></path></svg> <?php echo $wo['lang']['upload'] ?></a></p>
					<div class="upload_bank_receipts">
						<div onclick="document.getElementById('upload').click(); return false">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M13.5,16V19H10.5V16H8L12,12L16,16H13.5M13,9V3.5L18.5,9H13Z"></path></svg>
							<p><?php echo $wo['lang']['browse_to_upload']; ?></p>
							<img id="receipt_img_preview" src="">
						</div>
					</div>
					<input name="price" type="hidden" id="bank_transfer_price" class="hidden">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					<input name="thumbnail" type="file" id="upload" class="hidden" accept="image/*">
					<input name="type" type="hidden" id="bank_transfer_type" class="hidden">
					<input name="description" type="hidden" id="bank_transfer_des" class="hidden">
					<input type="reset" id="configreset" value="Reset" class="hidden">
			</div>
			<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="submit" class="btn btn-main"><?php echo $wo['lang']['publish']; ?></button>
				</div>
				</form>
		</div>
	</div>
</div>
















<!-- <div class="modal fade" id="bank_transfer_modal" role="dialog" data-keyboard="false">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><i class="fa fa-money"></i> <?php echo $wo['lang']['bank_transfer'] ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo nl2br($wo['config']['bank_description']);?></p>
				<?php if (!empty($wo['config']['bank_transfer_note'])) { ?>
					<div class="alert alert-warning"><?php echo nl2br($wo['config']['bank_transfer_note']);?></div>
				<?php } ?>
				<div>
					<div class="page-margin">
						<div class="row">
							<div class="col-md-12 wo-create-forms">
								<div class="wo_settings_page">
									<form class="form form-horizontal create-article-form" method="post" id="bank_transfer_form_wallet" action="#">
										<div class="setting-panel row">
											<div class="create_blog_area_acombo">
											<div class="form-group col-sm-12">
												<div class="col-md-12">
													<div class="main prv-img pointer" id="select-img" data-block="thumdrop-zone">
														<div class="thumbnail-rendderer">
															<div>
																<h4 class="bold"><?php echo $wo['lang']['drop_img_here']; ?></h4>
																<div class="error-text-renderer"></div>
																<div>
																	<span><?php echo $wo['lang']['or']; ?></span>
																	<p><?php echo $wo['lang']['browse_to_upload']; ?></p>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											</div>

											<input type="file" class="hidden" id="thumbnail" name="thumbnail" accept="image/*">
										</div>

										<div class="setting-update-alert" id="blog-alert"></div>

										<div class="form-group last-sett-btn modal-footer">
											<div class="ball-pulse"><div></div><div></div><div></div></div>
											<button type="submit" class="btn btn-main setting-panel-mdbtn"><?php echo $wo['lang']['publish']; ?></button>
										</div>
										<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
										<input name="image" type="file" id="upload" class="hidden">
										<input name="price" type="hidden" id="bank_transfer_price" class="hidden">
										<input name="description" type="hidden" id="bank_transfer_des" class="hidden">
										<input type="reset" id="configreset" value="Reset" class="hidden">
									</form>
								</div>
							</div>
						</div>
						 .row -->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
