<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists singlecol">
			<?php if ($wo['config']['user_ads'] == 1): ?>
				<div id="sidebar-sticky-funding">
					<?php 
					  $wo['sidebar-ad'] = Wo_GetAdsByType('funding');
					  if (!empty($wo['sidebar-ad'])) {
					  	echo Wo_LoadPage('ads/includes/funding-ad');
					  }
					?>
					<div class="clear"></div>
				</div>
		    <?php endif; ?>
			<div class="wo_my_pages">
				<div class="my_pages_header row">
					<ul class="<?php echo Wo_RightToLeft('pull-left'); ?>">
						<li><a href="<?php echo Wo_SeoLink('index.php?link1=funding'); ?>" data-ajax="?link1=funding"><?php echo $wo['lang']['funding'] ?></a></li>
						<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=my_funding'); ?>" data-ajax="?link1=my_funding"><?php echo $wo['lang']['my_funding'] ?></a></li>
					</ul>
					<?php if ($wo['config']['can_use_funding']) { ?>
					<span class="btn btn-success <?php echo Wo_RightToLeft('pull-right'); ?>">
						<a href="<?php echo Wo_SeoLink('index.php?link1=create_funding');?>" data-ajax="?link1=create_funding"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg></a>
					</span>
					<?php } ?>
				</div>

				<div class="row" id="blog-list">
					<?php  
						$funding = GetFundingByUserId($wo["user"]['id'],9); 

					?>

					<?php if ($funding && count($funding) > 0): ?>
						<?php foreach ($funding as $wo['fund']): ?>
							<?php echo Wo_LoadPage('my_funding/list'); ?>
						<?php endforeach ?>
					<?php else: ?> 
						<?php echo '<h5 class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-dollar-sign"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg> ' . $wo['lang']['no_funding_found'] . '</h5>'; ?>
					<?php endif; ?> 
				</div>
				
				<div class="loading-alert"></div>
            
				<div class="posts_load">
					<?php if (count($funding) >= 8): ?>
					<div class="load-more">
                        <button class="btn btn-default text-center pointer load-more-my-fund">
                          <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                          <?php echo $wo['lang']['load_more'] ?>
                        </button>
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo Wo_LoadPage('my_funding/delete_fund');?>

<script>
$(document).ready(function() {
  $(".delete-fund").on("click", function() {
    $("#delete-fund").attr('data-fund-id', $(this).attr("id")).modal();      
  });

  $(".load-more-my-fund").click(function () {
      let offset = (($(".view-blog").length > 0) ? $(".view-blog:last").attr('id') : 0);

      $.ajax({
         url: Wo_Ajax_Requests_File(),
         type: 'GET',
         dataType: 'json',
         data: {f:"funding",s:"load_user_fund",offset:offset},
         success:function(data){
            if (data['status'] == 200 && data['html'] != '') {
              $("#blog-list").append(data['html']);
            }

            else{
              $(".posts_load").remove();
            }
         }
      });
   });
});
</script>