<div class="page-margin">
	<div class="wow_main_float_head jobs new_jobs">
		<div class="container">
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg>
			<h1><?php echo $wo['lang']['jobs']; ?></h1>
			<p><?php echo $wo['lang']['search_find_job_at']; ?> <?php echo $wo['config']['siteName'];?></p>
		</div>
	</div>
	
	<div class="wow_main_blogs_bg"></div>
	
	<div class="wow_content wo_job_head_filter">
		<div class="search-blog">
			<form action="">
				<input type="text" onkeyup="Wo_SearchJobs(this.value)" placeholder="<?php echo $wo['lang']['search_for_jobs']; ?>" id="product-text">
			</form>
		</div>
		<div class="dropdown wo_job_main_widget">
			<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button"><?php echo $wo['lang']['job_type'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z"></path></svg></div>
			<div class="dropdown-menu">
				<div class="wjob_categories">
					<ul class="product-category-slider">
						<?php 
						$job_type = array('full_time','part_time','internship','volunteer','contract');
							$category_id = (!empty($_GET['c_id'])) ? (int) $_GET['c_id'] : 0;
							$type = (!empty($_GET['type'])) ? $_GET['type'] : '';
							foreach ($job_type as $key => $category) {
								$active = ($type == $category) ? 'active' : '';
						?>
							<li class="<?php echo $active?>" data_prodect_type_id="<?php echo($category) ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=jobs');?>?c_id=<?php echo($category_id) ?>&type=<?php echo($category) ?>"><?php echo $wo['lang'][$category];?></a></li>
						<?php } ?>
					</ul>
				</div>
			</div>
		</div>
		<div class="dropdown wo_job_main_widget">
			<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button"><?php echo $wo['lang']['categories'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z"></path></svg></div>
			<div class="dropdown-menu">
				<div class="wjob_categories">
					<ul class="product-category-slider">
						<?php 
							$category_id = (!empty($_GET['c_id'])) ? (int) $_GET['c_id'] : 0;
							$type = (!empty($_GET['type'])) ? $_GET['type'] : '';
							foreach ($wo['job_categories'] as $key => $category) {
								$active = ($category_id == $key) ? 'active' : '';
						?>
							<li class="<?php echo $active?>"><a href="<?php echo Wo_SeoLink('index.php?link1=jobs');?>?c_id=<?php echo($key) ?>&type=<?php echo($type) ?>"><?php echo $category;?></a></li>
						<?php } ?>
					</ul>
				</div>
			</div>
		</div>
		<div class="dropdown wo_job_main_widget">
			<div class="m_widget_head dropdown-toggle" data-toggle="dropdown" role="button"><?php echo $wo['lang']['location_dist'];?> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M7,10L12,15L17,10H7Z"></path></svg></div>
			<div class="dropdown-menu">
				<div class="select-nearby-users-distance wo_select_job_dist">
					<form>
						<input type="range" class="cusrange" id="nearby-users-distance" name="amountRange" onchange="Wo_SearchJobsNearBy();" value="0" min="0" max="300" oninput="this.form.amountInput.value=this.value">
						<input type="number" name="amountInput" min="0" max="4000" value="0" oninput="this.form.amountRange.value=this.value" readonly id="cusrange-reader"/> km
					</form>
				</div>
			</div>
		</div>
		<?php if ($wo['loggedin'] == true) { ?>
		<?php if ($wo['config']['nearby_business_system'] == 1) { ?>
			<a href="<?php echo($wo['config']['site_url'].'/nearby_business') ?>" data-ajax="?link1=nearby_business" class="btn btn-info side_mkt_btn btn-mat"><?php echo $wo['lang']['nearby_business'] ?></a>
		<?php } ?>
		<?php } ?>
	</div>
	
	<?php if ($wo['config']['user_ads'] == 1): ?>
			<div id="sidebar-sticky-jobs">
				<?php 
				  $wo['sidebar-ad'] = Wo_GetAdsByType('jobs');
				  if (!empty($wo['sidebar-ad'])) {
				  	echo Wo_LoadPage('ads/includes/jobs-ad');
				  }
				?>
				<div class="clear"></div>
			</div>
        <?php endif; ?>
	
	<div class="row">
		<div class="col-md-12">
			<div class="latest-products">
				<?php
					$category_name = '';
				$data = array();
				if (!empty($_GET['c_id'])) {
					if (is_numeric($_GET['c_id'])) {
						if (array_key_exists($_GET['c_id'], $wo['job_categories'])) {
							?>
							<input type="hidden" value="<?php echo Wo_Secure($_GET['c_id']); ?>" id="c_id" />
							<?php
							$category_name = $wo['job_categories'][$_GET['c_id']];
							$data['c_id'] = Wo_Secure($_GET['c_id']);
						}
					}
				} else {
					echo '<input type="hidden" value="0" id="c_id" />';
				}

				if (!empty($_GET['type'])) {
						if (in_array($_GET['type'], $job_type)) {
							?>
							<input type="hidden" value="<?php echo Wo_Secure($_GET['type']); ?>" id="job_type" />
							<?php
							$data['type'] = Wo_Secure($_GET['type']);
						}
				} else {
					echo '<input type="hidden" value="" id="job_type" />';
				}
				?>
				<div class="market_bottom">
					<?php
						$data['limit'] = 10;
						$jobs = Wo_GetAllJobs($data);
						if (count($jobs) > 0) {
					?>
					<div class="row" id="products">
						<?php
						foreach ($jobs as $key => $wo['job']) {
							echo Wo_LoadPage('jobs/jobs_list'); 
						}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z" /></svg>' . $wo['lang']['no_available_jobs'] . '</div>';
						}
						?>
					</div>
				</div>
			</div> 	
			<div class="posts_load load-produts">
			    <?php if (count($jobs) > 0): ?>
				<div class="load-more">
                    <button class="btn btn-default text-center pointer" onclick="Wo_LoadJobs();">
                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_jobs'] ?></button>
                </div>
                <?php endif ?>
			</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
		<br>		
           <?php //echo Wo_LoadPage('footer/content'); ?>
</div>
<div class="modal fade" id="delete-job-modal" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['delete_job']; ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $wo['lang']['confirm_delete_job']; ?></p>
				<input type="hidden" id="delet_job_id">
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button id="delete-all-post" type="button" onclick="Wo_DeleteJob();" class="btn btn-main btn-mat"><?php echo $wo['lang']['delete']; ?></button>
			</div>
		</div>
	</div>
</div>

<script>
$('.wow_main_blogs_bg').css('height', ($('.wow_main_float_head').height()) + 'px');

function Wo_OpenJobDeleteBox(job_id) {
  $('#delet_job_id').val(job_id);
  var delete_box = $('#delete-job-modal');
  delete_box.modal({
    show: true
  });
}
function Wo_DeleteJob() {
  Wo_CloseLightbox();
  var job_id = $('#delet_job_id').val();
  var delete_box = $('#delete-job-modal');
  $('#delete-job-modal').find('.ball-pulse').fadeIn(100);
  $.get(Wo_Ajax_Requests_File(), {
    f: 'job',
    s: 'delete_job',
    job_id: job_id
  }, function (data) {
    if(data.status == 200) {
      delete_box.modal('hide');
      setTimeout(function () {
        $('#product-' + job_id).slideUp(200, function () {
          $(this).remove();
        });
      }, 300);
    }
    $('#delete-job-modal').find('.ball-pulse').fadeOut(100);
  });
}
function Wo_SearchJobsNearBy() {
	length = $('#cusrange-reader').val();
	text_value = $('#job-text').val();
	var c_id = 0;
	if ($('#c_id').length > 0) {
		c_id = $('#c_id').val();
	}
	var type = '';
	if ($('#job_type').length > 0) {
		type = $('#job_type').val();
	}
	$.post(Wo_Ajax_Requests_File() + '?f=job&s=search_jobs', {value: text_value, c_id:c_id,type:type, length: length}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('#products').html(data.html);
			} else {
				$('#products').html('<?php echo $wo['lang']['no_available_jobs'] ?>');
			}
		}
	});
}
function Wo_LoadJobs() {
	$('.load-produts').html('<div class="white-loading list-group"><div class="cs-loader"><div class="cs-loader-inner"><label> ●</label><label> ●</label><label> ●</label><label> ●</label><label> ●</label><label> ●</label></div></div></div>');
	var $c_id = $('#c_id').val();
	var text = $('#job-text').val();
	var $last_id = $('.product:last').attr('data-id');
	var price = $('.product:last').attr('data_price');
	var length = $('#distance_val').text();
	var price_sort = $('#PriceSortValue').attr('data_PriceSortType');
	var type = '';
	if ($('#job_type').length > 0) {
		type = $('#job_type').val();
	}
	$.post(Wo_Ajax_Requests_File() + '?f=job&s=search_jobs', {last_id: $last_id, c_id:$c_id,type:type, length: length,price_sort:price_sort,price:price,text:text}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('.load-produts').html('<div class="load-more"><button class="btn btn-default text-center pointer" onclick="Wo_LoadJobs();"><i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_products'] ?></button></div>');
				$('#products').append(data.html);
			} else {
				$('.load-produts').html('<div class="load-more"><button class="btn btn-default text-center pointer" onclick="Wo_LoadJobs();"><?php echo $wo['lang']['no_available_jobs'] ?></button></div>');
			}
		}
	});
}
function Wo_SearchJobs(value) {
	length = $('#distance_val').text();
	var price_sort = $('#PriceSortValue').attr('data_PriceSortType');
	var c_id = 0;
	if ($('#c_id').length > 0) {
		c_id = $('#c_id').val();
	}
	var type = '';
	if ($('#job_type').length > 0) {
		type = $('#job_type').val();
	}
	$.post(Wo_Ajax_Requests_File() + '?f=job&s=search_jobs', {value: value, c_id:c_id,type:type, length: length,price_sort:price_sort}, function (data) {
		if (data.status == 200) {
			if (data.html.length > 0) {
				$('#products').html(data.html);
			} else {
				$('#products').html('<?php echo $wo['lang']['no_available_jobs'] ?>');
			}
		}
	});
}
</script>