<tr tabindex="1" class="mythread-list" data-thread-ident="<?php echo $wo['thread']['id']; ?>">
	<td class="">
		<div class="threadcont-inner">
	    	<div >
	    		<a class="sun_ftitle" href="<?php echo $wo['thread']['url'];?>" data-ajax="?link1=showthread&tid=<?php echo $wo['thread']['id'];?>">
		        	<?php 
		        		
		        		if(strlen($wo['thread']['headline']) > 55){
		        			echo Wo_GetShortTitle($wo['thread']['headline'], false, 50);
		        		}
		      			else {
		      				echo $wo['thread']['headline'];
		      			}
		        	?>	
	        	</a>
	    	</div>
	    	<div class="thread-info">
		    	<span class="blog-meta-desc"><i><?php echo $wo['lang']['by']; ?></i> <a href="<?php echo $wo['thread']['author_url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['thread']['user_data']['username']; ?>"><?php echo $wo['thread']['user_data']['username']; ?></a></span>
		    	<span>
		        	<?php echo Wo_Time_Elapsed_String($wo['thread']['posted']); ?>
		    	</span>
	    	</div>

		</div>
	</td>

	<td class="small">
		<h6><?php echo $wo['thread']['views']; ?> <?php echo $wo['lang']['views']; ?></h6> 
	</td>
	<td class="small">
		<h6>
		<?php if ($wo['thread']['last_post'] > 0): ?>
			<?php echo Wo_Time_Elapsed_String($wo['thread']['last_post']); ?>
		<?php else: ?>
			<?php echo $wo['lang']['never'] ?>
		<?php endif; ?>
				
		</h6>
	</td>
	<td class="small ">
		<a class="btn btn-default btn-mat" href="<?php echo $wo['thread']['edit_url']; ?>" data-ajax="?link1=edithread&tid=<?php echo $wo['thread']['id'];?>">
	        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z" /></svg>
        </a>
		<a class="btn btn-default btn-mat delete-thread" id="<?php echo $wo['thread']['id']; ?>">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" /></svg>
		</a>
	</td>
</tr>