<div class="container-fluid">
    <div>
        <h3>CHANGELOGS</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">CHANGELOGS</li>
            </ol>
        </nav>
    </div>
		<div class="alert alert-info">Updates are provided freely for life-time if you own a valid purchase code, don't have one? <a href="https://bit.ly/2R2jrcz" target="_blank">Get Valid Purchase Code!</a></div>
            <!-- Changelogs -->
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1.1 <small>08 Jul 2022 </small></h6>
                          <ul>
                              <li> [Added] story viewed time.</li>
                              <li> [Improved] design / colors in default theme for few sections.</li>
                              <li> [Improved] audio player design.</li>
                              <li> [Fixed] create article issue.</li>
                              <li> [Fixed] live streaming privacy not updating in admin panel.</li>
                              <li> [Fixed] pick your plans, go pro plans were not showing on welcome page. </li>
                              <li> [Fixed] CROS issues in nodejs.</li>
                              <li> [Fixed] wallet system was not accepting top ups more than 1000</li>
                              <li> [Fixed] message button was not showing on profile (mobile).</li>
                              <li> [Fixed] {site_name} showing on registration page.</li>
                              <li> [Fixed] charts were not showing on groups and pages if loading using ajax.</li>
                              <li> [Fixed] stories now are ordered by DESC instead of ASC.</li>
                              <li> [Fixed] chat colors, default color was black.</li>
                              <li> [Fixed] birthday showing NULL on profile page sometimes. </li>
                              <li> [Fixed] clicking on stories next shows pervious story.</li>
                              <li> [Fixed] charecter limit on privacy page.</li>
                              <li> [Fixed] disabling pages was disabling the create button on top header.</li>
                              <li> [Fixed] YouTube videos on Instegram mode wasn't working.</li>

                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.1 <small>01 Jul 2022 </small></h6>
                          <ul>
                              <li> [Added] report user system + reason.</li>
                              <li> [Added] ban message on user profile if user is banned. </li>
                              <li> [Added] Instagram Mode.</li>
                              <li> [Added] flutterwave payment method.</li>
                              <li> [Added] Ngenius payment method.</li>
                              <li> [Added] Aamarpay payment method.</li>
                              <li> [Added] the ability to add custom pro packages.</li>
                              <li> [Added] the ability to add custom withdrawal method. </li>
                              <li> [Added] the abiltiy to choose whom can use a feature, Admin, All Users, Only Pro.</li>
                              <li> [Added] the ability to resend two auth verfication code.</li>
                              <li> [Added] new design for Instegram mode.</li>
                              <li> [Added] developer mode to admin panel.</li>
                              <li> [Updated] documentation & FAQs: <a href="https://docs.wowonder.com/" target="_blank">https://docs.wowonder.com/</a> .</li>
                              <li> [Updated] email verfication page design. </li>
                              <li> [Updated] chat design.</li>
                              <li> [Updated] all website shadow elements (css).</li>
                              <li> [Updated] header notifications, messages dropdown size.</li>
                              <li> [Updated] post comments design.</li>
                              <li> [Improved] design in default theme for few sections.</li>
                              <li> [Fixed] qrcode.js was missing in sunshine.</li>
                              <li> [Fixed] search in admin panel was not working well.</li>
                              <li> [Fixed] login using twitter.</li>
                              <li> [Fixed] admin commission was not appearing with product purchase.</li>
                              <li> [Fixed] OG meta tags for albums.</li>
                              <li> [Fixed] XSS vulnerability.</li>
                              <li> [Fixed] fixed product showing in stock while there is no stock left.</li>
                              <li> [Fixed] announcements wern't working.</li>
                              <li> [Fixed] agora live video / calls.</li>
                              <li> [Fixed] google login API.</li>
                              <li> [Fixed] twilio video/audio calls.</li>
                              <li> [Fixed] if post was boosted on a page it doesn't appear in booted posts section.</li>
                              <li> [Fixed] the ability to send gif & stickers on nodejs. </li>
                              <li> [Fixed] 40+ more minor bugs.</li>
                              <li> [Fixed] bugs in API.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.0.1 <small>23 Feb 2022 </small></h6>
                          <ul>
                              <li> [Added] audio player for mp3 files.</li>
                              <li> [Added] yandex API for maps. </li>
                              <li> [Added] yandex payment method.</li>
                              <li> [Added] iyzipay payment method.</li>
                              <li> [Added] securionpay payment method.</li>
                              <li> [Added] authorize.Net payment method. </li>
                              <li> [Added] ok.ru social login.</li>
                              <li> [Added] new APIs in developers page: get_pages, get_groups, get_products, get_followers, get_following, get_friends</li>
                              <li> [Added] mobile apps links in welcome page and sidebar, managed from admin panel -> website information.</li>
                              <li> [Updated] design in few sections.</li>
                              <li> [Updated] documentation & FAQs: <a href="https://docs.wowonder.com/" target="_blank">https://docs.wowonder.com/</a> .</li>
                              <li> [Fixed] price not showing in products.</li>
                              <li> [Fixed] links not working on profile page.</li>
                              <li> [Fixed] ajax load in few pages.</li>
                              <li> [Fixed] broken images when importing a link.</li>
                              <li> [Fixed] add as familly system.</li>
                              <li> [Fixed] XSS vulnerability.</li>
                              <li> [Fixed] 10+ more minor bugs.</li>
                              <li> [Fixed] bugs in API.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
            <div class="row clearfix">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="card">
                      <div class="card-body">
                          <h6 class="card-title">v4.0 <small>07 Feb 2022 [Ultimate Update]</small></h6>
                          <ul>
                              <li> [Added] website mode, switch your website instantly to Linkedin mode. (Instagram, Twitter, AskFM, Patreon are coming soon).</li>
                              <li> [Added] marketplace system, users can now buy and sell products + admin commission. </li>
                              <li> [Added] moderator rules manager, now you can choose what a moderator can do.</li>
                              <li> [Added] more ads placements (jobs, forums, movies, offers & funding) & entire site option.</li>
                              <li> [Added] multiple levels affiliate system.</li>
                              <li> [Added] custom ban message for every user. </li>
                              <li> [Added] the ability to translate terms pages.</li>
                              <li> [Added] CoinBase payment method. </li>
                              <li> [Added] new search system for Linkedin mode. </li>
                              <li> [Added] more APIs. </li>
                              <li> [Added] ReCaptcha to create article page. </li>
                              <li> [Added] Wasabi Storage.</li>
                              <li> [Added] new welcome page.</li>
                              <li> [Added] remember me on login page.</li>
                              <li> [Added] mutli languages support for terms, privacy and about pages.</li>
                              <li> [Updated] bulksms API.</li>
                              <li> [Updated] CoinPayments API.</li>
                              <li> [Updated] Infobip API.</li>
                              <li> [Updated] marketplace, jobs & movies pages design (default theme). </li>
                              <li> [Updated] design in a few other pages (default theme).</li>
                              <li> [Updated] Twilio SDK. </li>
                              <li> [Updated] left sidebar icons. (default theme)</li>
                              <li> [Updated] documentation & FAQs: <a href="https://docs.wowonder.com/" target="_blank">https://docs.wowonder.com/</a> .</li>
                              <li> [Cleaned] 10,000+ lines of outdated code. </li>
                              <li> [Orginzed] PHP code format (HTML coming in next update).</li>
                              <li> [Fixed] images with _small extensions is not getting deleted on remote storage.</li>
                              <li> [Fixed] watermark isn't working on images posts.</li>
                              <li> [Fixed] family memebers texts.</li>
                              <li> [Fixed] auto username, pages likes or groups joins isn't working when you register using the app.</li>
                              <li> [Fixed] login with instagram isn't working.</li>
                              <li> [Fixed] email notifications are not working on follow, view profile or comments.</li>
                              <li> [Fixed] digitalocean test button wasn't working in admin panel.</li>
                              <li> [Fixed] Audio/video calls are not working from website to apps using agora.</li>
                              <li> [Fixed] "common things" page php fatal error.</li>
                              <li> [Fixed] 2 XSS exploits. <small style="color: red;">[Important!]</small>  </li>
                              <li> [Fixed] blank page when adding / in url.</li>
                              <li> [Fixed] site-map doesn't generate more than 50K links.</li>
                              <li> [Fixed] read more button on mobile.</li>
                              <li> [Fixed] 30+ more minor bugs.</li>
                              <li> [Fixed] bugs in API.</li>
                          </ul>
                      </div>
                  </div>
              </div>
           </div>
              <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.2.2 <small>09 Augest 2021 </small></h6>
                            <ul>
                                <li> [Added] Palestine to country list.</li>
                                <li> [Removed] dublicated nginx rules in nginx.conf, update required for nginx users. </li>
                                <li> [Replaced] Yahoo weather with new provider https://openweathermap.org</li>
                                <li> [Fixed] live video not working on firefox.</li>
                                <li> [Fixed] blog point issue, user will get points now after approving.</li>
                                <li> [Fixed] nearby shops counter. </li>
                                <li> [Fixed] line break issue in nodejs chat system.</li>
                                <li> [Fixed] refund page wasn't apearing. </li>
                                <li> [Fixed] add movies page in admin, sometimes it looks broken.</li>
                                <li> [Fixed] bank details wasn't getting updated in admin panel. </li>
                                <li> [Fixed] issues in design.</li>
                                <li> [Fixed] video post on MySQL 8 and PHP 8.</li>
                                <li> [Fixed] more minor bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.2.1 <small>28 June 2021 </small></h6>
                            <ul>
                                <li> [Added] delete account E-mail to Manage Emails in admin panel.</li>
                                <li> [Re-orginzed] admin panel links, content, texts and created auto save system.</li>
                                <li> [Fixed] seen issue on nodejs.</li>
                                <li> [Fixed] FTP support on nodejs.</li>
                                <li> [Fixed] "View X Posts" on newsfeed (NodeJS).</li>
                                <li> [Fixed] 2 security issues (important). </li>
                                <li> [Fixed] double points when posting multi images.</li>
                                <li> [Fixed] 500 Error when accessing a page without being logged in. </li>
                                <li> [Fixed] URL fetcher, it wasn't fetching URLs from WoWonder blogs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.2 <small>8 June 2021 </small></h6>
                            <ul>
                                <li> [Added] ability to edit and translate emails from admin panel, under Tools > Manage E-mails.</li>
                                <li> [Added] expire time for reset password links, 12 hours.</li>
                                <li> [Added] FFMPEG for video conversation + thumbnail generation + debug ffmpeg feature from admin panel + up to 4K video support, (Enable / Disable).</li>
                                <li> [Added] auto username generator, for new user registration users are not required to write their username. (Enable / Disable)</li>
                                <li> [Added] new APIs, more than 40+.</li>
                                <li> [Added] reactions for messages, (ajax / nodejs). </li>
                                <li> [Added] reply system for messages, (ajax / nodejs). </li>
                                <li> [Added] reactions system for stories. </li>
                                <li> [Added] reply system for stories. </li>
                                <li> [Added] gifs + stickers to comment system. </li>
                                <li> [Added] gifs + stickers to reply system. </li>
                                <li> [Added] video chat by Agora. </li>
                                <li> [Added] terms of use checkbox to contact us page. </li>
                                <li> [Added] the ability to delete poll answers while creating one.</li>
                                <li> [Added] login with Mailru, Discord, WeChat and QQ.</li>
                                <li> [Added] ability to delete selected user's messages, stories, posts, articles, and notifications from admin panel.</li>
                                <li> [RE-ADDED] script version in admin panel sidebar.</li>
                                <li> [Updated] twilio video chat system. </li>
                                <li> [Updated] message seen systemn (NodeJS). </li>
                                <li> [Fixed] 80+ reported bugs and improvments.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1.3 <small>12 April 2021 </small></h6>
                            <ul>
                                <li> [Added] real-time notification system.</li>
                                <li> [Improved] server load & site speed.</li>
                                <li> [Removed] All PHP ajax intervals, requests, and loops from clinet end (if nodejs enabled) and replaced to realtime web socket.</li>
                                <li> [Fixed] 3+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1.2 <small>28 March 2021 </small></h6>
                            <ul>
                                <li> [Added] support for PHP 8.0+ and MySQL 8.0</li>
                                <li> [Added] new ajax load system for admin panel, now admin panel pages are loaded thru ajax.</li>
                                <li> [Updated] nodejs chat system, now users can see typing action on messages user list, real time avatar update, name, and status.</li>
                                <li> [Updated] S3 / Spaces libraries. </li>
                                <li> [Improved] speed on PHP 8.0</li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1.1 <small>05 March 2021 </small></h6>
                            <ul>
                                <li> [Fixed] 10+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.1 <small>04 March 2021 </small></h6>
                            <ul>
                                <li> [Added] new messaging system powered by NodeJS and websockets, now chat are faster, real time, and smoother. </li>
                                <li> [Added] new admin panel v2, with many options.</li>
                                <li> [Added] new timestamp system, e.g (1 mintue ago -> 1 m, 2 hours ago -> 2 hrs, 1 month ago -> 4 w, 1 year ago -> 1 y)</li>
                                <li> [Added] new notifications for admin panel, now you'll get notificed for any new bank payments, verfication requests and more.</li>
                                <li> [Added] night mode to admin panel. </li>
                                <li> [Improved] security. [Important] </li>
                                <li> [Fixed] 60+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.3 <small>08 July 2020 </small></h6>
                            <ul>
                               <li> [Added] ability to embed posts from TikTok, Twitter, and MP4 links. </li>
                                <li> [Improved] security. [Important] </li>
                                <li> [Fixed] 10+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.3 <small>08 July 2020 </small></h6>
                            <ul>
                                <li> [Added] ability to choose camera on live streaming. </li>
                                <li> [Added] thumbnail for live streaming videos. </li>
                                <li> [Added] female avatar for female users. </li>
                                <li> [Added] Few more APIs. (payment methods) </li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.2
                                <small>26 May 2020 </small></h6>
                            <ul>
                                <li> [Added] Agora Live Streaming. </li>
                                <li> [Added] Few more APIs. </li>
                                <li> [Fixed] 40+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                                <li> [Improved] Load speed.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0.1
                                <small>18 April 2020 </small></h6>
                            <ul>
                                <li> [Fixed] 10+ bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v3.0
                                <small>16 April 2020 [Ultimate] </small></h6>
                            <ul>
                                <li> [Added] the ability to edit/add/disable post reactions. </li>
                                <li> [Added] memories system, user can view his memories on this day.</li>
                                <li> [Added] live stream for posts [enable/disable] (third party sites).</li>
                                <li> [Added] page analytics, view latest likes per week, month, year, and today.</li>
                                <li> [Added] group analytics, view latest joins per week, month, year, and today.</li>
                                <li> [Added] blog post notifications, get a notification when someone comments on your blog post.</li>
                                <li> [Added] forum notifications, get a notification when someone comments on your forum thread.</li>
                                <li> [Added] the ability to require membership on sign up, [enable/disable]</li>
                                <li> [Added] sub categories for pages, groups and marketplace.</li>
                                <li> [Added] custom fields for pages, groups and marketplace. </li>
                                <li> [Added] remaining pro membership days announcement. </li>
                                <li> [Added] recurring payments for pro system.</li>
                                <li> [Added] the ability for only pro users could upload [enable/disable].</li>
                                <li> [Added] the ability for only pro users could make calls [enable/disable]</li>
                                <li> [Added] blog posts review/approval system. </li>
                                <li> [Added] the ability to request refund for pro package [enable/disable]</li>
                                <li> [Added] refund policy page. </li>
                                <li> [Added] paystack, razorpay, paysera and cashfree payment methods. </li>
                                <li> [Added] page to show shops/businesses nearby. </li>
                                <li> [Added] offer system for pages. </li>
                                <li> [Added] password complexity system on register page. </li>
                                <li> [Added] prevent brutforce on login system, limit failed login per min.</li>
                                <li> [Added] the ability for users to be able to post in the pages. [enable/disable]</li>
                                <li> [Added] the ability for pages and groups owners could add moderators with certain privileges.</li>
                                <li> [Added] google cloud for storage.</li>
                                <li> [Added] bank account withdrawal method, user can send his bank info to admin and admin can review then approve.</li>
                                <li> [Added] email mock system. send email for users who didn't login for X time.</li>
                                <li> [Added] the ability to add games from other sites, not just miniclip.</li>
                                <li> [Added] the ability to get notified when user posts new post.</li>
                                <li> [Added] ads within and inside articles.</li>
                                <li> [Added] the ability for users to generate invite links.</li>
                                <li> [Added] shout box, post anonymously.</li>
                                <li> [Added] the ability to get notified when a friend posts a new post.</li>
                                <li> [Fixed] 50+ bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                                <li> [Fixed] Important security issues.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.5.2
                                <small>7 Jan 2020 [Important]</small></h6>
                            <ul>
                                <li> [Added] click button to comment and reply.</li>
                                <li> [Fixed] bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                                <li> [Fixed] Important security issues.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.5.1
                                <small>17 Dec 2019 [Important]</small></h6>
                            <ul>
                                <li> [Added] view joined groups and liked pages from one page.</li>
                                <li> [Added] the ability to attache photos in commment replies.</li>
                                <li> [Added] missing files from v2.5</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.5
                                <small>16 Dec 2019 [Script improvments update]</small></h6>
                            <ul>
                                <li> [Added] the ability logout from all sessions.</li>
                                <li> [Added] the ability to approve or decline a post, enable / disable.</li>
                                <li> [Added] new APIs. </li>
                                <li> [Added] auto like for pages and auto join for groups. </li>
                                <li> [Updated] PHP libaries.</li>
                                <li> [Updated] Google login API.</li>
                                <li> [Improved] default theme design.</li>
                                <li> [Improved] speed.</li>
                                <li> [Improved] english in some parts.</li>
                                <li> [Fixed] 100+ reported bugs and issues.</li>
                                <li> [Fixed] bugs in API.</li>

                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.4
                                <small>01 Sep 2019</small></h6>
                            <ul>
                                <li> [Added] the ability to send messages to pages.</li>
                                <li> [Added] the ability to accept or decline a group chat invitation.</li>
                                <li> [Added] job system, users can now create jobs and hire.</li>
                                <li> [Added] weather plugin to sidebar. </li>
                                <li> [Added] common things page, now you can find users that matches your information.</li>
                                <li> [Added] funding system, users can create funds, and get paid.</li>
                                <li> [Added] new APIs. </li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                                <li> [Improved] speed.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3.3
                                <small>11 July 2019</small></h6>
                            <ul>
                                <li> [Added] few new APIs to v2.</li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                                <li> [Improved] script stabilitiy for v2.4</li>
                                <li> [Improved] speed.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3.2
                                <small>20 June 2019</small></h6>
                            <ul>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Improved] speed.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3.1
                                <small>2 June 2019</small></h6>
                            <ul>
                                <li> [Fixed] 10+ reported bugs.</li>
                                <li> [Fixed] security issue.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.3
                                <small>30 May 2019</small></h6>
                            <ul>
                                <li> [Added] Manage currencies from admin panel, add any currency, remove, delete, one currency for all, pro, ads and market.</li>
                                <li> [Added] the ability to comment on albums, and multi images.</li>
                                <li> [Added] filter comments, top and latest. </li>
                                <li> [Added] the ability to make forums, marketplace and events public and reachable by google. </li>
                                <li> [Added] the ability to enable / disable PayPal payment method. </li>
                                <li> [Added] the ability to disable a language without deleting it. </li>
                                <li> [Added] the ability to enable / disable pokes, and "good monring" message. </li>
                                <li> [Added] the ability for users to make comment on post before sharing it. </li>
                                <li> [Added] the ability to block a domain from email while siging up, example, blocking @gmail.com </li>
                                <li> [Added] embeded product style to messages. </li>
                                <li> [Added] colored posts, with the ability to manage, add, remove and edit them. </li>
                                <li> [Added] 2Checkout payment method. </li>
                                <li> [Added] search on admin panel.</li>
                                <li> [Changed] password hash from sha1 to password_hash encryption. </li>
                                <li> [Improved] ajax speed by reducing requests.php file size and seperating the requests.</li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] API issues.</li>
                                <li> [Fixed] security issue.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.2.2
                                <small>12 April 2019</small></h6>
                            <ul>
                                <li> [Added] deepsound embed feature, now you can embed the player from deepsound to wowonder.</li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] security issue.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.2.1
                                <small>6 April 2019</small></h6>
                            <ul>
                                <li> [Added] support for PHP 7.3+</li>
                                <li> [Fixed] 30+ reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.2
                                <small>1 April 2019</small></h6>
                            <ul>
                                <li> [Added] The ability to add and manage genders from admin panel.</li>
                                <li> [Added] The ability to earn points by creating blogs. </li>
                                <li> [Added] points daily limit for pro and free users. </li>
                                <li> [Added] The ability to edit group chat info and avatar.</li>
                                <li> [Added] The ability to turn off messages from friends or everyone.</li>
                                <li> [Added] the ability to filter porn and nude pictures using Google Vision API.</li>
                                <li> [Added] user will require to verfiy his email if he changed is from settings page, if email verfication is enabled.</li>
                                <li> [Added] new sharing system, with new style and the abiltiy to share to timeline, group and pages.</li>
                                <li> [Added] the ability to manage pro packages name, icon, features, prices, and disable which one of them</li>
                                <li> [Added] the ability to manage pages, groups, products and blog categories from admin panel > manage features + seperated.</li>
                                <li> [Added] the ability to view the reactions, likes, dislikes on comments and replies.</li>
                                <li> [Added] the ability to view reactions, likes of posts on new model.</li>
                                <li> [Added] bank payments for wallet and pro.</li>
                                <li> [Added] group chat API, albums API, Pokes API and few other APIs. </li>
                                <li> [Added] group chat notifications.</li>
                                <li> [Added] the ability to delete a user posts by one click from admin panel. </li>
                                <li> [Added] recaptcha to contact us from. </li>
                                <li> [Added] new message page design for default theme.</li>
                                <li> [Fixed] few important bugs.</li>
                                <li> [Fixed] secuity threat, URGENT an update is required.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.1.1
                                <small>29 January 2019</small></h6>
                            <ul>
                                <li> [Added] Download my information, user can download personal info, pages, groups, posts and friends.</li>
                                <li> [Fixed] few important bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.1
                                <small>20 January 2019</small></h6>
                            <ul>
                                <li> [Added] new theme, "sunshine".</li>
                                <li> [Added] new story system for both themes. </li>
                                <li> [Added] filter system on marketplace, on the new theme. </li>
                                <li> [Added] hashtag posts count, on new theme.</li>
                                <li> [Fixed] few bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.3.1
                                <small>30th Octobar 2018</small></h6>
                            <ul>
                                <li> [Fixed] few important bugs in wallet system and other major bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.3
                                <small>16th Octobar 2018</small></h6>
                            <ul>
                                <li> [Added] confirmation system when user login from new location. </li>
                                <li> [Added] two-factor authentication system using email or phone. </li>
                                <li> [Fixed] few bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.2
                                <small>9th Octobar 2018</small></h6>
                            <ul>
                                <li> [Added] new video player. </li>
                                <li> [Added] the ability to disable / enable google maps.</li>
                                <li> [Added] the ability for admin to top up any user wallet.</li>
                                <li> [Added] IP to session manager.</li>
                                <li> [Added] the ability to disable / enable comments on each post.</li>
                                <li> [Fixed] 9 reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0.1
                                <small>5th Octobar 2018</small></h6>
                            <ul>
                                <li> [Fixed] 11 reported bugs. </li>
                                <li> [Improved] Script speed.</li>
                                <li> [Fixed] important security vulnerability.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v2.0
                                <small>30th Sep 2018</small></h6>
                            <ul>


<li>[Added] digitalocean spaces storage.
</li>
<li>[Added] poke system.
</li>
<li>[Added] reaction system (Like, Haha, wow, angry, love).
</li>
<li>[Added] gift system, users can send each other gifts.
</li>
<li>[Added] statics and charts to daily ads views / clicks.
</li>
<li>[Added] Infobip to SMS providers.
</li>
<li>[Added] stripe to wallet system like on go pro page.
</li>
<li>[Added] password recovery by phone number.
</li>
<li>[Added] estimated user reach on create ads page.
</li>
<li>[Added] bitcoin (coinpayments) payment method for ads and pro system.
</li>
<li>[Added] Payment Transactions history for wallet topups and pro system, with the ability to turn this feature on or off.
</li>
<li>[Added] the option to change the phone number from settings page.
</li>
<li>[Added] popular posts page.
</li>
<li>[Added] photos & videos sections to profile.
</li>
<li>[Added] End video chat button.
</li>
<li>[Added] ability to use percentage in the affiliate system.
</li>
<li>[Added] telegram to share options.
</li>
<li>[Added] admin can disable and enable social share links.
</li>
<li>[Added] more emojies.
</li>
<li>[Added] shortkey for posts, clicking "j" to scroll to next post.
</li>
<li>[Added] points system, user can earn points for posts, comments, likes, dislikes, wonders, and reactions. (User can spend points on pro or ads, or he can requst them as dollars).
</li>
<li>[Added] stickers to chat and messages.
</li>
<li>[Added] rotate system for images.
</li>
<li>[Added] Manage developer applications from admin panel.
</li>
<li>[Added] Report comment to admin.
</li>
<li>[Added] Advanced search system for custom fields.
</li>
<li>[Added] Added filter by age, and verfied to the search system.
</li>
<li>[Added] suggested groups / pages in my groups and my pages.
</li>
<li>[Added] search system in blog.
</li>
<li>[Added] auto friend system (Auto follow / friend with new registred users).
</li>
<li>[Added] the ability to view mutual friends from the profile (friends system).
</li>
<li>[Added] the ability to know who viewed your stories via notifications.
</li>
<li>[Added] ReCaptcha check to forgot password form (secuirty).
</li>
<li>[Added] blog comment notifications.
</li>
<li>[Added] Email notification when the user's account was deleted.
</li>
<li>[Added] a warning message before unfriending someone.
</li>
<li>[Added] session manager (users can view / manage browser / platforms where they are logged in).
</li>
<li>[Added] notification management system (Users can choose what kind of notifications they want to get).
</li>
<li>[Added] the ability to add followers to a specific user using IDs, in Admin > Users (Enabled just in follow system).
</li>
<li>[Added] blacklist system, admin can blacklist emails, usernames, and IP addresses.
</li>
<li>[Added] activities system, user can view his own activities from his profile (like, dislike, react, wonder, comment, reply, follow, friends).
</li>
<li>[Added] the ability for a user to choose if their profile should be found/indexed by search engines.
</li>
<li>[Improved] load speed.
</li>
<li>[Compressed] JS files to few less files.
</li>
<li>[Fixed] bugs on API.
</li>
<li>[Fixed] major bugs in the script. (+10)
</li>
<li>[Fixed] 3 security issues.</li>


                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.6.2
                                <small>27th Jun 2018</small></h6>
                            <ul>
                                <li> [Added] New welcome page for the default theme. </li>
                                <li> [Added] Wasabi storage support.</li>
                                <li> [Upgraded] PHPMailer to v6.</li>
                                <li> Fixed 10+ reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.6.1
                                <small>13th Jun 2018</small></h6>
                            <ul>
                                <li> [Added] Day status to default theme (good morning etc).</li>
                                <li> [Improved] wonderful theme design and forms.</li>
                                <li> [Improved] publisher box stability.</li>
                                <li> [Removed] Weather plugin from wonderful theme due copyright issues.</li>
                                <li> Fixed 10+ reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
              <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.6
                                <small>27th May 2018</small></h6>
                            <ul>
                                <li> [Added] FTP client server to store files, images, videos on other servers.</li>
                                <li> [Added] GDPR compliance (cookie frame, checkboxes, privacy policy)</li>
                                <li> [Added] full new APIv2 + docs.</li>
                                <li> [Added] the ability to edit movies from admin panel.</li>
                                <li> [Added] the abilty to post mobile emojies on posts, comments, and messages.</li>
                                <li> [Added] Auto delete system for users and posts that are longer than X date.</li>
                                <li> [Added] Crop system for user avatar.</li>
                                <li> [Translated] all page's titles.</li>
                                <li> [Improved] load post speed on wonderful theme.</li>
                                <li> [Fixed] 3 security issues.</li>
                                <li> [Fixed] 50+ reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5.3
                                <small>17th April 2018</small></h6>
                            <ul>
                                <li> Added two keys for OneSignal.</li>
                                <li> Added video call API for mobile applications.</li>
                                <li> Improved the cache system for user data.</li>
                                <li> Fixed all reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5.2
                                <small>6th April 2018</small></h6>
                            <ul>
                                <li> Improved content load and server load 50% faster.</li>
                                <li> Fixed all reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5.1
                                <small>29th March 2018</small></h6>
                            <ul>
                                <li> Fixed facebook / google login issues.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.5
                                <small>20th March 2018</small></h6>
                            <ul>
                                <li> Added new theme (default).</li>
                                <li> Fixed issues & high security vulnerability.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4.3
                                <small>30th January 2018 (Important update!)</small></h6>
                            <ul>
                                <li> Fixed issues & high security vulnerability.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4.2
                                <small>4th January 2018</small></h6>
                            <ul>
                                <li> Added Indian currency.</li>
                                <li> Added new API for movies, stories.</li>
                                <li> Fixed 7+ important reported bugs.</li>
                                <li> Script stability checkout.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4.1
                                <small>22th December 2017</small></h6>
                            <ul>
                                <li> Added Cache-Control to Amazon hosted files.</li>
                                <li> Fixed 5+ important reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.4
                                <small>13th December 2017</small></h6>
                            <ul>
                                <li> Added the ability for users to send money to each other using their wallet balance. </li>
                                <li> Added Email messages notification for offline users. </li>
                                <li> Added the ability to import images from links in post system. </li>
                                <li> Added profile percentage system. (Fill your profile details for new users). </li>
                                <li> Added new pagination system with a search feature to admin panel (Users, Pages, Groups, Posts).</li>
                                <li> Added new ads placed in the ads system (Users can create ads on videos posts).</li>
                                <li> Added Iframe support for the forum Editor. </li>
                                <li> Added share to wowonder button to blogs.</li>
                                <li> Added the ability for users to choose a default thumb when uploading a video in publisher box.</li>
                                <li> Added playtube video player integration.</li>
                                <li> Changed video player to mediaelement.js </li>
                                <li> Expired events will be deleted automatically.</li>
                                <li> Hid admin details in mass notification system and replaced it with site favicon/name.</li>
                                <li> Changed the blog system design.</li>
                                <li> Fixed 7+ reported bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.3.2
                                <small>15th November 2017</small></h6>
                            <ul>
                                <li> Added more regions to Amazon S3. </li>
                                <li> Added explore link to left sidebar. </li>
                                <li> Fixed 15+ reported bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.3.1
                                <small>21th October 2017</small></h6>
                            <ul>
                                <li> Added custom currency for the ads system. </li>
                                <li> Added web push notifications. </li>
                                <li> Added custom CSS / JS code to admin panel. </li>
                                <li> Fixed 10+ reported bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.3
                                <small>1st October 2017</small></h6>
                            <ul>
                                <li> Added new powerful admin panel. </li>
                                <li> Added push notification system for all site notifications. </li>
                                <li> Added the abiltiy to disable wonder/dislike buttons. </li>
                                <li> Added new API files, find friends, events, stories create groups pages and events. </li>
                                <li> Added support for Opera mini and UC browsers. </li>
                                <li> Fixed 15+ reported bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.2
                                <small>4th September 2017</small></h6>
                            <ul>
                                <li> Added privacy option for users “Share my location with public?”. </li>
                                <li> Added friends stories to home page. </li>
                                <li> User now can view his own ads. </li>
                                <li> Added the option to upload images to blog system. </li>
                                <li> Added multi currency in classified. </li>
                                <li> Added video chat API for the windows application. </li>
                                <li> Added ads prices in craete ads page. </li>
                                <li> Improved the ads view design. </li>
                                <li> Improved admin panel, changed tables to datatable.js </li>
                                <li> User can't create ads if wallet is empty. </li>
                                <li> Fixed 40+ reported bugs / improvements. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5.1
                                <small>27th August 2017</small></h6>
                            <ul>
                                <li> Fixed all reported bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.5
                                <small>24th August 2017</small></h6>
                            <ul>
                                <li> Added advertisement system. (Clicks, impressions) </li>
                                <li> Added story system. (status, automatically gets removed after 24 hours).  </li>
                                <li> Added new comment system for blogs and movies. </li>
                                <li> Added group chat system. </li>
                                <li> Added mass notification system in the admin panel. </li>
                                <li> Added the ability to edit comment's replies. </li>
                                <li> Added the ability to delete posts directly from home page (admins). </li>
                                <li> Added the ability to delete any comment (admins). </li>
                                <li> Added hide posts feature. </li>
                                <li> Added 30+ more emojis. </li>
                                <li> Added full verification form (ID, photo, description). </li>
                                <li> Added new post sharing system. </li>
                                <li> Added sitemap generator. </li>
                                <li> Added registration invite system (Users can register just with invite link). </li>
                                <li> Added new albums style (Collapsed). </li>
                                <li> Added new admin panel sidebar (Collapsed). </li>
                                <li> Added the ability to choose specific users in Mailing List. </li>
                                <li> Added the ability to enable/disable ads system, story system. </li>
                                <li> Added manage ads, stories (status) in the admin panel. </li>
                                <li> Added "Who can see my friends" privacy option. </li>
                                <li> Added multi date formats support. </li>
                                <li> Added the ability to lose the verification if the username was changed. </li>
                                <li> Added youtube/video link support for movies system. </li>
                                <li> Added multi admins for groups and pages. </li>
                                <li> Added gifs using "Giphy" API for messages/posts. </li>
                                <li> Added API support for upcoming IOS application. </li>
                                <li> Added Lightbox for images on messages, comments, and replies. </li>
                                <li> Added page rate system, users can rate page from 0/5. </li>
                                <li> Added report system for profiles, pages, and groups. </li>
                                <li> Added new API for the new powerful windows desktop application. </li>
                                <li> Added family members list (add a friend as a brother, father etc..) </li>
                                <li> Added relationship assignment, e.g: Lisa is in a relationship with Zach </li>
                                <li> Added find friends nearby (find friends near you within 100KM). </li>
                                <li> Added alert feedback if file mime type/extension is not supported. </li>
                                <li> Added alert if the file is larger than the max allowed size in publisher box, messages and chat. </li>
                                <li> Upgraded Password hash system from MD5 to SHA1 </li>
                                <li> Changed the trending system to be updated weekly. </li>
                                <li> Updated font-awesome library. </li>
                                <li> Updated emojis library. </li>
                                <li> Fixed bugs on API. </li>
                                <li> Fixed major bugs in the script. (+30) </li>
                                <li> Improved load speed. </li>
                                <li> Fixed 2 security issues. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.5.2
                                <small>18th June 2017</small></h6>
                            <ul>
                                <li> Added audio recording to Post/Comment systems.  </li>
                                <li> Upgraded the API to the newest version for the new android messenger update.  </li>
                                <li> Fixed bugs in the script.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.5.1
                                <small>6th June 2017</small></h6>
                            <ul>
                                <li> Added movies system. </li>
                                <li> Added translate system for posts. </li>
                                <li> Added video views system. </li>
                                <li> Fixed twilio SMS bug. </li>
                                <li> Fixed bugs in the native app API. </li>
                                <li> Fixed few bugs in the script. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.5
                                <small>25th May 2017</small></h6>
                            <ul>
                                <li> Added forum system. </li>
                                <li> Added events system.  </li>
                                <li> Added "Login with WoWonder" API feature + applications + documentation.   </li>
                                <li> Added "load more" button to the advanced search page.   </li>
                                <li> Added "Share to wowonder" button for third-party websites + documentation.    </li>
                                <li> Added custom chat colors for each conversation.   </li>
                                <li> Added push notifications support for Android messenger.   </li>
                                <li> Fixed video/audio call bugs.  </li>
                                <li> Fixed bugs in the native app API.   </li>
                                <li> Fixed few bugs in the script.  </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.5
                                <small>11th April 2017</small></h6>
                            <ul>
                                <li> Added blog system. </li>
                                <li> Final release for full API system (for native apps). </li>
                                <li> Fixed few bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.4
                                <small>2nd March 2017</small></h6>
                            <ul>
                                <li> Added auto-updater system. </li>
                                <li> Added windows server rewrite URL support (web.config). </li>
                                <li> Fixed few bugs in the API. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.3
                                <small>23th February 2017</small></h6>
                            <ul>
                                <li> Improved the script theme.</li>
                                <li> Upgraded jQuery library. </li>
                                <li> Increased script speed. </li>
                                <li> Fixed few bugs in the API. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.2
                                <small>10th February 2017</small></h6>
                            <ul>
                                <li> Updated API for IOS messenger.</li>
                                <li> Fixed few bugs in the script. </li>
                                <li> Fixed few bugs in the API. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4.1
                                <small>27th January 2017</small></h6>
                            <ul>
                                <li> Updated Hybridauth library (Facebook login bug). </li>
                                <li> Fixed more than +3 other bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.4
                                <small>11th January 2017</small></h6>
                            <ul>
                                <li> Added "Read more" to product description. </li>
                                <li> Added custom currency option for classified. </li>
                                <li> Added custom mime types option to admin panel. </li>
                                <li> Updated PHPmailer library (Security bug).</li>
                                <li> Updated Hybridauth library (Google+ login bug). </li>
                                <li> Fixed "copyright" text in footer. </li>
                                <li> Fixed RTL design problems. </li>
                                <li> Fixed UTF-8 issues in hashtag system. </li>
                                <li> Fixed JavaScript code bugs in Apple products. </li>
                                <li> Fixed Android / Windows messengers API requests. </li>
                                <li> Optimized admin panel. </li>
                                <li> Fixed more than +5 other bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.3
                                <small>8th December 2016</small></h6>
                            <ul>
                                <li> Added the ability to translate custom fields. </li>
                                <li> Added the ability to add/edit/remove languages from admin panel. </li>
                                <li> Added audio calls. </li>
                                <li> Added integration with the new <a href="https://codecanyon.net/item/wowonder-android-messenger-mobile-application-for-wowonder/19034167?s_rank=1">WoWonder Android Messenger</a>.</li>
                                <li> Added the ability to manage pro membership periods. </li>
                                <li> Added a button to manage and cancel expired pro users. </li>
                                <li> Added Twilio API for sending SMS messages. </li>
                                <li> Added android API for the upcoming native apps. </li>
                                <li> Added Alipay to Stipe. </li>
                                <li> Added hashtag post streaming. </li>
                                <li> Added YouTube field to page social link settings. </li>
                                <li> Added location field to classified system. </li>
                                <li> Improved database structure. </li>
                                <li> Improved SQL queries. </li>
                                <li> Improved script speed. </li>
                                <li> Design/Code optimization. </li>
                                <li> Fixed bugs in messages system. </li>
                                <li> Fixed few bugs. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.2
                                <small>10th October 2016</small></h6>
                           <ul>
                                <li> Added Amazon S3 integration. </li>
                                <li> Added the ability to delete full conversations. </li>
                                <li> Added the ability to delete recipient messages. </li>
                                <li> Added Nginx support. </li>
                                <li> Fixed an issue in login system. </li>
                                <li> Fixed an issue while deleting a page from admin panel. </li>
                                <li> Fixed few more bugs. </li>
                           </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4.1
                                <small>3rd October 2016</small></h6>
                            <ul>
                                <li> More than 10+ old and new bug fixes. </li>
                                <li> Design/Code optimization. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.4
                                <small>25th September 2016</small></h6>
                            <ul>
                                <li>Added new welcome page. </li>
                                <li>Added custom fields system. </li>
                                <li>Added classified system. </li>
                                <li>Added full affiliates system + payments. </li>
                                <li>Added poll system. </li>
                                <li>Added custom pages system. </li>
                                <li>Added more payment methods, (Credit card, Bitcoin, american express). </li>
                                <li>Added YouTube field to social links. </li>
                                <li>Added integration with the new <a href="https://codecanyon.net/item/wowonder-desktop-a-windows-messenger-for-wowonder/18029772">Windows Desktop Messenger</a>. </li>
                                <li>Added new posts updater system (Like twitter). </li>
                                <li>Added image on comments system. </li>
                                <li>Added full messaging API code for windows / Android / IOS. </li>
                                <li>Added CSRF protection for more forms / ajax requests. </li>
                                <li>Added terms link to registration page. </li>
                                <li>Added the option to enable/disable notification sound. </li>
                                <li>Added the option for user to filter posts by all or following. </li>
                                <li>Added more ad placements (between posts). </li>
                                <li>Added 'latest products' placement in sidebar. </li>
                                <li>Added longer user session time. </li>
                                <li>Added new design for messages system. </li>
                                <li>Added custom backgrounds for pages. </li>
                                <li>Replaced the URL scrape system with better one. </li>
                                <li>Re-coded style.css file to .scss for easy coding and outputting. </li>
                                <li>Speed/Design/Code optimization. </li>
                                <li>Fixed Hashtag issues. </li>
                                <li>Fixed birthday privacy issue. </li>
                                <li>Fixed image rotation issue. </li>
                                <li>Fixed image cropping issues. </li>
                                <li>Fixed session hijacking security.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.4
                                <small>27th June 2016</small></h6>
                            <ul>
                                <li> Fixed all reported bug. </li>
                                <li> Increased the script speed by 50%. </li>
                                <li> Design/Code optimization. </li>
                                <li> Upgraded the image optimization system to next level. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.3
                                <small>19th June 2016</small></h6>
                            <ul>
                                <li> Added video call/chat system for all devices. </li>
                                <li> Added the option to view all posts or following posts. </li>
                                <li> Added the option to enable/disable "developers" page. </li>
                                <li> Added the option to enable/disable user registration. </li>
                                <li> Added "maintenance_mode" to shut down the whole site. </li>
                                <li> Added the option to send mailing list to "active, inactive, all" users. </li>
                                <li> Added "disabled button" background color to admin panel. </li>
                                <li> Added dropdown menu for messages button in header. </li>
                                <li> Added gender field for Facebook social login. </li>
                                <li> Added max posts/pages boosts allowed for per pro user to admin panel. </li>
                                <li> Added "eapi link" for sending SMS. </li>
                                <li> Added multi chat tabs (max 3 tabs). </li>
                                <li> Added the option to change favicon from admin panel. </li>
                                <li> Added CSRF protection for few more forms. </li>
                                <li> Upgraded chat system + messages. </li>
                                <li> Updated API to v1.3.1 </li>
                                <li> Optimized admin panel layout. </li>
                                <li> Fixed few bugs. </li>
                                <li> Speed/Design/Code optimization. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.2
                                <small>17th May 2016</small></h6>
                            <ul>
                                <li> Added the ability enable/disable games, pages, groups. </li>
                                <li> Added full backup system, (backup your files, database, uploads easily with one click via admin panel). </li>
                                <li> Added more currency types for payments, (RUB, PLN, ILS, BRL). </li>
                                <li> Added pull to refresh to android application. </li>
                                <li> Added test log for PayPal configuration. </li>
                                <li> Speeded up loading time. </li>
                                <li> Fixed redirection issue, (www or without www). </li>
                                <li> Fixed default language on sign up. </li>
                                <li> Fixed common bugs. </li>
                                <li> Script optimization. </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3.1
                                <small>24th April 2016</small></h6>
                            <ul>
                                <li> Added more currency types for payments.</li>
                                <li> Added the ability for groups admin to delete users posts.</li>
                                <li> Added Portuguese language.</li>
                                <li> Added 2 new design types to admin panel for header, (header input text, buttons text shadow).</li>
                                <li> Added send button to comment field. (On mobile) </li>
                                <li> Fixed common bugs.</li>
                                <li> Fixed security bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.3
                                <small>21th April 2016</small></h6>
                            <ul>
                                <li> Added SMS verification system (verify user by phone number).</li>
                                <li> Added premium members (Star - Hot - Utlima - Vip) with PayPal / credit card integration.</li>
                                <li> Added Android, IOS, and Windows Phone apps (web-view).</li>
                                <li> Added cover re-position feature.</li>
                                <li> Added birthday events on home page.</li>
                                <li> Added the ability to boost posts & pages with monthly payments.</li>
                                <li> Added post limit p/ hour for every user.</li>
                                <li> Added registration limit p/ hour for every IP.</li>
                                <li> Added custom CSS file for every user (user can completely re-design his own profile).</li>
                                <li> Added Video.JS/Audio.JS for video & audio players.</li>
                                <li> Added new speed for all action, (follow, add friend, chat, like, dislike, wonder, join etc ..).</li>
                                <li> Added desktop notifications for Google Chrome / FireFox.</li>
                                <li> Added the ability to upload .mov, .flv, .mpeg Videos.</li>
                                <li> Added CSRF protection for common forms.</li>
                                <li> Added user ranks, admin - moderator - user.</li>
                                <li> Added send button to messages.</li>
                                <li> Added top featured users bar (applying by paying).</li>
                                <li> Added online users list to admin panel.</li>
                                <li> Added invite system.</li>
                                <li> Added og-Meta tags for social sharing.</li>
                                <li> Added new loading system (loading content without refreshing the page) & bandwidth saver system.</li>
                                <li> Added new E-mail notification system.</li>
                                <li> Added block system.</li>
                                <li> Added new sources for games importing.</li>
                                <li> Optimized layout.</li>
                                <li> Speeded up SMTP.</li>
                                <li> Replaced cache system.</li>
                                <li> Removed /welcome from welcome page URL.</li>
                                <li> Updated API to v1.3.</li>
                                <li> Script & code optimization.</li>
                                <li> SEO optimization.</li>
                                <li> Improved chat system usage of resources.</li>
                                <li> Increased site security (XSS, CSRF, SQL, Spams).</li>
                                <li> Fixed default country (USA).</li>
                                <li> Fixed common bugs.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.3
                                <small>26th February 2016</small></h6>
                            <ul>
                                <li> Added SMTP server.<br>
                                <li> Added Login with username or email.</li>
                                <li> Added Build Version to admin panel.</li>
                                <li> Fixed major bugs.</li>
                                <li> Improved Security.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.2
                                <small>29th January 2016</small></h6>
                            <ul>
                                <li> Added auto suggestion for mentions in publisher box, comments, replies.</li>
                                <li> Added Start up pages (Add photo, Fill some information, Follow users).</li>
                                <li> Added terms pages to admin panel. (Admin can now edit terms pages from admin panel).</li>
                                <li> Added video, audio upload setting to admin panel.</li>
                                <li> Added welcome background image changer to admin panel.</li>
                                <li> Added site design colors to email notification.</li>
                                <li> Added user profile privacy for non-logged users.</li>
                                <li> Added smiles button to comment, send message boxs.</li>
                                <li> Added installer for easy installation.</li>
                                <li> Fixed Bugs from your feedback.</li>
                                <li> Script Optimization.</li>
                                <li> Improved Speed.</li>
                                <li> Improved Security.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2.1
                                <small>12th January 2016</small></h6>
                            <ul>
                                <li> Added words wonder, dislike, like to the post action buttons.</li>
                                <li> Added the ability to just like or dislike. (can't do it both).</li>
                                <li> Re added emotions to post publisher box. </li>
                                <li> Optimized chat requests.</li>
                                <li> Fixed bugs from your feedback.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.2
                                <small>10th January 2016</small></h6>
                            <ul>
                                <li> Added group system</li>
                                <li> Added game system</li>
                                <li> Added dislike button (wonder or dislike)</li>
                                <li> Added new lightbox</li>
                                <li> Added login via Instagram</li>
                                <li> Added verification request system</li>
                                <li> Added photo album system</li>
                                <li> Added multi photos upload</li>
                                <li> Added autoload system for posts</li>
                                <li> Added new search system</li>
                                <li> Added recent searches</li>
                                <li> Added page invitation system</li>
                                <li> Added group invitation system</li>
                                <li> Added ban ip system</li>
                                <li> Added feelings/travailing/watching/playing/listening post status</li>
                                <li> Added call to action system for pages</li>
                                <li> Added online user counter on admin & home page</li>
                                <li> Added location autocomplete for user/page setting</li>
                                <li> Added design system (Customize your own website style & colors on very easy way from admin panel)</li>
                                <li> Added recent searches</li>
                                <li> Added notification popup</li>
                                <li> Added profile visit privacy</li>
                                <li> Added last seen privacy</li>
                                <li> Added profile birthday privacy</li>
                                <li> Added auto detector for Youtube, Dailymotion, Vine, Vimeo, Facebook videos & soundcloud links.</li>
                                <li> Added https support</li>
                                <li> Added comment replies system</li>
                                <li> Added comment auto detector</li>
                                <li> Added education to user profile information</li>
                                <li> Added the ability to like/dislike/wonder/comment on user's profile picture & cover image</li>
                                <li> Added email notification setting</li>
                                <li> Added site statistics charts in admin panel</li>
                                <li> Added ip address field to manage users page</li>
                                <li> Added new language (Italian)</li>
                                <li> Removed "@" from user profile URL</li>
                                <li> Removed "p/" from page URL</li>
                                <li> Removed "/home" from home page URL</li>
                                <li> Changed the entire admin panel layout</li>
                                <li> Changed the entire user/page/group setting layout</li>
                                <li> Improved user popover</li>
                                <li> Improved layout</li>
                                <li> Improved layout on smartphones</li>
                                <li> Improved chat system</li>
                                <li> Improved site security</li>
                                <li> Improved link preview</li>
                                <li> Improved cache system to a higher level</li>
                                <li> Updated API version to v1.1</li>
                                <li> Script optimization</li>
                                <li> Bug fixes </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.1
                                <small>8th December 2015</small></h6>
                            <ul>
                                <li> Added Page System.</li>
                                <li> Added Link Preview.</li>
                                <li> Added User Typing System & Message "Seen" System.</li>
                                <li> Added Profile Custom fields (Work, Company, Relationship, Location .. etc).</li>
                                <li> Added Profile Google Map location.</li>
                                <li> Added Profile Background image. (user can choose his own background image).</li>
                                <li> Added Facebook, Vimeo, Dailymotion videos.</li>
                                <li> Added User Details On Hovering on user link.</li>
                                <li> Added Censored Words System.</li>
                                <li> Added 4 New Languages (Dutch, German, Spanish, French).</li>
                                <li> Added Search Posts System.</li>
                                <li> Added HTML Support For Announcements.</li>
                                <li> Changed Welcome Page Style.</li>
                                <li> Changed Sidebar Style.</li>
                                <li> Improved Layout & Styles.</li>
                                <li> Improved Layout On Smartphones.</li>
                                <li> Improved Admin Panel Layout.</li>
                                <li> Added More features for Sending emails to all users.</li>
                                <li> Script Optimization.</li>
                                <li> Fixed Bugs.</li>
                                <li> Improved Security.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">v1.0 <small></small> </h6>
                            Version 1.0 released on 26 November 2015.
                        </div>
                    </div>
                </div>
            </div>
        </div>
