<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 singlecol">
			<div class="wo_my_pages">
				<div class="my_pages_header row">
					<ul class="<?php echo Wo_RightToLeft('pull-left'); ?>">
						<?php if ($wo['config']['can_use_market']) { ?>
						<li><a href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" data-ajax="?link1=my-products"><?php echo $wo['lang']['my_products'] ?></a></li>
						<?php } ?>
						<?php if ($wo['config']['store_system'] == 'on') { ?>
							<li><a href="<?php echo Wo_SeoLink('index.php?link1=purchased'); ?>" data-ajax="?link1=purchased"><?php echo $wo['lang']['purchased'] ?></a></li>
							<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=orders'); ?>" data-ajax="?link1=orders"><?php echo $wo['lang']['orders'] ?></a></li>
						<?php } ?>
						<li><a href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>" data-ajax="?link1=products"><?php echo $wo['lang']['market'] ?></a></li>
					</ul>
				</div>
				<div class="sun_terms my_purchased_content">
					<?php if (!empty($wo['orders']) && count($wo['orders']) > 0): ?>
						<div class="row">
							<?php echo($wo['html']); ?>
						</div>

						<?php if (count($wo['orders']) == 10){ ?>
							<div class="load-more">
								<button class="btn btn-default text-center wo_load_more" onclick="Wo_LoadOrders();">
									<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></span> <?php echo $wo['lang']['load_more']; ?>
								</button>
							</div>
							<?php } ?>
					<?php else: ?>
						<?php echo($wo['html']); ?>
					<?php endif; ?>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- .row -->
</div>