<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists singlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_menu">
						<ul class="list-unstyled">
							<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=apps'); ?>" data-ajax="?link1=apps">My Apps</a></li>
						</ul>
						<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-app');?>" data-ajax="?link1=create-app"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <?php echo $wo['lang']['create'] ?></a>
					</div>
				</div>
			</div>
			
			<div class="wo_my_pages">
				<div class="row">
					<?php
						$apps = Wo_GetAppsData();
						if (count($apps) > 0) {
							foreach ($apps as $wo['app']) {
								echo Wo_LoadPage('graph/app-list');
							}
						} else {
							echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5,3H19A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5A2,2 0 0,1 3,19V5A2,2 0 0,1 5,3M7,7V9H9V7H7M11,7V9H13V7H11M15,7V9H17V7H15M7,11V13H9V11H7M11,11V13H13V11H11M15,11V13H17V11H15M7,15V17H9V15H7M11,15V17H13V15H11M15,15V17H17V15H15Z" /></svg> No applications found</div>';
						}
					?>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<?php //echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>