<div class="wo_settings_page sun_sett_page">
	<a href="javascript:void(0)" class="btn btn-main btn-sm <?php echo Wo_RightToLeft('pull-right');?>" onclick="NewProjects()"><?php echo $wo['lang']['add_new']; ?></a>
	<h3><?php echo $wo['lang']['projects']; ?></h3>
	<br>

	<div>
		<?php 
			if (!empty($wo['projects_html'])) {
				echo $wo['projects_html'];
			}
			else{
				echo '<div class="search-filter-center-text empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M17,9H7V7H17M17,13H7V11H17M14,17H7V15H14M12,3A1,1 0 0,1 13,4A1,1 0 0,1 12,5A1,1 0 0,1 11,4A1,1 0 0,1 12,3M19,3H14.82C14.4,1.84 13.3,1 12,1C10.7,1 9.6,1.84 9.18,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3Z"></path></svg>' . $wo['lang']['no_available_data'] . '</div>';
			}
		?>
	</div>
</div>

<script type="text/javascript">
	function NewProjects() {
	  $('.modal_add_project_modal_alert').empty();
	  $("#add_project_modal").find('.btn-mat').removeAttr('disabled')
	  $("#add_project_modal").find('.btn-mat').text("<?php echo $wo['lang']['add'] ?>");
	  $('#add_project_modal').modal('show');
    $( ".project_start" ).datepicker({ dateFormat: 'yy-mm-dd',prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'});
    $( ".project_end" ).datepicker({ dateFormat: 'yy-mm-dd',prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'});
    var options = { 
    url: Wo_Ajax_Requests_File() + '?f=project&s=add&hash=' + $('.main_session').val() + "&mode_type=linkedin",
      beforeSubmit:  function () {
        $('.modal_add_project_modal_alert').empty();
        $("#add_project_modal").find('.btn-mat').attr('disabled', 'true');
        $("#add_project_modal").find('.btn-mat').text("<?php echo($wo['lang']['please_wait']) ?>");
      }, 
      success: function (data) {
        $("#add_project_modal").find('.btn-mat').text("<?php echo $wo['lang']['add'] ?>");
        $("#add_project_modal").find('.btn-mat').removeAttr('disabled')
        if (data.status == 200) {
          $('.modal_add_project_modal_alert').html('<div class="alert alert-success bg-success"><i class="fa fa-check"></i> '+
            data.message
            +'</div>');
            setTimeout(function (){
            	location.reload();
            }, 3000)
        } else {
          $('.modal_add_project_modal_alert').html('<div class="alert alert-danger bg-danger"> '+
          data.message
          +'</div>');
        } 
      }
  }; 
  $('.add_project_form').ajaxForm(options); 
	}
  function EditProject(id) {
		$('.modal_edit_project_modal_alert_'+id).empty();
		$("#edit_project_modal_"+id).find('.btn-mat').removeAttr('disabled')
		$("#edit_project_modal_"+id).find('.btn-mat').text("<?php echo $wo['lang']['edit']; ?>");
		$( ".edit_project_start_"+id ).datepicker({ dateFormat: 'yy-mm-dd',prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'});
    $( ".edit_project_end_"+id ).datepicker({ dateFormat: 'yy-mm-dd',prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'});
		$('#edit_project_modal_'+id).modal('show');
	}
	function DeleteProject(id,type = 'show') {
		if (type == 'hide') {
	      $('#delete-project').find('.btn-mat').attr('onclick', "DeleteProject('"+id+"')");
	      $('#delete-project').modal('show');
	      return false;
	    }
	    $('.project_'+id).slideUp();
		$('.project_'+id).remove();
		$('#edit_project_modal_'+id).remove();
		$.post(Wo_Ajax_Requests_File() + '?f=project&s=delete&hash=' + $('.main_session').val() + "&mode_type=linkedin", {id: id}, function(data, textStatus, xhr) {});
	}
</script>
