<div class="wo_ad_header_format list-group-forum sidebar-ad-wrapper-forum pointer rads-<?php echo $wo['sidebar-ad']['bidding']; ?>" id="<?php echo $wo['sidebar-ad']['id']; ?>">
    <div class="sidebar-ad-header-forum sidebar-title-back-forum sponsored"><?php echo $wo['lang']['sponsored'] ?></div>
    <div class="sidebar-ad-body-forum imgs">
        <img src="<?php echo $wo['sidebar-ad']['ad_media']; ?>" alt="Picture">
    </div>
    <div class="sidebar-ad-footer-forum details">
        <p class="ad-title-forum">
            <?php echo $wo['sidebar-ad']['headline']; ?>
        </p>
        <p class="small ad-descrition-forum ">
            <?php echo $wo['sidebar-ad']['description']; ?>
        </p>
        <time>
            <a href="<?php  echo $wo['sidebar-ad']['url'];?>" class="main-forum" target="_blank">
                <?php echo Wo_UrlDomain($wo['sidebar-ad']['url']); ?>
            </a>
        </time>
    </div>
</div>