<link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
<div class="container-fluid">
    <div>
        <h3>Add New Movie</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Manage Features</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Movies</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Add New Movie</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                	<h6 class="card-title">Add New Movie</h6>
                    
                    <form class="newforum" method="POST" id="new-film">
						<div class="row">
							<div class="col-md-4">
								<div class="d-flex align-items-center add-admn-movie" id="select-f-cover">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z" /></svg>
									<?php echo $wo['lang']['select'] ?>
								</div>
								<small class="admin-info">Movie thumbnail, required size: 400x570.</small>
							</div>
							<div class="col-md-8">
								<div class="form-group form-float">
									<div class="form-line">
										<label class="form-label">Movie Title</label>
										<input type="text" id="name" name="name" class="form-control">
										<small class="admin-info">Choose a title for the movie, max 23 characters allowed.</small>
									</div>
								</div>
								<div class="form-group form-float">
									<div class="form-line">
										<label class="form-label">Description</label>
										<textarea name="description" id="description" class="form-control" cols="30" rows="3"></textarea>
										<small class="admin-info">Choose a description for the movie, min 23 characters allowed.</small>
									</div>
								</div>
							</div>
						</div>
						<br>
                    	<div class="form-group form-float">
                            <div class="form-line">
                            	<label class="form-label">Movie Source</label>
                                <input type="text" id="embed_source" name="iframe" class="form-control" onchange="Wo_ToggleMoviewsSource(this)">
                                <small class="admin-info">Import a movie from other sites, Example: (youtube.com, vimeo.com, site.com/video.mp4)</small>
                            </div>
                        </div>
                        <div class="preview-utube-import hidden" style="margin-top: 25px;">
							<iframe width="100%" height="350px" src="" frameborder="0" allowfullscreen></iframe>
						</div>
						<div class="admin-or-divide">OR</div><br>
                         <div class="form-group form-float">
                            <div class="form-line">
								<div class="btn-file d-flex align-items-center">
									<input type="file" id="film" accept="video/*" name="source" value="C:\fakepath\source" class="hidden">
									<div class="mr-2 change-file-ico">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M16.5,6V17.5A4,4 0 0,1 12.5,21.5A4,4 0 0,1 8.5,17.5V5A2.5,2.5 0 0,1 11,2.5A2.5,2.5 0 0,1 13.5,5V15.5A1,1 0 0,1 12.5,16.5A1,1 0 0,1 11.5,15.5V6H10V15.5A2.5,2.5 0 0,0 12.5,18A2.5,2.5 0 0,0 15,15.5V5A4,4 0 0,0 11,1A4,4 0 0,0 7,5V17.5A5.5,5.5 0 0,0 12.5,23A5.5,5.5 0 0,0 18,17.5V6H16.5Z"></path></svg>
									</div>
									<div class="full-width">
										<b id="wowonder-movie-name">Upload Movie File</b>
										<small class="admin-info">MP4 only allowed.</small>
									</div>
								</div>
                            </div>
                        </div>
                        <br>
                        
                        <div class="form-group form-float">
                            <div class="form-line">
                            	<label class="form-label">Stars</label>
                                <textarea name="stars" id="stars" class="form-control" cols="30" rows="3"></textarea>
                                <small class="admin-info"><small>Set movie stars, separated by comma(,).</small></small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                            	<label class="form-label">Producer</label>
                                <input type="text" id="producer" name="producer" class="form-control">
                            </div>
                        </div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group form-float">
									<div class="form-line">
										<label class="form-label">Release</label>
										<input type="number" id="release" name="release" class="form-control" min="1960" max="<?php echo date('Y') ?>">
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group form-float">
									<div class="form-line">
										<label class="form-label">Duration</label>
										<input type="number" id="duration" name="duration" class="form-control" min="10" max="350">
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<label for="country">Country</label>
								<select class="form-control show-tick" id="country" name="country">
								<?php foreach ($wo['countries'] as $c_key => $c_value): ?>
									<option value="<?php echo $c_key; ?>"><?php echo $c_value; ?></option>
								<?php endforeach; ?>
								</select>
							</div>

							<div class="col-md-6">
								<label for="quanlity">Quality</label>
								<select class="form-control show-tick" id="quanlity" name="quanlity">
									<option value="cam">CAMRip</option>
									<option value="ts">TS</option>
									<option value="vsh">VHSRip</option>
									<option value="wp">WP</option>
									<option value="scr">SCR (VHSScr)</option>
									<option value="dvds">DVDScr</option>
									<option value="ts">TC</option>
									<option value="ldr">LDRip</option>
									<option value="tv">TVRip</option>
									<option value="sat">SATRip</option>
									<option value="dvb">DVBRip</option>
									<option value="dtv">DTVRip</option>
									<option value="dvd">DVD</option>
									<option value="hdr">HDRip</option>
									<option value="web-dl">WEB-DL</option>
									<option value="hd-tv">HD-TV</option>
									<option value="hd">HD DVD</option>
								</select>
							</div>
							<div class="col-md-6">
								<label for="genre">Genre</label>
								<select class="form-control show-tick" id="genre" name="genre">
								<?php foreach ($wo['film-genres'] as $g_key => $g_value): ?>
									<option value="<?php echo $g_key; ?>"><?php echo $g_value; ?></option>
								<?php endforeach;?>
								</select>
							</div>
							<div class="col-md-6">
								<div class="form-group form-float">
									<div class="form-line">
										<label class="form-label">Rating</label>
										<input type="number" id="rating" name="rating" class="form-control" min="1" max="10" step="0.1">
										<small class="admin-info">Movie rating, set a number from 1 to 10.</small>
									</div>
								</div>
							</div>
						</div>


                        <div class="clearfix"></div>
				         <div id="progress" style="display: none">
				            <span id="percent">0%</span>
				            <div class="progress">
				             <div id="bar" class="progress-bar progress-bar-striped active"></div> 
				            </div>
				            <div class="clear"></div>
				         </div>
				      <input type="file" class="hidden" name="cover" id="film-cover" accept="image/*">
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <div class="" id="film-alert"></div>
                        <div class="clearfix"></div>
                        <br>
                        <button type="submit" id="upload-film" class="btn btn-primary m-t-15 waves-effect">Create Movie</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
	
	<style type="text/css">
	.btn-file { position: relative; overflow: hidden;cursor: pointer;}
	.btn-file input[type=file] { position: absolute; top: 0; right: 0; min-width: 100%; min-height: 100%; font-size: 100px; text-align: right; opacity: 0; outline: none; background: #fff; cursor: inherit; display: block; }
	.change-file-ico {min-width: 36px;}
	.change-file-ico svg {border-radius: 50%;background: rgb(2 154 214 / 15%);color: #029ad6;padding: 7px;width: 36px;height: 36px;}
	.full-width {width: 100%;}
	#wowonder-movie-name {font-weight: normal;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;display: block;}
</style>
	
<script>
	$("#film").change(function () {
		var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
		$("#wowonder-movie-name").text(filename);
    });
	
	jQuery(document).ready(function($) {

		var bar = $('#bar');
	    var percent = $('#percent');
	    var status = $('#status');
	    var publisher_button = $('#publisher-button');
		$("#select-f-cover").click(function(event) {
	      $("#film-cover").click()
	    });

	    $("#film-cover").change(function(event) {
	      $("#select-f-cover").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'  class='w100'>")
	    });


	    $('#new-film').ajaxForm({
	      url: Wo_Ajax_Requests_File() + '?f=new-film',
	      beforeSend: function() {
	      	var percentVal = '0%';
	        bar.width(percentVal);
	        percent.html(percentVal);
	        $('#upload-film').text('Submitting..');
	      },
	      uploadProgress: function (event, position, total, percentComplete) {
           var percentVal = percentComplete + '%';
           bar.width(percentVal);
           $('#progress').slideDown(200);
           if(percentComplete > 50) {
             percent.addClass('white');
           }
           percent.html(percentVal);
         },
	      type:"POST",
	      success: function(data) {
	      	$('#upload-film').text('Create Movie');
	      	$("html, body").animate({ scrollTop: 0 }, "slow");
	        bar.width(0);
	        percent.html('0%');
	        $('#progress').slideUp(200);
	        if (data['status'] == 200) {
	          $("#film-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	          $('#new-film').resetForm();
	        } 
	        else if (data['message']) {
	          $("#film-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	      }});
	    $(".delete-film").click(function(event) {
	    	$("#delete-film").attr('data-film-ident', $(this).attr('id')).modal('show');
	    });
	});

	function Wo_IsURL(str) {
	  var pattern = new RegExp('^(https?:\\/\\/)?'+ 
	  '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.?)+[a-z]{2,}|'+ 
	  '((\\d{1,3}\\.){3}\\d{1,3}))'+ 
	  '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+ 
	  '(\\?[;&a-z\\d%_.~+=-]*)?'+ 
	  '(\\#[-a-z\\d_]*)?$','i'); 
	  return pattern.test(str);
	}

	function Wo_FilmMediaUrl(pastedData) {
		var success = false;
		var media   = {};
		if (GetYoutubeId(pastedData)) {

		    media.type  = "youtube";
		    media.id    = GetYoutubeId(pastedData);
		    success     = true;
		    $("#embed_source").attr('name', 'iframe');
		}

		else if (Wo_GetVimeoID(pastedData)) {
		    media.type  = "vimeo";
		    media.id    = Wo_GetVimeoID(pastedData);
		    success     = true;
		    $("#embed_source").attr('name', 'iframe');
		}

		else if (Wo_IsURL(pastedData)) {
		    media.type  = "other";
		    media.id    = pastedData;
		    success     = true;
		    $("#embed_source").attr('name', 'other');
		}

		if (success) { 
			return media; 
		}

		else { 
			alert("Not valid source id detected"); 
			return false;
		}
	}

	function  Wo_ToggleMoviewsSource(self = false) {
		if (!self || self.value.length == '') {
			$('#film').attr('disabled', false);
			return false;
		}
		$('#film').attr('disabled', true);
		var url_data = Wo_FilmMediaUrl(self.value);
		if (url_data && url_data.type == 'youtube') {
			var u_source = "https://www.youtube.com/embed/" + url_data.id;
			$(".preview-utube-import").removeClass('hidden').find('iframe').attr('src', u_source);
			self.value = u_source;
		}
		else if (url_data && url_data.type == 'vimeo') {
			var u_source = "https://player.vimeo.com/video/" + url_data.id;
			alert(u_source)
			$(".preview-utube-import").removeClass('hidden').find('iframe').attr('src', u_source);
			self.value   = u_source;
		}
		else if (url_data && url_data.type == 'other') {
			var u_source = url_data.id;
			var html = "\
			<div class='video-js-responsive-container vjs-hd'>\
			<video onplay='' class='video-js vjs-big-play-centered' controls preload='auto' poster='' data-setup='{}'>\
			    <source src='"+u_source+"' type='video/mp4'>\
			    <source src='"+u_source+"' type='video/webm'>\
			</video>\
			<script src='<?php echo $wo['config']['theme_url'];?>/player/Video/video.js'><\/script>\
			</div>\ ";
			$(".preview-utube-import").removeClass('hidden').html(html);
			self.value = u_source;
		}
	}


	function Wo_GetVimeoID(str) {

		if (str.indexOf('#') > -1) {
			str = str.split('#')[0];
		}

		if (str.indexOf('?') > -1) {
			str = str.split('?')[0];
		}

		var id;

		if (/https?:\/\/vimeo\.com\/[0-9]+$|https?:\/\/player\.vimeo\.com\/video\/[0-9]+$/igm.test(str)) {
			var arr = str.split('/');
			if (arr && arr.length) {
				id = arr.pop();
			}
		}
		return id;
	}




	function GetYoutubeId(str) {
		var shortcode = /youtube:\/\/|https?:\/\/youtu\.be\//g;

		if (shortcode.test(str)) {
			var shortcodeid = str.split(shortcode)[1];
			return Wo_StripParameters(shortcodeid);
		}
		var inlinev = /\/v\/|\/vi\//g;

		if (inlinev.test(str)) {
			var inlineid = str.split(inlinev)[1];
			return Wo_StripParameters(inlineid);
		}
		var parameterv = /v=|vi=/g;

		if (parameterv.test(str)) {
			var arr = str.split(parameterv);
			return arr[1].split('&')[0];
		}

		var embedreg = /\/embed\//g;

		if (embedreg.test(str)) {
			var embedid = str.split(embedreg)[1];
			return Wo_StripParameters(embedid);
		}

		var userreg = /\/user\//g;

		if (userreg.test(str)) {
			var elements = str.split('/');
			return Wo_StripParameters(elements.pop());
		}

		var attrreg = /\/attribution_link\?.*v%3D([^%&]*)(%26|&|$)/;

		if (attrreg.test(str)) {
			return str.match(attrreg)[1];
		}
	}
	 


	function Wo_StripParameters(str) {
		if (str.indexOf('?') > -1) {
			return str.split('?')[0];
		}

		return str;
	}
</script>