<div class="row">
	<div class="col-lg-1"></div>
	<div class="col-lg-10">
		<div class="page-margin wow_creads_minstp wow__minstp step-three-active">
			<div class="line">
				<div class="line_sec"></div>
				<div class="dot one"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg></div>
				<div class="dot two"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg></div>
				<div class="dot three"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" /></svg></div>
			</div>
			<div class="steps">
				<div class="step step-one"><?php echo $wo['lang']['ad_media']; ?></div>
				<div class="step step-two"><?php echo $wo['lang']['info']; ?></div>
				<div class="step step-three"><?php echo $wo['lang']['follow']; ?></div>
			</div>
		</div>
		<div class="page-margin wow_content">	
			<div class="add-photo wow_usr_steps">
				<h2><?php echo $wo['lang']['follow_head'];?></h2>
				<h4><?php echo $wo['lang']['get_latest_activity'];?></h4>
				<div class="row wow_frnd_usr">
				<?php
					$user_id = array();
					foreach ($wo['users'] as $wo['result']) {
						$user_id[] = $wo['result']['user_id'];
						$wo['result']['no_btn'] = true;
						echo Wo_LoadPage('start_up/user-result');
					}
					echo '<input type="hidden" name="users" id="users-id" value="' . implode(',' , $user_id) . '">';
				?>
				</div>
				<div class="clear"></div>
			</div>
			<div class="continue-button wow_usr_steps_cont">
				<small class="skip-step" onclick="Wo_SkipStep('startup_follow');"><?php echo $wo['lang']['start_up_skip'];?></small>
				<button class="con-button btn btn-main btn-mat btn-mat-raised" onclick="Wo_SubmitFollow();"><?php $string = str_replace('{number}', count($wo['users']), $wo['lang']['follow_num']); echo $string;?></button>
			</div>
		</div>
	</div>
	<div class="col-lg-1"></div>
</div>

<script type="text/javascript">
function Wo_SubmitFollow() {
	$('.con-button').attr('disabled', true);
  $('.con-button').text("<?php echo $wo['lang']['please_wait'];?>");
	var users = $('#users-id').val();
	$.post(Wo_Ajax_Requests_File() + '?f=follow_users', {user:users}, function (data) {
		if (data.status == 200) {
			window.location.href = '<?php echo Wo_SeoLink('index.php?link1=start-up');?>';
		}
	});
}
</script>