<div class="page-margin wow_content"> 
   	  <div class="text-center">
   	    <?php 
        $string = str_replace('{color}', $wo["pro_packages"][$wo['user']['pro_type']]['color'], $wo['lang']['cong']);
        $string = str_replace('{icon}', $wo["pro_packages"][$wo['user']['pro_type']]['image'], $string);
        $string = str_replace('{type_name}', $wo["pro_packages"][$wo['user']['pro_type']]['name'], $string);
        ?>
			<div class="empty_state wow_upgrd_ico">
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 504.12 504.12" xml:space="preserve"> <circle style="fill:#3DB39E;" cx="252.06" cy="252.06" r="252.06"/> <path style="fill:#37A18E;" d="M463.163,114.609L240.246,345.403l0.394,24.812h10.24l241.428-194.56 C485.218,153.994,475.372,133.12,463.163,114.609z"/> <path style="fill:#F2F1EF;" d="M499.397,103.582l-44.505-44.111c-5.908-5.908-15.754-5.908-22.055,0L242.609,256l-82.314-81.132 c-5.908-5.908-15.754-5.908-22.055,0l-39.385,38.991c-5.908,5.908-5.908,15.754,0,21.662L230.4,365.883 c3.545,3.545,8.271,4.726,12.997,4.332c4.726,0.394,9.452-0.788,12.997-4.332l243.003-240.246 C505.305,119.335,505.305,109.489,499.397,103.582z"/> <path style="fill:#E6E5E3;" d="M256.394,365.883l243.003-240.246c5.908-5.908,5.908-15.754,0-21.662l-7.089-6.695L243.003,342.252 L105.157,207.951l-5.908,5.908c-5.908,5.908-5.908,15.754,0,21.662l131.545,130.363c3.545,3.545,8.271,4.726,12.997,4.332 C248.123,370.609,252.849,369.428,256.394,365.883z"/></svg>
				<?php echo $wo['lang']['pro_con'];?> <?php 
        if (!empty(in_array($wo['user']['pro_type'], array_keys($wo['pro_packages'])) && !empty($wo['pro_packages'][$wo['user']['pro_type']]['image'])) && $_COOKIE['mode'] == 'day') { ?>
          <img src="<?php echo($wo['pro_packages'][$wo['user']['pro_type']]['image']) ?>" class="pro_packages_icon_inline"><?php }
        elseif (!empty(in_array($wo['user']['pro_type'], array_keys($wo['pro_packages'])) && !empty($wo['pro_packages'][$wo['user']['pro_type']]['night_image'])) && $_COOKIE['mode'] == 'night') { ?>
          <img src="<?php echo($wo['pro_packages'][$wo['user']['pro_type']]['night_image']) ?>" class="pro_packages_icon_inline">
        <?php }else if($wo['user']['pro_type'] == 1){ ?>
          <i class="fa fa-star fa-fw"></i>
        <?php }else if($wo['user']['pro_type'] == 2){  ?> 
          <i class="fa fa-fire fa-fw"></i>
        <?php }else if($wo['user']['pro_type'] == 3){  ?> 
          <i class="fa fa-bolt fa-fw"></i>
        <?php }else if($wo['user']['pro_type'] == 4){  ?> 
          <i class="fa fa-rocket fa-fw"></i>
        <?php } ?>
        <?php echo $wo['pro_packages'][$wo['user']['pro_type']]['name']; ?>
			</div>
			<a href="<?php echo Wo_SeoLink('index.php?link1=welcome');?>" class="btn btn-main btn-mat btn-mat-raised" style="margin: -30px 0 50px;"><?php echo $wo['lang']['cong_2']?></a>
      </div>
</div>