<tr class="setting-invitation" data-invitation="<?php echo $wo['invitation']['id']; ?>" data_selected="<?php echo($wo['invitation']['id']) ?>">
  <td><input type="checkbox" id="check-data-<?php echo($wo['invitation']['id']) ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo($wo['invitation']['id']) ?>"></label></td>
  <td >
     <?php echo $wo['invitation']['id']; ?>
  </td>
  <td >
     <?php echo Wo_Time_Elapsed_String($wo['invitation']['posted']); ?>
  </td>
  <td>
     <?php echo $wo['invitation']['code']; ?>
  </td>
  <td><span class="badge badge-warning">Pending</span></td>
  <td>
     <button class="btn bg-info admn_table_btn copy-invitation-url" id="<?php echo $wo['invitation']['id']; ?>" data-link="<?php echo $wo['invitation']['url']; ?>">Copy Link</button>
     <button class="btn bg-danger admn_table_btn delete-admin-invitation" id="<?php echo $wo['invitation']['id']; ?>" onclick="DeleteBan(<?php echo $wo['invitation']['id']; ?>,'hide')">Delete</button>
  </td>
</tr>
