<?php echo($wo['reaction_name']) ?>
<div class="form-group form-float">
  <div class="form-line focused">
    <label class="form-label">Reaction Wowonder Theme Icon</label>
        <input type="file" class="form-control" name="wowonder">
  </div>
</div>
<div class="form-group form-float">
  <div class="form-line focused">
    <label class="form-label">Reaction Sunshine Theme Icon</label>
        <input type="file" class="form-control" name="sunshine">
  </div>
</div>
<?php if ($wo['reaction_id'] < 7) { ?>
  <?php if (!empty($wo['wowonder_icon'])) { ?>
<label for="wowonder_to_use">Use Default Icon On Wowonder Theme</label>
<div class="form-group">
    <input type="radio" name="wowonder_to_use" id="wowonder_to_use-enabled" value="1">
    <label for="wowonder_to_use-enabled">Default</label>
</div>
<?php } ?>
<?php if (!empty($wo['sunshine_icon'])) { ?>
<label for="sunshine_to_use">Use Default Icon On Sunshine Theme</label>
<div class="form-group">
    <input type="radio" name="sunshine_to_use" id="sunshine_to_use-enabled" value="1">
    <label for="sunshine_to_use-enabled">Default</label>
</div>
<?php } ?>
<?php } ?>
<input type="hidden" name="id" value="<?php echo($wo['reaction_id']) ?>">