<div class="col-md-6 col-sm-12 nearby_user_wrapper profile user-data" data-user-id="<?php echo $wo['UsersList']['user_id'];?>">
	<div class="avatar">
		<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture" />
    </div>
	&nbsp;&nbsp;&nbsp;
	<div>
		<span class="user-popover" data-id="<?php echo $wo['UsersList']['id'];?>" data-type="<?php echo $wo['UsersList']['type'];?>">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username'];?>" class="user_wrapper_link">
				<?php echo $wo['UsersList']['name']; ?>
				<?php if (!empty($wo['UsersList']['is_open_to_work']) && $wo['config']['website_mode'] == 'linkedin') { ?>
					<span class="wo_open_job_badge" title="<?php echo($wo['lang']['open_to_work']); ?>" data-toggle="tooltip"><svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg></span>
				<?php } ?>
			</a>
		</span>
	  
		<?php if (!empty($wo['UsersList']['family_member'])){ ?>
			<div class="user-lastseen" data-family-member="<?php echo $wo['UsersList']['user_id'];?>">  &#64;<?php echo $wo['UsersList']['family_member']; ?></div>
		<?php } else { ?>
			<?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['showlastseen'] != 0): ?>
				<div class="user-lastseen">
					<?php echo Wo_UserStatus($wo['UsersList']['user_id'],$wo['UsersList']['lastseen']); ?>
				</div>
			<?php endif; ?>
		<?php } ?>
	  
		<div class="user-follow-button">
			<?php echo Wo_GetFollowButton($wo['UsersList']['user_id']);?>
			<?php if (!empty($wo['UsersList']['family_member'])): ?>
				<span data-family-member="<?php echo $wo['UsersList']['user_id'];?>">
					<button type="button" class="btn btn-default btn-sm" onclick="$('#delete_family_mbr_modal').attr('data-family-member-id', '<?php echo $wo['UsersList']['id'];?>').modal('show');">
						<i class="fa fa-times progress-icon" data-icon="fa-times"></i>
						<span class="button-text"> <?php echo $wo['lang']['delete'];?></span>
					</button>
				</span>
			<?php endif; ?>
		</div>
	</div>
</div>