<li class="row user-group-request-<?php echo $wo['group_chat']['group_id'];?>">
	<div class="user-request-list ">
		<div class="user-info">
			<a href="javascript:void(0)">
				<div class="avatar">
					<img src="<?php echo $wo['group_chat']['avatar'];?>" alt="<?php echo $wo['group_chat']['group_name']; ?> Profile Picture" />
				</div>
				<?php echo $wo['group_chat']['group_name']; ?> (<?php echo $wo['lang']['group']; ?>)
				<?php $user = Wo_UserData($wo['group_chat']['user_id']); ?>
				<p><small><?php echo $user['name']." " . $wo['lang']['invited_to_group']; ?></small></p>
			</a>
		</div>
		<div class="accept-btns user-follow-button">
			<button type="button" id="accept-<?php echo $wo['group_chat']['group_id']?>" onclick="Wo_AcceptFollowGroupRequest(<?php echo $wo['group_chat']['group_id'];?>)" class="btn btn-default btn-sm btn-active" title="<?php echo $wo['lang']['accept']; ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check"><polyline points="20 6 9 17 4 12"></polyline></svg>
			</button>
			<button type="button" id="delete-<?php echo $wo['group_chat']['group_id']?>" onclick="Wo_DeleteFollowGroupRequest(<?php echo $wo['group_chat']['group_id'];?>)" class="btn btn-default btn-sm" title="<?php echo $wo['lang']['delete']; ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
			</button>
		</div>
	</div>
</li>