<div class="post-container sun_post job_apply" data-job-apply="<?php echo($wo['job_apply']['id']) ?>">
	<div class="panel panel-white panel-shadow">
		<div class="wo_vew_apld_jobs">
			<div class="wo_vew_apld_head">
				<div class="avatar">
					<a href="<?php echo  $wo['job_apply']['user_data']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['job_apply']['user_data']['username']?>">
						<img src="<?php echo $wo['job_apply']['user_data']['avatar'] ; ?>" id="updateImage-<?php echo $wo['job_apply']['user_data']['user_id']?>" alt="<?php echo $wo['job_apply']['user_data']['username']; ?>">
					</a>
				</div>
				<div class="jinfo">
					<?php if (!empty($wo['job_apply']['user_name'])) { ?>
						<h4><?php echo $wo['job_apply']['user_name']; ?></h4>
					<?php } ?>
					<div class="row">
						<?php if (!empty($wo['job_apply']['location'])) { ?>
							<div class="col-md-5">
								<p class="wo_vew_apld_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#ff5722" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg> <?php echo $wo['job_apply']['location']; ?></p>
							</div>
						<?php } ?>
						<div class="col-md-7">
							<p class="wo_vew_apld_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#4caf50" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M16.2,16.2L11,13V7H12.5V12.2L17,14.9L16.2,16.2Z" /></svg> <span class="ajax-time" title="<?php echo date('c',$wo['job_apply']['time']); ?>"><?php echo Wo_Time_Elapsed_String($wo['job_apply']['time']); ?></span></p>
						</div>
					</div>
					<div class="row">
						<?php if (!empty($wo['job_apply']['phone_number'])) { ?>
							<div class="col-md-5">
								<p class="wo_vew_apld_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#2196f3" d="M6.62,10.79C8.06,13.62 10.38,15.94 13.21,17.38L15.41,15.18C15.69,14.9 16.08,14.82 16.43,14.93C17.55,15.3 18.75,15.5 20,15.5A1,1 0 0,1 21,16.5V20A1,1 0 0,1 20,21A17,17 0 0,1 3,4A1,1 0 0,1 4,3H7.5A1,1 0 0,1 8.5,4C8.5,5.25 8.7,6.45 9.07,7.57C9.18,7.92 9.1,8.31 8.82,8.59L6.62,10.79Z" /></svg> <?php echo $wo['job_apply']['phone_number']; ?></p>
							</div>
						<?php } ?>
						<?php if (!empty($wo['job_apply']['email'])) { ?>
							<div class="col-md-7">
								<p class="wo_vew_apld_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#e91e63" d="M20,8L12,13L4,8V6L12,11L20,6M20,4H4C2.89,4 2,4.89 2,6V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V6C22,4.89 21.1,4 20,4Z" /></svg> <?php echo $wo['job_apply']['email']; ?></p>
							</div>
						<?php } ?>
					</div>
					<?php if ($wo['loggedin'] == true) { ?>
						<div class="wo_vew_apld_msg">
							<?php if (!empty($wo['page_profile'])) { ?>
								<button type="button" class="btn btn-main" onclick="Wo_OpenChatTab(0,0,0,<?php echo $wo['page_profile']['page_id']; ?>,<?php echo $wo['job_apply']['user_data']['user_id']; ?>)"><?php echo $wo['lang']['message'] ?></button>
							<?php }else{ ?>
								<button type="button" class="btn btn-main" onclick="Wo_OpenChatTab(<?php echo $wo['user_profile']['user_id']; ?>)"><?php echo $wo['lang']['message'] ?></button>
							<?php } ?>
						</div>
					<?php } ?>
				</div>
			</div>
			<div class="wo_vew_apld_blocks">
				<?php if (!empty($wo['job_apply']['where_did_you_work'])) { ?>
					<div class="wo_vew_apld_blkmrgn">
						<b><?php echo $wo['lang']['where_did_you_work']; ?></b>
						<p class="edited_text"><?php echo $wo['job_apply']['where_did_you_work']; ?></p>
					</div>
				<?php } ?>
				<div class="row">
					<div class="col-md-7">
					<?php if (!empty($wo['job_apply']['position'])) { ?>
						<div class="wo_vew_apld_blkmrgn">
							<b><?php echo $wo['lang']['position']; ?></b>
							<p class="edited_text"><?php echo $wo['job_apply']['position']; ?></p>
						</div>
					<?php } ?>
					</div>
					<div class="col-md-5">
						<div class="row">
							<div class="col-md-6">
								<?php if (!empty($wo['job_apply']['experience_start_date'])) { ?>
									<div class="wo_vew_apld_blkmrgn">
										<b><?php echo $wo['lang']['start_date']; ?></b>
										<p class="edited_text"><?php echo $wo['job_apply']['experience_start_date']; ?></p>
									</div>
								<?php } ?>
							</div>
							<div class="col-md-6">
								<?php if (!empty($wo['job_apply']['experience_end_date'])) { ?>
									<div class="wo_vew_apld_blkmrgn">
										<b><?php echo $wo['lang']['end_date']; ?></b>
										<p class="edited_text"><?php echo $wo['job_apply']['experience_end_date']; ?></p>
									</div>
								<?php } ?>
							</div>
						</div>
					</div>
				</div>
				<?php if (!empty($wo['job_apply']['experience_description'])) { ?>
					<div>
						<b><?php echo $wo['lang']['description']; ?></b>
						<p class="edited_text"><?php echo $wo['job_apply']['experience_description']; ?></p>
					</div>
				<?php } ?>
			</div>
			<div class="wo_vew_apld_blocks">
				<?php if (!empty($wo['job_apply']['question_one_answer']) && !empty($wo['job_apply']['job_info']['question_one'])) { ?>
					<div class="wo_vew_apld_blkmrgn">
						<b><?php echo $wo['job_apply']['job_info']['question_one']; ?></b>
						<?php if ($wo['job_apply']['job_info']['question_one_type'] == 'multiple_choice_question') { ?>
							<p class="edited_text"><?php echo $wo['job_apply']['job_info']['question_one_answers'][$wo['job_apply']['question_one_answer']]; ?></p>
						<?php  } else{ ?>
							<p class="edited_text"><?php echo $wo['job_apply']['question_one_answer']; ?></p>
						<?php  } ?>
					</div>
				<?php } ?>
				<?php if (!empty($wo['job_apply']['question_two_answer']) && !empty($wo['job_apply']['job_info']['question_two'])) { ?>
					<div class="wo_vew_apld_blkmrgn">
						<b><?php echo $wo['job_apply']['job_info']['question_two']; ?></b>
						<?php if ($wo['job_apply']['job_info']['question_two_type'] == 'multiple_choice_question') { ?>
							<p class="edited_text"><?php echo $wo['job_apply']['job_info']['question_two_answers'][$wo['job_apply']['question_two_answer']]; ?></p>
						<?php  } else{ ?>
							<p class="edited_text"><?php echo $wo['job_apply']['question_two_answer']; ?></p>
						<?php  } ?>
					</div>
				<?php } ?>
				<?php if (!empty($wo['job_apply']['question_three_answer']) && !empty($wo['job_apply']['job_info']['question_three'])) { ?>
					<div>
						<b><?php echo $wo['job_apply']['job_info']['question_three']; ?></b>
						<?php if ($wo['job_apply']['job_info']['question_three_type'] == 'multiple_choice_question') { ?>
							<p class="edited_text"><?php echo $wo['job_apply']['job_info']['question_three_answers'][$wo['job_apply']['question_three_answer']]; ?></p>
						<?php  } else{ ?>
							<p class="edited_text"><?php echo $wo['job_apply']['question_three_answer']; ?></p>
						<?php  } ?>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>