<div class="page_list row boosted_pages">
	<div class="col-xs-2 col-md-2 no-padding-left">
		<a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
			<div class="avatar">
				<img src="<?php echo $wo['page']['avatar'];?>" alt="<?php echo $wo['page']['page_name']; ?> Profile Picture" />
			</div>
		</a>
	</div>
	<div class="<?php if( isset( $wo['page']['Wo_PageSug'] ) ){ ?>col-xs-6 col-md-6<?php }else{ ?>col-xs-8 col-md-8<?php } ?>">
		<a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
			<span class="page_title"><?php echo $wo['page']['page_title']; ?></span>
		</a>
		<div class="page_info">
			<ul>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-thumbs-up"><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path></svg> <?php echo Wo_CountPageLikes($wo['page']['page_id']);?> <?php echo $wo['lang']['people_likes_this']; ?>
				</li>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-feather"><path d="M20.24 12.24a6 6 0 0 0-8.49-8.49L5 10.5V19h8.5z"></path><line x1="16" y1="8" x2="2" y2="22"></line><line x1="17" y1="15" x2="9" y2="15"></line></svg> <?php echo Wo_CountPagePosts($wo['page']['page_id']);?> <?php echo $wo['lang']['posts']; ?>
				</li>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3" y2="6"></line><line x1="3" y1="12" x2="3" y2="12"></line><line x1="3" y1="18" x2="3" y2="18"></line></svg> <?php echo $wo['page']['category']?>
				</li>
				<?php if (!empty($wo['page']['page_sub_category'])) { ?>
				<li>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z" /></svg> <?php echo $wo['page']['page_sub_category']; ?>
				</li>
				<?php } ?>
			</ul>
		</div>
	</div>
	<div class="<?php if( isset( $wo['page']['Wo_PageSug'] ) ){ ?>col-xs-4 col-md-4<?php }else{ ?>col-xs-2 col-md-2<?php } ?>">
		<div class="text-right">
			<?php if( isset( $wo['page']['Wo_PageSug'] ) ){ ?>
				<?php echo Wo_GetLikeButton($wo['page']['page_id']);?>
			<?php }else{ ?>
		    	<a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' .  $wo['page']['page_name']); ?>" data-ajax="?link1=page-setting&page=<?php echo $wo['page']['page_name'];?>" class="btn btn-info btn-sm" title="<?php echo $wo['lang']['edit']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><polygon points="16 3 21 8 8 21 3 21 3 16 16 3"></polygon></svg></a>
			<?php } ?>
		</div>
	</div>
</div>