<div class="wo_comthing_usr col-md-3" id="<?php echo $wo['UsersList']['user_data']['id']; ?>">
	<div class="wo_comthing_usr_innr" onclick="Wo_ShowCommonUserProfile('<?php echo $wo['UsersList']['user_data']['user_id']?>');">
		<div class="avatar">
			<img src="<?php echo $wo['UsersList']['user_data']['avatar'];?>" alt="<?php echo $wo['UsersList']['user_data']['name']; ?> Profile Picture" />
		</div>
		<h3><?php echo $wo['UsersList']['user_data']['name']; ?></h3>
		<?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['user_data']['showlastseen'] != 0): ?>
			<!--<p>
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg>
				<?php
					if ($wo['UsersList']['user_data']['age'] && $wo['UsersList']['user_data']['birth_privacy'] == 0) {
						echo $wo['UsersList']['user_data']['age'];
					} else {
						echo Wo_UserStatus($wo['UsersList']['user_data']['user_id'], $wo['UsersList']['user_data']['lastseen']);
					}
				?>
			</p>-->
		<?php endif; ?>
		<p>
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15,2C16.94,2 18.59,2.7 19.95,4.05C21.3,5.41 22,7.06 22,9C22,10.56 21.5,11.96 20.58,13.2C19.64,14.43 18.44,15.27 16.97,15.7L17,15.38V15C17,12.81 16.23,10.93 14.65,9.35C13.07,7.77 11.19,7 9,7H8.63L8.3,7.03C8.73,5.56 9.57,4.36 10.8,3.42C12.04,2.5 13.44,2 15,2M9,8A7,7 0 0,1 16,15A7,7 0 0,1 9,22A7,7 0 0,1 2,15A7,7 0 0,1 9,8M9,10A5,5 0 0,0 4,15A5,5 0 0,0 9,20A5,5 0 0,0 14,15A5,5 0 0,0 9,10Z" /></svg>
			<?php
				if ($wo['UsersList']['common_things'] == 1) {
					echo $wo['UsersList']['common_things'] .' '. $wo['lang']['thing_in_common'];
				}else{
					echo $wo['UsersList']['common_things'] .' '. $wo['lang']['things_in_common'];
				} 
			?>
		</p>
	</div>
	<div class="clear"></div>
</div>